### ISSUE TITLE
Installation of the Zeek/Linux using the docker pull Repo : Error encountered as i tried to install FleetSpeak Service on Windows Client(dbg_GRR_3.4.6.7_amd64.msi/GRR_3.4.6.7_amd64.msi

### ISSUE THREAD

**Issue by Yashil06** [google/grr#1032]
**Environment**

- How did you install GRR? [e.g. from release DEB, HEAD DEB, PIP package, source] :  

docker run \
  --name grr-server \
  -e EXTERNAL_HOSTNAME=<your-external-hostname> \
  -e ADMIN_PASSWORD=<your-admin-password> \
  -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 \
  -v grr-data:/data \
  ghcr.io/google/grr:v3.4.6.7

- What GRR version are you running?: [e.g. 3.1.2.3]

3.4.6.7_amd64.amsi

- What operating system does the GRR server run on? [e.g. Ubuntu 18.04]
                                                       
┌──(root㉿kali)-[/var/log]
└─# uname -a   
Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux

- What operating system does the affected GRR client run on, if applicable? [e.g. Windows 10]

Windows specifications : 

edition : Windows  10 Home
Version : 22H2
OS.Build : 19045.2846 

**Describe the issue**
Describe the issue that occurs and list steps to reproduce this behavior. Make sure to read [GRR server doesn't seem to run](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/troubleshooting.html) and [I don't see my clients](https://grr-doc.readthedocs.io/en/latest/deploying-grr-clients/troubleshooting.html). If the errors occur after an upgrade, make sure to read [CHANGELOG](https://github.com/google/grr/blob/master/CHANGELOG) for possible reasons.

**Error logs**
""
Here is the following encountered Error Message as i try to install the "GRR_3.4.6.7_amd64.msi application". 
""

Error Prompt : 

- Service "Fleetspeak Service" (Fleetspeak Service) failed to start.Verify that you have the sufficient privileges to start system services. 

```
Copy-and-paste logs from the command you executed, GRR server log files, or flow logs.

```

Using the log file : 

- Windows: %WinDir%\system32\logfiles\GRR_installer.txt

Loading configuration  from C:\WINDOWS\system32\GRR\3.4.6.7\GRR.exe.yaml
Loading configuration from C:\WINDOWS\system32\GRR\3.4.6.7\build.yaml
Starting installation procedure for GRR client.
Trying to stop service FleetspeakService.
Tried to stop 'FleetspeakService', but the service is not installed.
Trying to start service FleetspeakService.
Tried to start 'FleetspeakService', but the service is not installed.

**Additional context**

-The WebUI works perfectly, just for when I've tried to install the fleetspeak service, missing "fleetspeak service" 
from services.msc". 

Some of the Repo to build  Fleetspeak service, from github has a "404 error code."

Thank you, any response will be very much appreciated. 

Furthermore i will like to add these two files for your convenience , in case this has to do with any conflict within them. 
[GRR.exe.yaml.txt
[GRR_fleetspeak_service_config.txt](https://github.com/google/grr/files/11457585/GRR_fleetspeak_service_config.txt)
](https://github.com/google/grr/files/11457580/GRR.exe.yaml.txt)

**Comment by Yashil06** [comment]
Just want to add a few debugging lines : 

c:\Windows\System32\GRR\3.4.6.7>

c:\Windows\System32\GRR\3.4.6.7>GRR.exe --config grr.exe.yaml --verbose
I0512 01:08:42.277603 20712 client_logging.py:113] Writing log file to C:\WINDOWS\System32\logfiles\\GRR.log
INFO:2023-05-12 01:08:42,277 client_logging:113] Writing log file to C:\WINDOWS\System32\logfiles\\GRR.log
INFO:2023-05-12 01:08:42,418 regconfig:87] Writing back configuration to key HKEY_LOCAL_MACHINE\Software\GRR.
DEBUG:2023-05-12 01:08:42,532 config_lib:405] Applying filter env for SystemRoot.
INFO:2023-05-12 01:08:42,534 sandbox:40] Initializing sandbox. Name: GRR_3.4.6.7. Read-only paths: ['C:\\WINDOWS\\System32\\GRR\\3.4.6.7'].
Traceback (most recent call last):
  File "Lib\site-packages\grr_response_client\client.py", line 36, in <module>
  File "absl\app.py", line 308, in run
  File "absl\app.py", line 254, in _run_main
  File "grr_response_client\client_main.py", line 90, in main
  File "grr_response_client\fleetspeak_client.py", line 64, in __init__
  File "fleetspeak\client_connector\connector.py", line 108, in __init__
  File "fleetspeak\client_connector\connector.py", line 63, in _EnvOpen
ValueError: FLEETSPEAK_COMMS_CHANNEL_INFD is not set
[5964] Failed to execute script 'client' due to unhandled exception!
