### ISSUE TITLE
FAILURE RUNNING: grr_config_updater initialize 

### ISSUE THREAD

**Issue by ega103083** [google/grr#146]
Hi, 

Attempting to get GRR running but received this error. Restored VM to first install and updated PROTOBUF from source as I've seen others mention to no avail. Any help is greatly appreciated. 

##########################################################################################
     Installing GRR from prebuilt package
##########################################################################################
2015-03-31 22:45:46 URL:https://72db995be8d9351a447467116a957b52ccdca415.googledrive.com/host/0B1wsLqFoT7i2c3F0ZmI1RDJlUEU/grr-server_0.3.0-2_amd64.deb [95542086] -> "grr-server_0.3.0-2_amd64.deb" [1]
(Reading database ... 183327 files and directories currently installed.)
Preparing to unpack grr-server_0.3.0-2_amd64.deb ...
Unpacking grr-server (0.3.0-2) over (0.3.0-2) ...
Setting up grr-server (0.3.0-2) ...
########################################################
Post install done

Next step if new install:
   Run:   sudo grr_config_updater initialize

If upgrading see:
https://code.google.com/p/grr/wiki/ServerUpgrades
########################################################
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot

##########################################################################################
     Initialize the configuration, building clients and setting options.
##########################################################################################
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.2', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 48, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 476, in main
    startup.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/startup.py", line 92, in Init
    registry.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 186, in Init
    InitHook().Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 151, in Init
    self._RunAllHooks(executed_hooks)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 141, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 131, in _RunSingleHook
    cls_instance.Run()
  File "/usr/lib/python2.7/dist-packages/grr/lib/data_store.py", line 627, in Run
    DB = cls()  # pylint: disable=g-bad-name
  File "/usr/lib/python2.7/dist-packages/grr/lib/data_stores/mongo_data_store.py", line 34, in __init__
    port=int(config_lib.CONFIG["Mongo.port"]))
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 352, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
Exception AttributeError: "'MongoDataStore' object has no attribute 'flusher_thread'" in <bound method MongoDataStore.__del__ of <grr.lib.data_stores.mongo_data_store.MongoDataStore object at 0x7fc68c656d90>> ignored
#########################################################################################
FAILURE RUNNING: grr_config_updater initialize

**Comment by ega103083** [comment]
I've attempted to troubleshoot MongoDB, but I'm not too familiar with it. Start/Stop and attempted a --repair with no luck.

**Comment by grrrrrrrrr** [comment]
Hey Greg,

As you correctly pointed out, this is a problem with MongoDB, not GRR. In order to troubleshoot this, I'd have a look at the MongoDB log at /var/log/mongodb/mongodb.log to see what's going wrong.

Otherwise, I'd recommend that you run the install script with -t to get a much more recent testing server version of GRR. That version is close to release and very stable. If you use that version, you can also use the SQLite data store instead of Mongo and get rid of all those problems by adding

Datastore.implementation: SqliteDataStore

to the /etc/grr/server.local.yaml config file.

Cheers,
-Andy

**Comment by ega103083** [comment]
Andy, 

Thanks for getting back to me so quickly. I checked the log and sure enough their wasn't enough space for the journal. Expanded volume in the VM and it's up and running. Thanks for the tip!
