### ISSUE TITLE
Artifact Manager

### ISSUE THREAD

**Issue by pidydx** [google/grr#153]
We are getting this error when attempting to use Artifact Manager after the changes to artifacts

Error: Traceback (most recent call last):
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/views.py", line 160, in RenderGenericRenderer
    result = method(request, result) or result
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/plugins/artifact_view.py", line 190, in Layout
    return super(ArtifactManagerView, self).Layout(request, response)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/renderers.py", line 656, in Layout
    self.table_contents = delegate_renderer.RenderAjax(request, tmp).content
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/renderers.py", line 705, in RenderAjax
    row.append(utils.SmartStr(c.RenderRow(index, request, row_options)))
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/plugins/semantic.py", line 89, in RenderRow
    result = renderer.RawHTML(request)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/gui/plugins/artifact_view.py", line 131, in Layout
    self.artifact_str = self.proxy.ToPrettyJson()
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/rdfvalues/artifacts.py", line 86, in ToPrettyJson
    artifact_dict = self.ToPrimitiveDict()
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/rdfvalues/artifacts.py", line 61, in ToPrimitiveDict
    for source in artifact_dict["sources"]:
KeyError: 'sources'

**Comment by pidydx** [comment]
This appears to be caused by having artifacts of the old format already loaded. I'm not sure what the best way to handle this is since you can't delete the old ones after the server update due to the exception.

**Comment by destijl** [comment]
argh, yeah I meant to tell people to clear this out but forgot.  I'll add it to the release notes.  Either delete from the database directly, or clear out the new artifacts and roll back to the old version and delete.

**Comment by pidydx** [comment]
I will go ahead and close this then.  It seems like that is probably the best solution that doesn't involve a bunch of extra code for backwards compatibility/conversion.
