### ISSUE TITLE
First Initialize attempt fails.  Second attempt works.

### ISSUE THREAD

**Issue by pidydx** [google/grr#168]
During initialize with no keys this happens.  A second attempt after all the keys have been written to the server.local.yaml file succeeds.

Step 4: Uploading Memory Drivers to the Database
Signing and uploading /opt/grr/share/grr/binaries/OSXPMem-signed.tar.gz to aff4:/config/drivers/osx/memory/pmem-signed
Traceback (most recent call last):
  File "/opt/grr/bin64/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-6', 'console_scripts', 'grr_config_updater')()
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/tools/config_updater.py", line 573, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/tools/config_updater.py", line 510, in Initialize
    LoadMemoryDrivers(flags.FLAGS.share_dir, token=token)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/tools/config_updater.py", line 307, in LoadMemoryDrivers
    client_context=client_context, token=token)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/maintenance_utils.py", line 113, in UploadSignedDriverBlob
    blob_rdf.Sign(content, sig_key, ver_key, prompt=True)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_6-py2.7.egg/grr/lib/rdfvalues/crypto.py", line 173, in Sign
    rsa = signing_key.GetPrivateKey(callback=callback)
AttributeError: 'NoneType' object has no attribute 'GetPrivateKey'

**Comment by destijl** [comment]
Not sure how to reproduce this.  I checked initialize after install works by running:
```
vagrant up ubuntu_trusty64
```
which uses the quickstart install script, and completed fine.  Then I did:
```
sudo mv /etc/grr/server.local.yaml ~/server.local.yaml
sudo grr_config_updater initialize
```
which also worked fine.

**Comment by pidydx** [comment]
I'm actually not even sure now.  I thought maybe I had a merge issue because I was able to reproduce it on two of our dev systems, but using the latest in github even with our branches I can't reproduce.
