### ISSUE TITLE
Failing unit tests.  

### ISSUE THREAD

**Issue by pidydx** [google/grr#189]
I am getting the following failure on clean clones of the master branch when trying to run unit tests, but the checkins to github seem to test correctly.  

ERROR: testProtoFileDescriptorIsGeneratedForDynamicType (grr.lib.rdfvalues.structs_test.RDFStructsTest)

RDFStructsTest.testProtoFileDescriptorIsGeneratedForDynamicType - 

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/seagill/test/grr/lib/test_lib.py", line 437, in run
    testMethod()
  File "/home/seagill/test/grr/lib/rdfvalues/structs_test.py", line 138, in testProtoFileDescriptorIsGeneratedForDynamicType
    "grr_export")
  File "/home/seagill/test/grr/lib/rdfvalues/structs.py", line 2002, in EmitProtoFileDescriptor
    for fd_dep in fd.dependencies:
AttributeError: 'FileDescriptor' object has no attribute 'dependencies'

----------------------------------------------------------------------
Ran 17 tests in 1.822s

**Comment by mbushkov** [comment]
Hi Sean,
Please upgrade your protobuf library to 2.6.1. Seems like you have version
2.5 installed which has a different reflection API.

Cheers,
Misha

**Comment by pidydx** [comment]
That got rid of that error and now produces this error.
ERROR: testProtoFileDescriptorIsGeneratedForDynamicType (grr.lib.rdfvalues.structs_test.RDFStructsTest)

RDFStructsTest.testProtoFileDescriptorIsGeneratedForDynamicType - 

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/seagill/grr/lib/test_lib.py", line 437, in run
    testMethod()
  File "/home/seagill/grr/lib/rdfvalues/structs_test.py", line 143, in testProtoFileDescriptorIsGeneratedForDynamicType
    proto_descriptor = pool.FindMessageTypeByName("grr_export.DynamicTypeTest")
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 236, in FindMessageTypeByName
    self.FindFileContainingSymbol(full_name)
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 222, in FindFileContainingSymbol
    return self._ConvertFileProtoToFileDescriptor(file_proto)
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 268, in _ConvertFileProtoToFileDescriptor
    built_deps = list(self._GetDeps(file_proto.dependency))
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 614, in _GetDeps
    dep_desc = self.FindFileByName(dependency)
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 186, in FindFileByName
    return self._ConvertFileProtoToFileDescriptor(file_proto)
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 268, in _ConvertFileProtoToFileDescriptor
    built_deps = list(self._GetDeps(file_proto.dependency))
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 614, in _GetDeps
    dep_desc = self.FindFileByName(dependency)
  File "/opt/grr/lib64/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 183, in FindFileByName
    raise error
KeyError: u'grr/proto/semantic.proto'

----------------------------------------------------------------------
Ran 17 tests in 1.582s

**Comment by destijl** [comment]
We actually have a dependency on 2.6.1? That means the server install script is broken because trusty only comes with 2.5.0 and the script uses the system packages.

**Comment by mbushkov** [comment]
Greg, this is a recently introduced dependency, but yes - we should upgrade
the server install script.
Sean, I'll look into this issue. How do you run the tests (what's your
working directory and what command do you use)?

Cheers,
Misha

**Comment by pidydx** [comment]
I make sure that grr is not installed (site-packages/grr-*) then I run the test out of my home dir setting pythonpath to ./ with the grr repo checked out into my home dir (~/grr/)

**Comment by mbushkov** [comment]
Sean, thanks for the reply - working dir location doesn't seem to be a
problem. Have you recompiled the protos with the 2.6.1 protoc compiler?

Cheers,
Misha

**Comment by pidydx** [comment]
I thought I had, but I just forced it and ran into ldconfig issues so I apparently didn't recompile them.  I fixed the library stuff when trying to run protoc and recompiled them and the unit test worked.  Thanks!
