### ISSUE TITLE
Invalid User Error

### ISSUE THREAD

**Issue by pidydx** [google/grr#224]
This is a file finder hunt using %%users.homedir%%. 

ERROR:2015-07-13 10:56:50,689 flow_runner:924] Error in flow aff4:/hunts/H:34C43678/C.37008215b38b937d/H:FB9EBDCA (aff4:/C.37008215b38b937d). Trace: Traceback (most recent call last):
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 569, in RunStateMethod
    responses=responses)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/flows/general/file_finder.py", line 146, in Start
    no_file_type_check=self.args.no_file_type_check)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/flows/general/filesystem.py", line 549, in GlobForPaths
    patterns.extend(path.Interpolate(client=client))
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/paths.py", line 242, in Interpolate
    for pattern in patterns:
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/paths.py", line 279, in InterpolateClientAttributes
    for rdf_value in attr_accessor(match.group(1)):
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/paths.py", line 269, in <lambda>
    attr_accessor = lambda x: client.GetValuesForAttribute(x, only_one=True)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/aff4.py", line 2005, in GetValuesForAttribute
    attribute = Attribute.GetAttributeByName(attribute)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0.post6-py2.7-linux-x86_64.egg/grr/lib/aff4.py", line 1244, in GetAttributeByName
    raise AttributeError("Invalid attribute %s" % name)
AttributeError: Invalid attribute users

**Comment by mbushkov** [comment]
Sean, is it a one-time error or do you see it a lot in the logs? If you see many errors like these, do they happen on the same client or not?

**Comment by pidydx** [comment]
Multiple errors, different clients, but all the same hunt.

**Comment by destijl** [comment]
This works for us at the moment, reopen if it's still a problem.
