### ISSUE TITLE
build process error caused by proto files

### ISSUE THREAD

**Issue by tomkkk** [google/grr#225]
using quickstart script to install depencies only - on fresh ubuntu 14.10 setup, mongodb up and running
```
    sudo bash install_script_ubuntu.sh -d
```

when trying to build & install from source after cloning git repo:
```
python setup.py build 
```
i get the following 
```
grr$ python setup.py build
running build
running build_py
(cd ../..; protoc --python_out=. --proto_path=. --proto_path=/usr/include --proto_path=/usr/local/include grr/proto/api.proto )
grr/proto/jobs.proto:684:17: Option field "(label)" is repeated. Repeated options are not supported.
grr/proto/jobs.proto:685:18: Option field "(label)" is repeated. Repeated options are not supported.
grr/proto/anomaly.proto: Import "grr/proto/jobs.proto" was not found or had errors.
grr/proto/anomaly.proto:53:12: "PathSpec" is not defined.
grr/proto/sysinfo.proto: Import "grr/proto/jobs.proto" was not found or had errors.
grr/proto/sysinfo.proto:113:12: "AttributedDict" is not defined.
grr/proto/sysinfo.proto:142:12: "StatEntry" is not defined.
grr/proto/sysinfo.proto:151:12: "Dict" is not defined.
grr/proto/sysinfo.proto:288:12: "StatEntry" is not defined.
grr/proto/sysinfo.proto:326:12: "AttributedDict" is not defined.
grr/proto/export.proto: Import "grr/proto/anomaly.proto" was not found or had errors.
grr/proto/export.proto: Import "grr/proto/jobs.proto" was not found or had errors.
grr/proto/export.proto: Import "grr/proto/sysinfo.proto" was not found or had errors.
grr/proto/export.proto:192:12: "StatEntry.RegistryType" is not defined.
grr/proto/export.proto:228:12: "NetworkConnection.Family" is not defined.
grr/proto/export.proto:229:12: "NetworkConnection.Type" is not defined.
grr/proto/export.proto:230:12: "NetworkEndpoint" is not defined.
grr/proto/export.proto:231:12: "NetworkEndpoint" is not defined.
grr/proto/export.proto:232:12: "NetworkConnection.State" is not defined.
grr/proto/export.proto:238:12: "Anomaly.AnomalyType" is not defined.
grr/proto/export.proto:242:12: "Anomaly.AnomalyLevel" is not defined.
grr/proto/export.proto:246:12: "Anomaly.AnomalyLevel" is not defined.
grr/proto/output_plugin.proto: Import "grr/proto/export.proto" was not found or had errors.
grr/proto/output_plugin.proto:60:12: "ExportOptions" is not defined.
grr/proto/flows.proto: Import "grr/proto/jobs.proto" was not found or had errors.
grr/proto/flows.proto: Import "grr/proto/output_plugin.proto" was not found or had errors.
grr/proto/flows.proto:73:12: "GrrMessage.Priority" is not defined.
grr/proto/flows.proto:135:12: "RequestState" is not defined.
grr/proto/flows.proto:191:12: "OutputPluginDescriptor" is not defined.
grr/proto/flows.proto:209:12: "ForemanAttributeRegex" is not defined.
grr/proto/flows.proto:214:12: "ForemanAttributeInteger" is not defined.
grr/proto/flows.proto:219:12: "GrrMessage.Priority" is not defined.
grr/proto/flows.proto:316:12: "OutputPluginDescriptor" is not defined.
grr/proto/flows.proto:333:12: "OutputPluginDescriptor" is not defined.
grr/proto/flows.proto:401:12: "Certificate" is not defined.
grr/proto/flows.proto:407:12: "PathSpec" is not defined.
grr/proto/flows.proto:423:12: "Dict" is not defined.
grr/proto/flows.proto:433:12: "Dict" is not defined.
grr/proto/flows.proto:599:12: "PathSpec" is not defined.
grr/proto/flows.proto:609:12: "Hash" is not defined.
grr/proto/flows.proto:640:12: "DriverInstallTemplate" is not defined.
grr/proto/flows.proto:654:12: "DriverInstallTemplate" is not defined.
grr/proto/flows.proto:668:12: "DriverInstallTemplate" is not defined.
grr/proto/flows.proto:675:12: "RekallRequest" is not defined.
grr/proto/flows.proto:704:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:718:12: "FindSpec" is not defined.
grr/proto/flows.proto:725:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:750:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:773:12: "PathSpec" is not defined.
grr/proto/flows.proto:779:12: "PathSpec" is not defined.
grr/proto/flows.proto:798:12: "PathSpec" is not defined.
grr/proto/flows.proto:811:12: "GrepSpec" is not defined.
grr/proto/flows.proto:821:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:825:12: "PathSpec" is not defined.
grr/proto/flows.proto:848:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:852:12: "PathSpec" is not defined.
grr/proto/flows.proto:871:12: "FindSpec" is not defined.
grr/proto/flows.proto:888:12: "PathSpec" is not defined.
grr/proto/flows.proto:914:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:1059:12: "PlistRequest" is not defined.
grr/proto/flows.proto:1081:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:1092:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:1181:12: "PathSpec" is not defined.
grr/proto/flows.proto:1201:12: "PathSpec" is not defined.
grr/proto/flows.proto:1471:12: "PathSpec.PathType" is not defined.
grr/proto/flows.proto:1497:12: "StatEntry" is not defined.
grr/proto/flows.proto:1498:12: "BufferReference" is not defined.
grr/proto/flows.proto:1499:12: "Hash" is not defined.
grr/proto/flows.proto:1507:12: "PathSpec" is not defined.
grr/proto/flows.proto:1629:12: "NetworkAddress.Family" is not defined.
grr/proto/flows.proto:1675:12: "DriverInstallTemplate" is not defined.
grr/proto/flows.proto:1736:12: "PathSpec.PathType" is not defined.
grr/proto/api.proto: Import "grr/proto/flows.proto" was not found or had errors.
grr/proto/api.proto:144:12: "ExportHuntResultsFilesAsArchiveArgs.ArchiveFormat" is not defined.
Makefile:27: recipe for target 'api_pb2.py' failed
make: *** [api_pb2.py] Error 1
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    cmdclass={"build_py": MyBuild})
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 23, in run
    subprocess.check_call(["make"], shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
```
using python 2.7.8:
```
`Python 2.7.8 (default, Jun 18 2015, 18:54:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.VERSION
(1, 6, 0, 'final', 0)
```

using the quickstart install script without parameters works fine, but I'd really like to build and install manually. Any hints on what I'm overseeing here?

**Comment by grrrrrrrrr** [comment]
Hey,

What's your protobuf version? Please use 2.6.1 or later, it seems that
yours is too old...

Cheers,
-Andy

**Comment by tomkkk** [comment]
hah jesus, great, that did the trick. 2.5.0 is not sufficient.
thanks a lot for fast response on this more like.. "support" -ish topic!

**Comment by destijl** [comment]
Filed https://github.com/google/grr-doc/issues/19
