### ISSUE TITLE
Initialize dies if you choose MySQL "No Storage System MySQLAdvancedDataStore"

### ISSUE THREAD

**Issue by destijl** [google/grr#237]
Via brian...

```
I built a vanilla Ubuntu 14.04 system today for some testing and found that grr_config_updater initialize will fail if you select MySQL as the datastore. Manually installing "mysql-server" and "python-mysqldb" resolves the issue so the initialize command will succeed. Should these packages be added to the installation script when the MySQL datastore is selected?

Error included below for searchability :)

Configuration parameters set. You can edit these in /etc/grr/server.local.yaml
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 785, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 707, in Initialize
    AddUsers(token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 638, in AddUsers
    startup.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/startup.py", line 107, in Init
    registry.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 220, in Init
    InitHook().Init(skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 185, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 175, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 163, in _RunSingleHook
    cls_instance.Run()
  File "/usr/lib/python2.7/dist-packages/grr/lib/data_store.py", line 686, in Run
    config_lib.CONFIG["Datastore.implementation"])
RuntimeError: No Storage System MySQLAdvancedDataStore found.
```
@pidydx intended the script to wait until the DB is available rather than die. And at the point it prompts you for the DB it should make it clear that it needs the DB to proceed and give you the apt-get command to run to install mysql and python libraries. In fact it should probably link to a short doc about setting up the MySQL DB because you'll need a user with the right permissions.

**Comment by pidydx** [comment]
https://github.com/google/grr/pull/235 should fix the main problem here.
