### ISSUE TITLE
Artifact KnowledgeBase users.local_settings missing #197 v2

### ISSUE THREAD

**Issue by brian-olson** [google/grr#239]
This bug (https://github.com/google/grr/issues/197) reappears if you attempt to use "Collectors" via the Hunt interface. 

================================================
Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/views.py", line 156, in RenderGenericRenderer
    result = method(request, result) or result
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/new_hunt.py", line 179, in Layout
    return super(HuntFlowForm, self).Layout(request, response)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/flow_management.py", line 278, in Layout
    prefix="args").RawHTML(request)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/forms.py", line 182, in Layout
    self.form_elements.append(type_renderer.RawHTML(request))
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/artifact_view.py", line 88, in Layout
    reload_datastore_artifacts=True):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 208, in GetArtifacts
    self._CheckDirty(reload_datastore_artifacts=reload_datastore_artifacts)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 186, in _CheckDirty
    self._LoadArtifactsFromDatastore(self._sources["datastores"])
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 66, in _LoadArtifactsFromDatastore
    artifact_value.Validate()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 651, in Validate
    self.ValidateSyntax()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 630, in ValidateSyntax
    "fields: %s" % (cls_name, dep, valid_provides))
ArtifactDefinitionError: Artifact InternetExplorerHistory has an invalid path dependency: 'users.local_settings', not in KB fields: ['code_page', 'current_control_set', 'domain', 'environ_allusersappdata', 'environ_allusersprofile', 'environ_path', 'environ_programfiles', 'environ_programfilesx86', 'environ_systemdrive', 'environ_systemroot', 'environ_temp', 'environ_windir', 'hostname', 'os', 'os_major_version', 'os_minor_version', 'os_release', 'time_zone', 'users.appdata', 'users.cookies', 'users.desktop', 'users.full_name', 'users.gid', 'users.gids', 'users.homedir', 'users.internet_cache', 'users.last_logon', 'users.localappdata', 'users.localappdata_low', 'users.personal', 'users.pw_entry', 'users.recent', 'users.shell', 'users.sid', 'users.startup', 'users.temp', 'users.uid', 'users.userdomain', 'users.username', 'users.userprofile']

**Comment by grrrrrrrrr** [comment]
It seems like you still have the old artifact that uses the wrong path somewhere. Since the exception happens in _LoadArtifactsFromDatastore I suspect you have it uploaded to your db. Can you maybe check if this is true? If so, just delete it from there and everything should be working again.

**Comment by brian-olson** [comment]
You are correct. Dumped all artifacts with

aff4.FACTORY.Delete("aff4:/artifact_store")

...and re-uploaded all the updated artifact yamls and all is well again.

Thanks!
