### ISSUE TITLE
GRR "local" Import Failure

### ISSUE THREAD

**Issue by brian-olson** [google/grr#245]
This change seems to be causing some issues:

https://github.com/google/grr/blob/master/lib/data_stores/registry_init.py#L39

Reverted to 3accb190113d8dafd35c22560e397a6313c887c5 and all is well. 

Traceback (most recent call last):
  File "/usr/local/bin/grr_server", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_server')()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/distro_entry.py", line 57, in GrrServer
    from grr.tools import grr_server
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/grr_server.py", line 22, in <module>
    from grr.lib import server_plugins
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/server_plugins.py", line 32, in <module>
    from grr.lib.data_stores import registry_init
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_stores/registry_init.py", line 39, in <module>
    from grr.lib.data_stores import local
ImportError: cannot import name local

**Comment by grrrrrrrrr** [comment]
Ha, sorry, I forgot to add a directory in the last commit. Please try again with the one I just submitted.

**Comment by brian-olson** [comment]
It's happy now. Thanks Andy!
