### ISSUE TITLE
Permissions && Import FakeDataStore Errors w/Vagrant

### ISSUE THREAD

**Issue by brian-olson** [google/grr#249]
I'm attempting to build clients with some customization outside of what can be done with templates. When running "make templates" from /grr/vagrant I get this error on each Linux client (with respective name changes):

Bringing machine 'ubuntu_lucid64' up with 'virtualbox' provider...
==> ubuntu_lucid64: Checking if box 'mrgcastle/ubuntu-lucid64' is up to date...
==> ubuntu_lucid64: VirtualBox VM is already running.
Traceback (most recent call last):
  File "grr/client/client_build.py", line 16, in <module>
    from grr.client import client_plugins
  File "/grr/client/client_plugins.py", line 24, in <module>
    from grr.client import client_actions
  File "/grr/client/client_actions/__init__.py", line 17, in <module>
    from grr.client.client_actions import grr_rekall
  File "/grr/client/client_actions/grr_rekall.py", line 22, in <module>
    from rekall import plugins
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/rekall/plugins/addrspaces/__init__.py", line 10, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/rekall/plugins/tools/__init__.py", line 27, in <module>
    from rekall.plugins.tools import aff4acquire
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/rekall/plugins/tools/aff4acquire.py", line 39, in <module>
    from pyaff4 import data_store
  File "build/bdist.linux-x86_64/egg/pyaff4/data_store.py", line 16, in <module>
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rdflib-4.2.1-py2.7.egg/rdflib/__init__.py", line 147, in <module>
    from rdflib.graph import Dataset, Graph, ConjunctiveGraph
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rdflib-4.2.1-py2.7.egg/rdflib/graph.py", line 254, in <module>
    from rdflib import plugin, exceptions, query
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rdflib-4.2.1-py2.7.egg/rdflib/plugin.py", line 114, in <module>
    for ep in iter_entry_points(entry_point):
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 722, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2690, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2433, in parse_map
    for group, lines in data:
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3035, in split_sections
    for line in yield_lines(s):
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2288, in yield_lines
    for ss in strs:
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2616, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1625, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1617, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1728, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/EGG-INFO/entry_points.txt'
Connection to 127.0.0.1 closed.
=== Command terminated with exit status 1 (Tue Aug 25 12:43:01 2015) ===

At this point I "vagrant ssh" to the host and attempt to replicate what I believe the GRR script is doing to troubleshoot the problem. I "chmod 777" the file to move on. 

Next I run the command "cd / && source ~/PYTHON_ENV/bin/activate && PYTHONPATH=. python grr/client/client_build.py --config=grr/config/grr-server.yaml build" from the host and get a completely different error:

(PYTHON_ENV)vagrant@vagrant-ubuntu-lucid-64:/$ cd / && source ~/PYTHON_ENV/bin/activate && PYTHONPATH=. python grr/client/client_build.py --config=grr/config/grr-server.yaml build
ERROR:2015-08-25 09:51:32,910 log:151] Unable to create logger file
Traceback (most recent call last):
  File "/grr/lib/log.py", line 142, in GetLogHandlers
    handler = logging.FileHandler(path, mode="ab")
  File "/usr/local/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: u'/var/log/grr/GRRlog.txt'
Traceback (most recent call last):
  File "grr/client/client_build.py", line 430, in <module>
    flags.StartMain(main)
  File "/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "grr/client/client_build.py", line 394, in main
    startup.ClientInit()
  File "/grr/lib/startup.py", line 75, in ClientInit
    registry.Init()
  File "/grr/lib/registry.py", line 220, in Init
    InitHook().Init(skip_set)
  File "/grr/lib/registry.py", line 185, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/grr/lib/registry.py", line 175, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/grr/lib/registry.py", line 163, in _RunSingleHook
    cls_instance.Run()
  File "/grr/lib/data_store.py", line 762, in Run
    config_lib.CONFIG["Datastore.implementation"])
RuntimeError: No Storage System FakeDataStore found.
(PYTHON_ENV)vagrant@vagrant-ubuntu-lucid-64:/$ 

I've tried to find where this problem is to comment out the import etc etc but have had zero luck. Can someone please take a look? Thanks!

**Comment by grrrrrrrrr** [comment]
Hey Brian,

I also encountered this bug :/ What happens is that the client accidentally imports server files that it shouldn't and now tries to set up the data store (clients don't have a data store obviously) and fails.

I have a fix pending, I'll try to get it out asap...

Cheers,
-Andy

**Comment by grrrrrrrrr** [comment]
Hey again,

I just pushed an update, can you check if this resolves the problem for you? Thanks!

Cheers,
-Andy

**Comment by brian-olson** [comment]
Hey Andy, 

Thanks for the quick fix. Looks like it got me past that error and on to the next. 

==> ubuntu_lucid64: Checking if box 'mrgcastle/ubuntu-lucid64' is up to date...
==> ubuntu_lucid64: VirtualBox VM is already running.
Traceback (most recent call last):
  File "grr/client/client_build.py", line 430, in <module>
    flags.StartMain(main)
  File "/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "grr/client/client_build.py", line 394, in main
    startup.ClientInit()
  File "/grr/lib/startup.py", line 71, in ClientInit
    ConfigInit()
  File "/grr/lib/startup.py", line 38, in ConfigInit
    config_lib.ParseConfigCommandLine()
  File "/grr/lib/config_lib.py", line 1415, in ParseConfigCommandLine
    CONFIG.Initialize(filename=flags.FLAGS.config, must_exist=True)
  File "/grr/lib/config_lib.py", line 992, in Initialize
    self.parser = self.LoadSecondaryConfig(filename)
  File "/grr/lib/config_lib.py", line 947, in LoadSecondaryConfig
    self.MergeData(parser.RawData())
  File "/grr/lib/config_lib.py", line 884, in MergeData
    raise InvalidContextError("Invalid context specified: %s" % k)
grr.lib.config_lib.InvalidContextError: Invalid context specified: CommandLine Context
Connection to 127.0.0.1 closed.

**Comment by grrrrrrrrr** [comment]
Hey,

This is kind of expected. We had some issues with context misspellings so I made this a hard error now. This is one of the bugs I found, the context was called both CommandLine and Commandline in different places so the settings were actually never loaded. In the last PR, I changed this in the grr-server.yaml to be Commandline. Can you update your grr-server.yaml too (or just change that one line, see https://github.com/google/grr/commit/56ee26d41afc5809e52d432096de8dbf09564851 )? That should make the error go away. I'd also advise to always use the latest grr-server.yaml and store your local changes in the server.local.yaml.

Cheers,
-Andy

**Comment by brian-olson** [comment]
Hmmm. Maybe I'm not following the process. I just wiped my whole grr directory and did a fresh clone. For some reason my box won't download openssl via https, so I swap out "https" for "http" in the "install_linux.sh" script. Then "make" completes successfully. Next I'm running "make templates". This is where things are breaking. After the commit yesterday and the fresh clone of the repo I'm getting:

==> centos_5.11_32: Checking if box 'mrgcastle/centos_5.11_32' is up to date...
==> centos_5.11_32: VirtualBox VM is already running.
Traceback (most recent call last):
  File "grr/client/client_build.py", line 16, in <module>
    from grr.client import client_plugins
  File "/grr/client/client_plugins.py", line 22, in <module>
    from grr.client import linux
  File "/grr/client/linux/__init__.py", line 7, in <module>
    from grr.client.linux import installers
  File "/grr/client/linux/installers.py", line 10, in <module>
    from grr.client import installer
  File "/grr/client/installer.py", line 15, in <module>
    from grr.client import comms
  File "/grr/client/comms.py", line 32, in <module>
    from grr.client import actions
  File "/grr/client/actions.py", line 16, in <module>
    from grr.client import client_utils
  File "/grr/client/client_utils.py", line 40, in <module>
    from grr.client import client_utils_linux
  File "/grr/client/client_utils_linux.py", line 18, in <module>
    from grr.lib import config_lib
  File "/grr/lib/config_lib.py", line 26, in <module>
    from grr.lib import type_info
  File "/grr/lib/type_info.py", line 13, in <module>
    from grr.lib import rdfvalue
  File "/grr/lib/rdfvalue.py", line 29, in <module>
    from grr.proto import jobs_pb2
ImportError: cannot import name jobs_pb2
Connection to 127.0.0.1 closed.

Just for troubleshooting here I did not change anything in grr-server.yaml nor did I copy my server.local.yaml file into the config dir.

**Comment by scudette** [comment]
You need to have the protobuf compiler and type make in the  proto
directory to build your pb2 files.
Am 26.08.2015 6:47 nachm. schrieb "Brian Olson" <notifications@github.com>:

**Comment by destijl** [comment]
I'm most of the way through fixing these issues, just recording some more info here for posterity. These are the two files that get installed with rekall that are 640 and break the virtualenv for anyone except root:

```
$ ls -lh /home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_gui-1.4.0.post0.dev1-py2.7.egg/EGG-INFO/entry_points.txt
-rw-r----- 1 root root 99 Sep  4 15:15 /home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_gui-1.4.0.post0.dev1-py2.7.egg/EGG-INFO/entry_points.txt
$ ls -lh /home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/EGG-INFO/entry_points.txt
-rw-r----- 1 root root 137 Sep  4 15:15 /home/vagrant/PYTHON_ENV/lib/python2.7/site-packages/rekall_core-1.4.0.post0.dev1-py2.7.egg/EGG-INFO/entry_points.txt
```

Rekall doesn't seem to be doing anything strange with this file:

**Comment by destijl** [comment]
Installing from pip worked, so switched to that instead. Fixed in commit https://github.com/google/grr/commit/4b7f9b06d1dfebd3dc86a6fa2eb7592f233b5330
