### ISSUE TITLE
AttributeError: No such vtype: _MMPTE

### ISSUE THREAD

**Issue by AndrewVi** [google/grr#255]
Hi Everyone,

When I try to AnalyzeClientMemory on Windows7x64 (pslist rekall plugin for instance) the system returned the following error:	"ERROR:rekall.11:No such vtype: _MMPTE". I am using the latest version of GRR Server and Windows agent.

The content of grr-worker.log file on GRR Server.
//--------------------------------------
ERROR:2015-09-17 17:56:50,708 flow_runner:949] Error in flow aff4:/C.55dd43c1d0f892aa/flows/F:AEF11A8D (aff4:/C.55dd43c1d0f892aa). Trace: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/lib/flow_runner.py", line 587, in RunStateMethod
    responses=responses)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flow.py", line 349, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/lib/python2.7/dist-packages/grr/lib/flows/general/memory.py", line 798, in End
    raise flow.FlowError("Error running plugins: %s" % all_errors)
FlowError: Error running plugins: Traceback (most recent call last):
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.client_actions.grr_rekall", line 280, in Iterate
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\rekall.session", line 683, in RunPlugin
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.client_actions.grr_rekall", line 218, in _HandleRunPluginException
AttributeError: No such vtype: _MMPTE
//------------------------

Thank you in advance.

**Comment by parkisan** [comment]
It's most likely this recent post holds answer: https://groups.google.com/forum/#!topic/grr-users/V2Dtq5rD6uY

**Comment by destijl** [comment]
I think this was bad updates by Microsoft to the symbol server. It should be working now, reopen if you're having problems still.
