### ISSUE TITLE
Document supported LC_ALL settings  

### ISSUE THREAD

**Issue by pettai** [google/grr#266]
Hi,

I followed the instruction of https://github.com/google/grr-doc/blob/master/quickstart.adoc#install-the-server and installed GRR on a (vanilla) Ubuntu 14.04. 
The end of the installation bails out with:

[...]
Next step if new install:
   Run:   sudo grr_config_updater initialize
[...]

-=Alert Email Address=-
Address where monitoring events get sent, e.g. crashed clients, broken server
etc.

Alert Email Address [grr-monitoring@localhost]:

-=Emergency Email Address=-
Address where high priority events such as an emergency ACL bypass are sent.

Emergency Access Email Address [grr-emergency@localhost]:
Configuration parameters set. You can edit these in /etc/grr/server.local.yaml
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 787, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 709, in Initialize
    AddUsers(token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 640, in AddUsers
    startup.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/startup.py", line 107, in Init
    registry.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 220, in Init
    InitHook().Init(skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 185, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 175, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 168, in _RunSingleHook
    cls_instance.RunOnce()
  File "/usr/lib/python2.7/dist-packages/grr/gui/django_lib.py", line 67, in RunOnce
    from grr.gui import gui_plugins
  File "/usr/lib/python2.7/dist-packages/grr/gui/gui_plugins.py", line 14, in <module>
    from grr.gui import plugins
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/__init__.py", line 9, in <module>
    from grr.gui.plugins import container_viewer
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/container_viewer.py", line 21, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
#########################################################################################
FAILURE RUNNING: grr_config_updater initialize
#########################################################################################

Perhaps the documentation could be updated with requirement to set LC_ALL to something appropriate, like described in this blog post:
https://secdiary.com/a-check-in-on-the-progress-of-google-rapid-response/

**Comment by grrrrrrrrr** [comment]
Sorry we missed this issue somehow, fix is coming soon.

**Comment by grrrrrrrrr** [comment]
Fixed in 62e70093be68d086cd843b643ae0992775de5160
