### ISSUE TITLE
Screenshot failure

### ISSUE THREAD

**Issue by 0xdabbad00** [google/grr#268]
I tried to take a screenshot on OSX, but received the following error on the server:

```
ERROR:2015-10-08 07:25:59,437 flow_runner:949] Error in flow aff4:/hunts/H:B32E0DC6/C.418c92f408908112/H:7F14B0EF (aff4:/C.418c92f408908112). Trace: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 587, in RunStateMethod
    responses=responses)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flows/general/screenshot.py", line 61, in ProcessFile
    ss_fd = aff4.FACTORY.Open(ss_urn, aff4_type="HashImage", token=self.token)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4.py", line 714, in Open
    urn, result.__class__.__name__, aff4_type))
InstantiationError: Object aff4:/C.418c92f408908112/fs/os/tmp/ss.dat is of type VFSBlobImage, but required_type is HashImage
```

I see the screenshot flow expecting a `HashImage` [here](https://github.com/google/grr/blob/master/lib/flows/general/screenshot.py#L61)
but I'm having trouble debugging to figure out where files are packaged up.

My server is running from the latest docker image.

**Comment by 0xdabbad00** [comment]
The screenshot did take successfully and was retrieved successfully (I could see `/tmp/ss.data` in the file browser, download it, change the name to ss.jpeg and open it).

**Comment by destijl** [comment]
Screenshot is a flow that got written but basically never used and should probably just get removed (or at least hidden under advanced). It's completely useless at scale, and essentially useless for individual machine investigations.
