### ISSUE TITLE
GRR install issues - Docker

### ISSUE THREAD

**Issue by kartikeyap** [google/grr#274]
While trying to run GRR via docker, encountered the following issue. This issue was observed on OSX 10.10.5 as well as Ubuntu 12.04 both.

**Command run was:**
```
docker run \
-e EXTERNAL_HOSTNAME="localhost" \
-e ADMIN_PASSWORD="demo" \
--ulimit nofile=1048576:1048576 \
-p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 \
grrdocker/grr grr
```

**Error received was:**
```
numpy.dtype has the wrong size, try recompiling
Traceback (most recent call last):
  File "/usr/local/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/distro_entry.py", line 51, in ConfigUpdater
    from grr.tools import config_updater
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/config_updater.py", line 19, in <module>
    from grr.lib import server_plugins
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/server_plugins.py", line 29, in <module>
    from grr.lib.aff4_objects import registry_init
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4_objects/registry_init.py", line 18, in <module>
    from grr.lib.aff4_objects import stats_store
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4_objects/stats_store.py", line 43, in <module>
    import pandas
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 6, in <module>
    from . import hashtable, tslib, lib
  File "numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:21547)
ValueError: numpy.dtype has the wrong size, try recompiling
```
Same issue was encountered while trying to install using install_script_ubuntu.sh and was resolved via upgrading numpy.

**Comment by destijl** [comment]
I'm working on this, should have it fixed shortly. Upgrading numpy yourself will fix it.

```
pip install --upgrade numpy
```

**Comment by kartikeyap** [comment]
thank you @destijl

**Comment by destijl** [comment]
Looks like the numpy upgrade forces a matplotlib upgrade too, so do that one as well. Testing now to see if that's enough to have everything build.

**Comment by destijl** [comment]
This is fixed now, the latest build on dockerhub works.
