### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by cjdupreez** [google/grr#279]
I've gotten GRR installed and can access it via the web browser, but when I click on the "Cron Job Viewer" nothing is displayed and in an error message I'm presented with the following traceback:

Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/views.py", line 156, in RenderGenericRenderer
    result = method(request, result) or result
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/cron_view.py", line 33, in Layout
    response = super(ManageCron, self).Layout(request, response)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 988, in Layout
    state=self.state.copy()).RawHTML(request)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/cron_view.py", line 161, in Layout
    response = super(CronTable, self).Layout(request, response)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 656, in Layout
    self.table_contents = delegate_renderer.RenderAjax(request, tmp).content
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/renderers.py", line 691, in RenderAjax
    limit_row + start_row, request)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/gui/plugins/cron_view.py", line 188, in BuildTable
    cron_jobs_urns = list(cronjobs.CRON_MANAGER.ListJobs(token=request.token))
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4_objects/cronjobs.py", line 105, in ListJobs
    return aff4.FACTORY.Open(self.CRON_JOBS_PATH, token=token).ListChildren()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4.py", line 695, in Open
    token=token))
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/aff4.py", line 322, in GetAttributes
    token=token, limit=None):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_store.py", line 362, in MultiResolvePrefix
    token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_stores/sqlite_data_store.py", line 596, in MultiResolveRegex
    timestamp=timestamp, limit=remaining_limit)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_stores/sqlite_data_store.py", line 637, in ResolveRegex
    with self.cache.Get(subject) as sqlite_connection:
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/utils.py", line 51, in NewFunction
    return f(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_stores/sqlite_data_store.py", line 173, in Get
    connection = SqliteConnection(path)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/data_stores/sqlite_data_store.py", line 196, in __init__
    self.cursor.execute("PRAGMA synchronous = OFF")
DatabaseError: database disk image is malformed

What can I do to fix my database? I'm running Ubuntu 14.04 Python 2.7 with GRR 3.0.0.7.

Thanks!

**Comment by destijl** [comment]
See this post on the mailing list for some debugging info:
https://groups.google.com//forum/#!topic/grr-users/IJIaLRcgsXs

The user on the list was just using SQLite without the HTTP distributed datastore (i.e. you didn't go through this setup: http://grr-response.blogspot.com/2014/10/using-distributed-data-store-in-grr.html). Can you confirm your setup is the same? Just the default DB?

See also here:
https://github.com/google/grr/issues/288

**Comment by destijl** [comment]
Anyone experiencing this should sync https://github.com/google/grr/commit/3cbc9ad242be925003261b4575745c23f9ed3597 or later to get more informative error messages so we can try and narrow down why this is happening.

**Comment by destijl** [comment]
Also, others have reported that running in the old single server mode (where worker ui etc. are just run as threads) caused problems with sqlite db corruption. This mode of operation was removed in https://github.com/google/grr/commit/54e18ca5ba20fc5bb8dcd827158c3239eec8898c

Anyone experiencing db corruption problems should upgrade to the latest server and run each component in its own process via a separate init script (as is the default now).

I managed to trigger db corruption myself by completely filling the disk. So make sure you have some monitoring for disk free space. You should also be backing up the sqlite files if you care about keeping your history.

I'm going to close this for now, please re-open if it continues to be a problem.
