### ISSUE TITLE
Windows client installer fails with ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by destijl** [google/grr#284]
We have two reports. From the mailing list and another privately. I'm looking into it now.

The simple workaround is to use the 3.0.0.7 client for windows, which will still work with the current server (you just need to change the client version in the yaml config when you repack). The 3.0.7.1 linux and OS X clients seem to be unaffected.

From the mailing list:

But, I got the followings when i executed windows client after downloaded from server:

Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "c:\python_64\lib\site-packages\PyInstaller-2.1dev_edb5d43-py2.7.egg\PyIn
staller\loader\pyi_importers.py", line 270, in load_module
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.client_plugins",
 line 16, in <module>
  File "c:\python_64\lib\site-packages\PyInstaller-2.1dev_edb5d43-py2.7.egg\PyIn
staller\loader\pyi_importers.py", line 270, in load_module
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.windows", line 7
, in <module>
  File "c:\python_64\lib\site-packages\PyInstaller-2.1dev_edb5d43-py2.7.egg\PyIn
staller\loader\pyi_importers.py", line 270, in load_module
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.windows.installe
rs", line 29, in <module>
  File "c:\python_64\lib\site-packages\PyInstaller-2.1dev_edb5d43-py2.7.egg\PyIn
staller\loader\pyi_importers.py", line 270, in load_module
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.installer", line
 15, in <module>
  File "c:\python_64\lib\site-packages\PyInstaller-2.1dev_edb5d43-py2.7.egg\PyIn
staller\loader\pyi_importers.py", line 270, in load_module
  File "C:\grr-build-root\workpath\grr\out00-PYZ.pyz\grr.client.comms", line 28,
 in <module>
ImportError: No module named google.protobuf

I checked the existence of modules in C:\PYTHON_64\Lib\site-packages. It was over there.

**Comment by destijl** [comment]
The windows client build script is missing a step, you need to create a missing `__init__.py` as we do in the other scripts. From https://github.com/google/grr/blob/master/vagrant/install_linux.sh#L163

```
  # That isn't even enough, pyinstaller still fails to include it because there
  # is no __init__.py as noted here:
  # http://stackoverflow.com/questions/13862562/google-protocol-buffers-not-found-when-trying-to-freeze-python-app
  touch PYTHON_ENV/lib/python2.7/site-packages/google/__init__.py
```

I'll add this in and rebuild the templates.

**Comment by destijl** [comment]
This is now done and new windows templates are available in the drive folder. Make sure you copy them into `/usr/share/grr/executables/windows/templates/` and then repack with your config. I'll have the windows build script updated shortly too.
