### ISSUE TITLE
Interrogate fails on Windows client machine

### ISSUE THREAD

**Issue by jgajek** [google/grr#285]
The Interrogate flow fails for a Windows 7 target machine with the following error:

Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 587, in RunStateMethod responses=responses) File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flows/general/discovery.py", line 168, in ProcessKnowledgeBase raise flow.FlowError("Error collecting artifacts: %s" % responses.status) FlowError: Error collecting artifacts: message GrrStatus { child_session_id : SessionID: aff4:/C.547a62ec0661522b/flows/F:200F53C7/F:B0E1C6B5 cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'Traceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 587, in RunStateMethod\n responses=responses)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact.py", line 236, in ProcessBase\n responses)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact.py", line 279, in SetKBValue\n artifact_obj = artifact_registry.REGISTRY.GetArtifact(artifact_name)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 282, in GetArtifact\n self._CheckDirty()\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 215, in _CheckDirty\n self._ReloadArtifacts()\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 194, in _ReloadArtifacts\n self._LoadArtifactsFromFiles(files_to_load)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 139, in _LoadArtifactsFromFiles\n artifact_value.Validate()\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 716, in Validate\n self.ValidateSyntax()\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact_registry.py", line 681, in ValidateSyntax\n "ARTIFACT_LABELS." % (cls_name, label))\nArtifactDefinitionError: Artifact OSXiCloudPreferences has an invalid label Cloud. Please use one from ARTIFACT_LABELS.\n' network_bytes_sent : 342 status : GENERIC_ERROR }

**Comment by destijl** [comment]
Fixed in https://github.com/google/grr/commit/e0f7ad7144ff5cc09d891cf177710b33505bdf40
