### ISSUE TITLE
Make SQLite database error messages useful

### ISSUE THREAD

**Issue by destijl** [google/grr#288]
Below is a backtrace from the mailing list. The error should tell you what query on what database raised.

```
Traceback (most recent call last):
  File "/usr/bin/grr_worker", line 9, in <module>
    load_entry_point('grr==0.3.0-6', 'console_scripts', 'grr_worker')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 78, in Worker
    flags.StartMain(worker.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/worker/worker.py", line 30, in main
    worker_obj.Run()
  File "/usr/lib/python2.7/dist-packages/grr/lib/worker.py", line 101, in Run
    processed = self.RunOnce()
  File "/usr/lib/python2.7/dist-packages/grr/lib/worker.py", line 140, in RunOnce
    queue)
  File "/usr/lib/python2.7/dist-packages/grr/lib/queue_manager.py", line 505, in GetNotificationsByPriority
    self._GetUnsortedNotifications(queue_shard).values(), queue)
  File "/usr/lib/python2.7/dist-packages/grr/lib/queue_manager.py", line 571, in _GetUnsortedNotifications
    token=self.token, limit=10000):
  File "/usr/lib/python2.7/dist-packages/grr/lib/data_stores/sqlite_data_store.py", line 649, in ResolveRegex
    end, new_limit)
  File "/usr/lib/python2.7/dist-packages/grr/lib/utils.py", line 82, in NewFunction
    return f(self, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/grr/lib/data_stores/sqlite_data_store.py", line 309, in GetValuesFromRegex
    data = self.cursor.execute(query, args).fetchall()
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by mutedmouse** [comment]
This happened to me during operations involving remote connections to the
aff4 while database was in use with grr_fuse.
A grr_config_updater initialize repaired the problem but all artifacts and
hunts were lost.

**Comment by mutedmouse** [comment]
Is there a better way to fix a malformed disk image?
