### ISSUE TITLE
grr_config_updater need pandas to continue

### ISSUE THREAD

**Issue by shane-Git** [google/grr#294]
After using the script to install grr server deb, while creating the config using grr_config_updater, it need pandas python package to continue.

```
Run grr_config_updater initialize [Y/n/a]? Y
#### Running #### grr_config_updater initialize
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 51, in ConfigUpdater
    from grr.tools import config_updater
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 19, in <module>
    from grr.lib import server_plugins
  File "/usr/lib/python2.7/dist-packages/grr/lib/server_plugins.py", line 30, in <module>
    from grr.lib.aff4_objects import registry_init
  File "/usr/lib/python2.7/dist-packages/grr/lib/aff4_objects/registry_init.py", line 18, in <module>
    from grr.lib.aff4_objects import stats_store
  File "/usr/lib/python2.7/dist-packages/grr/lib/aff4_objects/stats_store.py", line 43, in <module>
    import pandas
ImportError: No module named pandas
```

**Comment by destijl** [comment]
Thanks. @bgalehouse can you put pandas back in requirements.txt and add a note to remove it once we've cut a new server deb?

**Comment by mutedmouse** [comment]
Just ran into this last night as well as ipaddr package. Fixed for now my
manually installing missing pips until config updater worked.
