### ISSUE TITLE
Docker image seems to be broken

### ISSUE THREAD

**Issue by uhhhclem** [google/grr#307]
When using the latest image (verified via docker pull), running grrdocker/grr fails with:

Traceback (most recent call last):
  File "/usr/local/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/distro_entry.py", line 51, in ConfigUpdater
    from grr.tools import config_updater
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/config_updater.py", line 19, in <module>
    from grr.lib import server_plugins
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/server_plugins.py", line 27, in <module>
    from grr.lib import output_plugins
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/output_plugins/__init__.py", line 9, in <module>
    from grr.lib.output_plugins import bigquery_plugin
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/output_plugins/bigquery_plugin.py", line 12, in <module>
    from grr.lib import bigquery
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/bigquery.py", line 9, in <module>
    from apiclient.discovery import build
ImportError: No module named apiclient.discovery

**Comment by destijl** [comment]
Thanks, this is a consequence of the server deb needing an older version of requirements.txt and docker needing the latest. Fix is simple, I'll have it out soon.

**Comment by destijl** [comment]
Fixed in https://github.com/google/grr/commit/95980f5cc3232fff4b26c6698ed1ea2285654866
