### ISSUE TITLE
Interrogate: Job Error (StatFile): File not found: message PathSpec AllUsersProfile

### ISSUE THREAD

**Issue by destijl** [google/grr#31]
_From [tyler.keith](https://code.google.com/u/107420357665242655156/) on May 22, 2014 12:31:45_

What steps will reproduce the problem? 1. Install latest version of GRR beta
2. Build clients
3. Install on Windows 7 x64, Mac OS 10.9 What is the expected output? What do you see instead? On all four test machines the Interrogate job would not complete. This should automatically be done once a client connects. What version of the product are you using? On what operating system? 2.10 Beta 
Three Windows 7 x64 clients
One Mac OS 10.9 Please provide any additional information below. === Windows 7 x64 Details ===

All Windows clients have the following error:

INFO:2014-05-22 12:53:50,388 logging:1611] Job Error (ActionPlugin): KeyError(u'Action GetConfig not available on this platform.',): u'Action GetConfig not available on this platform.'
DEBUG:2014-05-22 12:53:50,388 logging:1619] Traceback (most recent call last):
  File "C:\grr_build\build\grr\out00-PYZ.pyz\grr.client.actions", line 133, in Execute
  File "C:\grr_build\build\grr\out00-PYZ.pyz\grr.client.actions", line 182, in Run
KeyError: u'Action GetConfig not available on this platform.'

INFO:2014-05-22 12:53:53,539 logging:1611] Job Error (StatFile): File not found: message PathSpec {
 path : u'AllUsersProfile'
 pathtype : TSK
}

Following Interrogate Flows do not complete, all have the next state as 'StartCollection'
Artifact list AllUsersAppDataEnvironmentVariable
Artifact list CurrentControlSet
Artifact list ProgramFiles
Artifact list ProgramFilesx86
Artifact list WindowsRegistryProfiles

=== Mac Client Details ===
Flow stops at: Interrogate > KnowledgeBaseInitializationFlow > ArtifactCollectorFlow >Artifact list	
OSXUsers

Additional details:
backtrace	 None
client_resources	
create_time	2014-05-21 23:13:51
creator	 GRREnroller
current_state	 Start
kill_timestamp	 None
network_bytes_sent	 0
next_outbound_id	 2
next_processed_request	 1
next_states	 set([])
output	 None
output_urn	 None
outstanding_requests	 1
remaining_cpu_quota	 0
session_id	 aff4:/C.cf57bdebf47be38f/flows/CA:6F0D3DE5/CA:A7F01C02/CA:6C04AE4
state	 RUNNING
user	 GRREnroller
user_notified	 False
failed_count	 0
knowledge_base	
Hostname	 Macintosh.local
Os	 Darwin
Os major version	 10
Os minor version	 9
path_type	 OS

Last Response
flow:request:00000001	
Id	 1
Next state	 StartCollection
Client id	 aff4:/C.cf57bdebf47be38f 
×
Client aff4:/C.cf57bdebf47be38f

 
Session id	 aff4:/C.cf57bdebf47be38f/flows/CA:6F0D3DE5/CA:A7F01C02/CA:6C04AE4	
Session id	 aff4:/C.cf57bdebf47be38f/flows/CA:6F0D3DE5/CA:A7F01C02/CA:6C04AE4
Request id	 1
Response id	 1
Auth state	 AUTHENTICATED
Type	 STATUS
Task id	 13911605062698200808

_Original issue: http://code.google.com/p/grr/issues/detail?id=108_

**Comment by destijl** [comment]
Fairly sure this works now, reopen if it's actually still a problem
