### ISSUE TITLE
KnowledgeBaseUser Error

### ISSUE THREAD

**Issue by brian-olson** [google/grr#321]
I'm getting this response from an interrogate of existing and new clients (client built months ago). Seems to be related to the KnowledgeBaseUser push...thinking it may be this but not sure:

https://github.com/google/grr/commit/c459f1ab76538a9960de66a1bd7e442538a6e536#diff-70922dee154fdca141a72203ab50fc6bL311

Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 594, in RunStateMethod responses=responses) File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flows/general/discovery.py", line 168, in ProcessKnowledgeBase raise flow.FlowError("Error collecting artifacts: %s" % responses.status) FlowError: Error collecting artifacts: message GrrStatus { child_session_id : SessionID: aff4:/hunts/H:xxxxx/C.xxxxxxxxx/H:xxxxxxxx/H:zxxxxxxx cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u'Traceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow_runner.py", line 594, in RunStateMethod\n responses=responses)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flow.py", line 349, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact.py", line 236, in ProcessBase\n responses)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/artifact.py", line 294, in SetKBValue\n self.state.knowledge_base.MergeOrAddUser(response))\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/client.py", line 195, in MergeOrAddUser\n new_attrs = self._CreateNewUser(kb_user)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/client.py", line 177, in _CreateNewUser\n self.users.Append(kb_user)\n File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/rdfvalues/structs.py", line 1111, in Append\n type(rdf_value), e))\nTypeValueError: Assignment value must be User, but <class \'grr.lib.rdfvalues.client.KnowledgeBaseUser\'> can not be coerced. Error: User can not be initialized from <class \'grr.lib.rdfvalues.client.KnowledgeBaseUser\'>\n' network_bytes_sent : 314 status : GENERIC_ERROR }

**Comment by destijl** [comment]
Thanks, I'll take a look.

**Comment by destijl** [comment]
It's definitely that KBUser change, so going back to the earlier version is the workaround.

**Comment by destijl** [comment]
I have a fix out for review internally, it's pretty tiny if you want to apply yourself:

```
grr/lib/rdfvalues/client.py

class User(structs.RDFProtoStruct):
   """Information about the users."""
   protobuf = knowledge_base_pb2.User
 
+  def __init__(self, initializer=None, age=None, **kwargs):
+    if isinstance(initializer, KnowledgeBaseUser):
+      # KnowledgeBaseUser was renamed to User, the protos are identical. This
+      # allows for backwards compatibility with clients returning KBUser
+      # objects.
+      super(User, self).__init__(initializer=initializer.SerializeToString(),
+                                 age=age, **kwargs)
+    else:
+      super(User, self).__init__(initializer=initializer, age=age, **kwargs)
+
 
 class KnowledgeBaseUser(User):
   """Backwards compatibility for old clients.
```
