### ISSUE TITLE
install_script_ubuntu.sh fails if LC_ALL is not set

### ISSUE THREAD

**Issue by schmiedecker** [google/grr#336]
Running install_script_ubuntu.sh on a fresh 15.10 server fails if LC_ALL is empty - setting it using  "export LC_ALL=en_US.UTF-8" fixes this, but there might be a better solution?

`admin@GRRserver:~$` locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME=de_AT.UTF-8
LC_ADDRESS=de_AT.UTF-8
LC_TELEPHONE=de_AT.UTF-8
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION=de_AT.UTF-8
LC_ALL=
`

`-=Emergency Email Address=-
Address where high priority events such as an emergency ACL bypass are sent.

Emergency Access Email Address [grr-emergency@localhost]: 
Configuration parameters set. You can edit these in /etc/grr/server.local.yaml
Traceback (most recent call last):
  File "/usr/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 787, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 709, in Initialize
    AddUsers(token=token)
  File "/usr/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 640, in AddUsers
    startup.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/startup.py", line 107, in Init
    registry.Init()
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 220, in Init
    InitHook().Init(skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 185, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 175, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/usr/lib/python2.7/dist-packages/grr/lib/registry.py", line 168, in _RunSingleHook
    cls_instance.RunOnce()
  File "/usr/lib/python2.7/dist-packages/grr/gui/django_lib.py", line 67, in RunOnce
    from grr.gui import gui_plugins
  File "/usr/lib/python2.7/dist-packages/grr/gui/gui_plugins.py", line 14, in <module>
    from grr.gui import plugins
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/__init__.py", line 9, in <module>
    from grr.gui.plugins import container_viewer
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/container_viewer.py", line 21, in <module>
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
#########################################################################################
FAILURE RUNNING: grr_config_updater initialize
#########################################################################################
`

**Comment by grrrrrrrrr** [comment]
Hey,

Thanks for your report! This has already been fixed, https://github.com/google/grr/blob/master/gui/plugins/container_viewer.py#L22 has the updated code that falls back to en_US.UTF-8 automatically.

We hope to release a new server package soon (maybe as soon as next week) that will not have this issue anymore.

Cheers,
-Andy
