### ISSUE TITLE
3.1 grr_config_updater fails at Step 5

### ISSUE THREAD

**Issue by jolachea** [google/grr#352]
Using:
`sudo grr_console initialize`

Results in:
```
Step 5: Installing template package and repackaging clients with new configuration.
Download and upgrade client templates? You can skip this if templates are already installed. [Yn]:
Downloading/unpacking grr-response-templates==3.1.*
  Could not find any downloads that satisfy the requirement grr-response-templates==3.1.*
  Some externally hosted files were ignored (use --allow-external grr-response-templates to allow).
Cleaning up...
No distributions at all found for grr-response-templates==3.1.*
Storing debug log for failure in /root/.pip/pip.log
```

Debug Log:
```
/usr/bin/pip run on Fri Apr 15 15:25:08 2016
Downloading/unpacking grr-response-templates==3.1.*
  Getting page https://pypi.python.org/simple/grr-response-templates/
  URLs to search for versions for grr-response-templates==3.1.*:
  * https://pypi.python.org/simple/grr-response-templates/3.1.*
  * https://pypi.python.org/simple/grr-response-templates/
  * https://storage.googleapis.com/releases.grr-response.com/index.html
  Skipping link https://storage.googleapis.com/releases.grr-response.com/index.html (from -f); unknown archive format: .html
  Getting page https://pypi.python.org/simple/grr-response-templates/3.1.*
  Could not fetch URL https://pypi.python.org/simple/grr-response-templates/3.1.*: timed out
  Will skip URL https://pypi.python.org/simple/grr-response-templates/3.1.* when looking for download links for grr-response-templates==3.1.*
  Analyzing links from page https://pypi.python.org/simple/grr-response-templates/
  Getting page https://storage.googleapis.com/releases.grr-response.com/index.html
  Analyzing links from page https://storage.googleapis.com/releases.grr-response.com/index.html
    Skipping https://storage.googleapis.com/releases.grr-response.com/grr-response-templates-3.1.0.tar.gz#md5=71525271a5fdbf0c72580ce56194d8a9 (from https://storage.googleapis.com/releases.grr-response.com/index.html) because it is externally hosted.
    Skipping https://storage.googleapis.com/releases.grr-response.com/grr-response-templates-3.1.0post1.tar.gz#md5=93703b0a2c8fb385706970708af0b24b (from https://storage.googleapis.com/releases.grr-response.com/index.html) because it is externally hosted.
  Could not find any downloads that satisfy the requirement grr-response-templates==3.1.*
  Some externally hosted files were ignored (use --allow-external grr-response-templates to allow).
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for grr-response-templates==3.1.*
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for grr-response-templates==3.1.*
```

But:
`sudo grr_config_updater --allow-external initialize`

and:
`sudo grr_config_updater initialize --allow-external`

both result in:
`grr_config_updater: error: unrecognized arguments: --allow-external`

Any way I can do this template import manually?  Thanks all!

**Comment by scudette** [comment]
The --allow-external flag refers to pip not config_updater (which is trying
to launch pip). This flag should not be needed if you have the latest
version of pip. Can you maybe try to upgrade pip?

pip install --upgrade pip

Thanks
Michael.

**Comment by jolachea** [comment]
```
sudo pip -V
pip 8.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
which pip
/usr/local/bin/pip
```

So, I:
`# cp /usr/local/bin/pip /usr/bin/`

Obviously I didn't have an updated pip in the right place.  FAIL

Working now.
Thanks for your help!
