### ISSUE TITLE
IOError: Unable to find resource grr-response-templates

### ISSUE THREAD

**Issue by jolachea** [google/grr#356]
I'm feeling a bit dense today:

```
Will repack the following clients (debug build):

Traceback (most recent call last):
  File "/usr/local/bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/usr/local/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 816, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 736, in Initialize
    ManageBinaries(config, token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr/tools/config_updater.py", line 691, in ManageBinaries
    token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/maintenance_utils.py", line 260, in RepackAllBinaries
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 1162, in Get
    type_info_obj=type_info_obj, context=calc_context)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 1291, in InterpolateValue
    parameter=type_info_obj.name, context=context).Parse()
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 671, in Parse
    self.Close()
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/lexer.py", line 187, in Close
    while self.NextToken():
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/lexer.py", line 127, in NextToken
    possible_next_state = cb(string=m.group(0), match=m)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 640, in Filter
    arg = filter_object().Filter(arg)
  File "/usr/local/lib/python2.7/dist-packages/grr/lib/config_lib.py", line 220, in Filter
    raise IOError("Unable to find resource %s" % filename)
IOError: Unable to find resource grr-response-templates
```

But I know I installed these:
```
pip install grr-response-templates --pre        Requirement already satisfied (use --upgrade to upgrade): grr-response-templates in /usr/local/lib/python2.7/dist-packages
sudo -H pip install grr-response-templates --pre
Requirement already satisfied (use --upgrade to upgrade): grr-response-templates in /usr/local/lib/python2.7/dist-packages
sudo pip install grr-response-templates --pre
```

So .... what have I done wrong here?

**Comment by destijl** [comment]
My guess is you're not using a virtualenv? That won't work. Can you try following these instructions exactly and see if you still have a problem?

https://github.com/google/grr-doc/blob/master/installfrompip.adoc

**Comment by jolachea** [comment]
Greg,

You are correct.  I was not using the virtualenv.  I was able to succeed at completing the install this morning but I ended up having to purge my existing python installation and start fresh.  Additionally, I had to run,

```
pip install rekall
pip install django
pip install werkzeug
```

for the installation and initialization processes to complete.

Thank you!

As a side note, GRR is amazing.

**Comment by jolachea** [comment]
I almost got it but as you can imagine, the django installation isn't working:

Found existing settings:
  Email Domain: localhost
  Alert Email Address: grr-monitoring@localhost
  Emergency Access Email Address: grr-emergency@localhost

```
Do you want to keep this configuration? [Yn]:
Configuration parameters set. You can edit these in /home/user/GRR_ENV/lib/python2.7/site-packages/grr/config/server.local.yaml
/home/user/GRR_ENV/local/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got grr.gui.views.Homepage). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got grr.gui.views.RenderApi). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got grr.gui.views.RenderGenericRenderer). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got grr.gui.views.RenderBinaryDownload). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.views.static.serve). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])

/home/user/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/urls.py:45: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got grr.gui.views.RenderHelp). Pass the callable instead.
  urlpatterns.extend([urls.url(prefix="", *x) for x in GetURLPatterns()])
```

I'm not sure which django version is supposed to be used.  Do you think I should attempt to create a fresh 3.0.7 installation and then upgrade?

**Comment by grrrrrrrrr** [comment]
Hm, there are a bunch of warnings but no error. Is anything actually broken
for you?

We will need to fix those once we upgrade to Django 10 but atm we use v8
(1.8.3) so there should be no problem.

Cheers,
-Andy

**Comment by jolachea** [comment]
Yeah,  I've only got the GRR emblem visible on the UI.  I'll try and revert to 1.8.3 and re-initialize to see if that will fix the problem.

**Comment by jolachea** [comment]
Reverting to 1.8.3 using:

```
pip remove django
pip install django==1.8.3
```

resolved the issue.

Thanks.

**Comment by grrrrrrrrr** [comment]
Yeah please try if downgrading Django fixes this.

I would really urge you to use a virtualenv instead of polluting your system Python and also to at least use the provided requirements.txt which should give you versions for all dependencies that we know are working.

**Comment by jolachea** [comment]
Thank you.  I am up and running now.  I do have a question, is protobufs still being used for client to frontend communications?

Thanks - I've been running a test instance of 3.0.7 since about December and we are working towards getting funding to do a limited prod release for about 1500 systems.  Eventually we want to move to full prod at around 12k.
