### ISSUE TITLE
test_data missing from 3.1.0rc2, breaks settings gui pane

### ISSUE THREAD

**Issue by destijl** [google/grr#358]
The test data is missing from 3.1.0rc2. This was a deliberate decision to clearly separate production code from test data, but it breaks the settings display.

We think the solution is to create another package for test data and dependencies, and just have an empty dir in the core package.

```
Traceback (most recent call last):
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 415, in HandleRequest
    rendered_data = self.CallApiHandler(handler, args, token=token)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 225, in CallApiHandler
    return handler.Render(args, token=token)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/api_plugins/config.py", line 80, in Render
    parameter_data = RenderConfigOption(parameter)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/gui/api_plugins/config.py", line 25, in RenderConfigOption
    option_value = config_lib.CONFIG.Get(name)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1162, in Get
    type_info_obj=type_info_obj, context=calc_context)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1291, in InterpolateValue
    parameter=type_info_obj.name, context=context).Parse()
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 671, in Parse
    self.Close()
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/lexer.py", line 187, in Close
    while self.NextToken():
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/lexer.py", line 127, in NextToken
    possible_next_state = cb(string=m.group(0), match=m)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 657, in ExpandArg
    final_value = self.config.Get(parameter_name, context=self.context)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1162, in Get
    type_info_obj=type_info_obj, context=calc_context)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1291, in InterpolateValue
    parameter=type_info_obj.name, context=context).Parse()
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 671, in Parse
    self.Close()
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/lexer.py", line 187, in Close
    while self.NextToken():
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/lexer.py", line 127, in NextToken
    possible_next_state = cb(string=m.group(0), match=m)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 640, in Filter
    arg = filter_object().Filter(arg)
  File "/home/dev/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 220, in Filter
    raise IOError("Unable to find resource %s" % filename)
IOError: Unable to find resource test_data
```

**Comment by destijl** [comment]
The workaround is to just create the dir it expects in the virtualenv:

```
touch path/to/your/virtualenv/test_data
```

**Comment by destijl** [comment]
Fixed by creating a new python package for the tests.

https://github.com/google/grr/commit/0b73b94eff4da7bf6ceffac4d4961341d628f52d
