### ISSUE TITLE
Cannot export collection files 

### ISSUE THREAD

**Issue by Leejdie** [google/grr#363]
Hello,

I've been trying to export files from hunts & flows using the grr_export tool like so:

`leejdie@ubuntu:/usr/bin$ sudo ./grr_export collection_files --path=aff4:/hunts/H:334F81CA/Results --output=/tmp`

, but I keep getting following errors:

`Traceback (most recent call last):
  File "./grr_export", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_export')()
  File "/usr/lib/python2.7/dist-packages/grr/lib/distro_entry.py", line 72, in Export
    flags.StartMain(export.main)
  File "/usr/lib/python2.7/dist-packages/grr/lib/flags.py", line 107, in StartMain
    main([sys.argv[0]])
  File "/usr/lib/python2.7/dist-packages/grr/tools/export.py", line 68, in main
    flags.FLAGS.func(flags.FLAGS)
  File "/usr/lib/python2.7/dist-packages/grr/tools/export_plugins/collection_files_plugin.py", line 49, in Run
    max_threads=args.threads)
  File "/usr/lib/python2.7/dist-packages/grr/lib/export_utils.py", line 250, in DownloadCollection
    urn = rdfvalue.RDFURN(grr_message.aff4path)
  File "/usr/lib/python2.7/dist-packages/grr/lib/rdfvalue.py", line 852, in __init__
    raise ValueError("URN cannot be None")
ValueError: URN cannot be None`

I'm not sure if this is a bug or if I am doing something wrong myself?

**Comment by grrrrrrrrr** [comment]
Ay, we missed this one too. We fixed a couple of bugs in the export tool, this might work now but no guarantees. I'm going to close this due to long inactivity. If this is still an issue, please reopen.
