### ISSUE TITLE
component selection should use PEP425

### ISSUE THREAD

**Issue by scudette** [google/grr#372]
Currently the component selection signature uses some aspects which are not portable, specifically platform.glibc_ver(). We should just use the scheme described in

https://www.python.org/dev/peps/pep-0425/

**Comment by destijl** [comment]
ping @scudette any progress here?

**Comment by destijl** [comment]
Hrm looks like initialize is confused and is overwriting binaries:

```
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-chipsec_0.1_Linux_CentOS_glibc_2.0_i386.bin
Opened component grr-chipsec.
Storing component summary at aff4:/config/components/grr-chipsec_0.1
Storing signed component at aff4:/web/static/components/573a3659678b4257/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-rekall_0.3_Windows_7___amd64.bin
Opened component grr-rekall.
Storing component summary at aff4:/config/components/grr-rekall_0.3
Storing signed component at aff4:/web/static/components/573a365911a3ac1c/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-rekall_0.3_Linux_debian_glibc_2.0_i386.bin
Opened component grr-rekall.
Using seed from stored component summary at aff4:/config/components/grr-rekall_0.3
Storing signed component at aff4:/web/static/components/573a365911a3ac1c/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-rekall_0.3_Windows_7___i386.bin
Opened component grr-rekall.
Using seed from stored component summary at aff4:/config/components/grr-rekall_0.3
Storing signed component at aff4:/web/static/components/573a365911a3ac1c/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-chipsec_0.1_Linux_debian_glibc_2.0_i386.bin
Opened component grr-chipsec.
Using seed from stored component summary at aff4:/config/components/grr-chipsec_0.1
Storing signed component at aff4:/web/static/components/573a3659678b4257/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-rekall_0.3_Linux_CentOS_glibc_2.2.5_amd64.bin
Opened component grr-rekall.
Using seed from stored component summary at aff4:/config/components/grr-rekall_0.3
Storing signed component at aff4:/web/static/components/573a365911a3ac1c/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-rekall_0.3_Linux_CentOS_glibc_2.0_i386.bin
Opened component grr-rekall.
Using seed from stored component summary at aff4:/config/components/grr-rekall_0.3
Storing signed component at aff4:/web/static/components/573a365911a3ac1c/cp27-cp27mu-linux_x86_64
Signing and uploading component /usr/local/google/home/gcastle/DEV/grr-response-templates/components/grr-chipsec_0.1_Linux_CentOS_glibc_2.2.5_amd64.bin

```
and I get load fails in the e2e:

```
DEBUG:2016-05-16 14:45:00,174 worker:330] Got lock on aff4:/C.7f7f23766909b277/flows/F:ABB5B0C4
DEBUG:2016-05-16 14:45:00,180 flow_runner:579] aff4:/C.7f7f23766909b277/flows/F:ABB5B0C4 Running ComponentLoaded with 1 responses from aff4:/C.7f7f23766909b277
INFO:2016-05-16 14:45:00,180 flow_runner:1153] aff4:/C.7f7f23766909b277/flows/F:ABB5B0C4: Component Loading failed: CipherError(EVPError('wrong final block length',),): wrong final block length
ERROR:2016-05-16 14:45:00,181 flow_runner:610] Flow aff4:/C.7f7f23766909b277/flows/F:ABB5B0C4 raised.
Traceback (most recent call last):
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow_runner.py", line 594, in RunStateMethod
    responses=responses)
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow.py", line 352, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flows/general/memory.py", line 140, in ComponentLoaded
    raise flow.FlowError("Component load failed.")
FlowError: Component load failed.
ERROR:2016-05-16 14:45:00,185 flow_runner:956] Error in flow aff4:/C.7f7f23766909b277/flows/F:ABB5B0C4 (aff4:/C.7f7f23766909b277). Trace: Traceback (most recent call last):
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow_runner.py", line 594, in RunStateMethod
    responses=responses)
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow.py", line 352, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flows/general/memory.py", line 140, in ComponentLoaded
    raise flow.FlowError("Component load failed.")
FlowError: Component load failed.
```

```
Running TestAnalyzeClientMemoryNonexistantPluginWithExisting on aff4:/C.7f7f23766909b277 (localhost.localdomain: Linux, 7.2, x86_64)
F
======================================================================
FAIL: TestAnalyzeClientMemoryNonexistantPluginWithExisting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/endtoend_tests/base.py", line 122, in runTest
    self.CheckFlow()
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/endtoend_tests/memory.py", line 241, in CheckFlow
    self.CheckForInvalidPlugin(flow_state)
  File "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/endtoend_tests/memory.py", line 198, in CheckForInvalidPlugin
    str(flow_state.context.backtrace).lower())
AssertionError: 'invalid plugin' not found in 'traceback (most recent call last):\n  file "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow_runner.py", line 594, in runstatemethod\n    responses=responses)\n  file "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flow.py", line 352, in decorated\n    res = f(*args[:f.func_code.co_argcount])\n  file "/usr/local/google/home/gcastle/grr_opensrc/grr/grr/lib/flows/general/memory.py", line 140, in componentloaded\n    raise flow.flowerror("component load failed.")\nflowerror: component load failed.\n'

----------------------------------------------------------------------
Ran 1 test in 5.167s
```

**Comment by destijl** [comment]
Problem is .signature() call at initialize time uploads everything to the same aff4 path of the host.
