### ISSUE TITLE
GRR docker's appears 

### ISSUE THREAD

**Issue by lukekwon** [google/grr#385]
Hello all,

I've installed GRR docker on CentOS 7.1
"docker exec logs grr_config_updater initialize" -> It appears the below.

Checking write access on config <YamlParser filename="/etc/grr/grr-server.yaml">

Step 0: Importing Configuration from previous installation.
No old config file found.

Step 1: Key Generation
You already have keys in your config, do you want to overwrite them? [yN]: Traceback (most recent call last):
  File "/usr/local/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr==0.3.0-7', 'console_scripts', 'grr_config_updater')()
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/distro_entry.py", line 53, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/config_updater.py", line 811, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_7-py2.7-linux-x86_64.egg/grr/tools/config_updater.py", line 722, in Initialize
    if (raw_input("You already have keys in your config, do you want to"
EOFError: EOF when reading a line

Thanks.
Justin.

**Comment by destijl** [comment]
Did you follow the instructions? It doesn't look like it from that command:
https://github.com/google/grr-doc/blob/master/docker.adoc

**Comment by destijl** [comment]
Please re-open if you can reproduce following the instructions.
