### ISSUE TITLE
rekall is missing in deb build

### ISSUE THREAD

**Issue by SleuthKid** [google/grr#388]
Following the standard procedure for build the grr-server deb with Docker it seems like rekall is not properly bundled:

```
grr-server (3.1.0-2) wird eingerichtet ...
#################################################################
Running grr_config_updater initialize
To avoid this prompting, set DEBIAN_FRONTEND=noninteractive
#################################################################
Traceback (most recent call last):
  File "/usr/share/grr-server//bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 74, in ConfigUpdater
    from grr.tools import config_updater
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 22, in <module>
    from grr.lib import server_plugins
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 27, in <module>
    from grr.lib import output_plugins
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/output_plugins/__init__.py", line 14, in <module>
    from grr.lib.output_plugins import csv_plugin
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/output_plugins/csv_plugin.py", line 8, in <module>
    from grr.lib import export
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/export.py", line 23, in <module>
    from grr.lib.flows.general import collectors as flow_collectors
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/collectors.py", line 20, in <module>
    from grr.lib.flows.general import memory as _
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 12, in <module>
    from rekall import constants
ImportError: No module named rekall
dpkg: Fehler beim Bearbeiten des Paketes grr-server (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Trigger für libc-bin (2.23-0ubuntu3) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 grr-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by destijl** [comment]
Fixed in the new .deb, available here:
https://storage.googleapis.com/grr_releases/3.1.0.2/grr-server_3.1.0-2_amd64.deb

**Comment by destijl** [comment]
The permanent link will be:
https://storage.googleapis.com/releases.grr-response.com/3.1.0.2/grr-server_3.1.0-2_amd64.deb

I'll be updating the install script to point there shortly.
