### ISSUE TITLE
grr_server --component ui fails

### ISSUE THREAD

**Issue by jessicawilsonsc** [google/grr#397]
Using install from pip tracking head, git pulled for the newest release. 

When I attempt to run grr_server --component ui --verbose it fails with the following error 
```
Traceback (most recent call last):
  File "GRR_NEW/bin/grr_server", line 9, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_server')()
  File "grr/grr/lib/distro_entry.py", line 80, in GrrServer
    from grr.tools import grr_server
  File "grr/grr/tools/grr_server.py", line 11, in <module>
    from grr.lib import server_plugins
  File "grr/grr/lib/server_plugins.py", line 22, in <module>
    from grr.lib import hunts
  File "grr/grr/lib/hunts/__init__.py", line 10, in <module>
    from grr.lib.hunts import process_results
  File "grr/grr/lib/hunts/process_results.py", line 21, in <module>
    class ProcessHuntResultCollectionsCronFlowArgs(rdf_structs.RDFProtoStruct):
  File "grr/grr/lib/hunts/process_results.py", line 22, in ProcessHuntResultCollectionsCronFlowArgs
    protobuf = flows_pb2.ProcessHuntResultCollectionsCronFlowArgs
AttributeError: 'module' object has no attribute 'ProcessHuntResultCollectionsCronFlowArgs'
```

**Comment by scudette** [comment]
It looks like your protobufs are not compiled properly. 
How is it installed?

If you installed an old version with pip install -e grr_path/  then every time you git pull you need to run makefile.py to re-compile protobufs or they will be out of sync.

**Comment by jessicawilsonsc** [comment]
That was exactly it. My apologies. Thank you!
