### ISSUE TITLE
grr agent fails on Fedora 24 - no minor version

### ISSUE THREAD

**Issue by chlunde** [google/grr#402]
FYI, `versions.versions[1]` raises IndexError on Fedora 24.  Probably because there's no minor version.

```
$ cat /etc/redhat-release 
Fedora release 24 (Twenty Four)

Traceback (most recent call last):
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod responses=responses)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount])
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/discovery.py", line 153, in Platform next_state="ProcessKnowledgeBase")
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 790, in CallFlow **kwargs)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 908, in CallFlow **kwargs)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 933, in StartFlow flow_obj.Start()
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount])
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact.py", line 142, in Start self.InitializeKnowledgeBase()
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact.py", line 434, in InitializeKnowledgeBase SetCoreGRRKnowledgeBaseValues(self.state.knowledge_base, self.client)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact.py", line 97, in SetCoreGRRKnowledgeBaseValues kb.os_minor_version = versions.versions[1]
IndexError: list index out of range
```

**Comment by destijl** [comment]
This isn't a platform we care much about at the moment. If it's important to you it would be great if you can send a PR to fix it.

**Comment by grrrrrrrrr** [comment]
I included a bugfix for this issue in https://github.com/google/grr/commit/15d069584fc362a72835cea488b89482c4133a46
