### ISSUE TITLE
import_nsrl_hashes.py - ImportError: No module named grr.lib

### ISSUE THREAD

**Issue by infde6** [google/grr#406]
While attempting to use the NSRL import script, the following error is encountered:
Traceback (most recent call last):
  File "import_nsrl_hashes.py", line 9, in <module>
    from grr.lib import server_plugins
ImportError: No module named grr.lib

uname -ar:
Linux <hostaname> 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed GRR with the install script in the Quickstart guide:
https://github.com/google/grr-doc/blob/master/quickstart.adoc

Search for grr.lib in /usr and /var returns 0 results

**Comment by grrrrrrrrr** [comment]
Hm how are you running this script? It doesn't have an entry point, are you calling it directly?

If you followed the install from pip instructions, this should just work. If I have the virtualenv activated, I can do a

import grr.lib

just fine.

**Comment by lodr74** [comment]
Im having the same issue.  From the grr_console I can import the grr.lib

In [2]: import grr.lib
In [3]: 

Yet calling the file directly as representing in https://github.com/google/grr-doc/blob/master/user_manual.adoc#importing-the-nsrl doesnt work.

root@somehost:/usr/share/grr-server/lib/python2.7/site-packages/grr/tools# python import_nsrl_hashes.py --config /etc/grr/grr-server.yaml --filename /nsrl/NSRLFile.txt
Traceback (most recent call last):
  File "import_nsrl_hashes.py", line 9, in <module>
    from grr.lib import server_plugins
ImportError: No module named grr.lib

 8 # pylint: disable=unused-import,g-bad-import-order
  9 from grr.lib import server_plugins
 10 # pylint: enable=unused-import,g-bad-import-order


Any suggestions?

**Comment by grrrrrrrrr** [comment]
you need to point your PYTHONPATH at /usr/share/grr-server/lib/python2.7/site-packages/ and this should work. It's only a workaround though, we should make the import_nsrl_hashes a proper entry point.

**Comment by lodr74** [comment]
After I add the PYTHONPATH I get the following:

root@ip-172-31-44-207:~# python /usr/share/grr-server/lib/python2.7/site-packages/grr/tools/import_nsrl_hashes.py --config /etc/grr/grr-server.yaml --filename /nsrl/NSRLFile.txt
Traceback (most recent call last):
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/tools/import_nsrl_hashes.py", line 9, in <module>
    from grr.lib import server_plugins
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 16, in <module>
    from grr.client import client_plugins
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/client/client_plugins.py", line 24, in <module>
    from grr.client import client_actions
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/client/client_actions/__init__.py", line 11, in <module>
    from grr.lib import rdfvalue
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/rdfvalue.py", line 30, in <module>
    from grr.proto import jobs_pb2
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/proto/jobs_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


So I uninstall and re-install protobuff.  This resulted in the following error.


root@ip-172-31-44-207:/usr/share/grr-server/lib/python2.7/site-packages/grr/tools# python /usr/share/grr-server/lib/python2.7/site-packages/grr/tools/import_nsrl_hashes.py --config /etc/grr/grr-server.yaml --filename /nsrl/NSRLFile.txt
Traceback (most recent call last):
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/tools/import_nsrl_hashes.py", line 9, in <module>
    from grr.lib import server_plugins
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 16, in <module>
    from grr.client import client_plugins
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/client/client_plugins.py", line 32, in <module>
    from grr import config
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/config/__init__.py", line 21, in <module>
    from grr.config import server
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/config/server.py", line 9, in <module>
    VERSION = grr.version()
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/__init__.py", line 14, in version
    version_ini = config_lib.Resource().Filter("version.ini")
  File "/usr/share/grr-server/lib/python2.7/site-packages/grr/lib/config_lib.py", line 243, in Filter
    filename_spec)
grr.lib.config_lib.FilterError: Unable to find resource version.ini while interpolating:

So I edit the:
/usr/share/grr-server/lib/python2.7/site-packages/grr/__init__.py

and point the file location to:
/usr/share/grr-server/version.ini

Which resulted in:
grr.lib.config_lib.ConfigFormatError: Unable to parse config file /etc/grr/grr-server.yaml

So I copy grr-server.yaml to the right location.
cp /usr/share/grr-server/install_data/etc/grr-server.yaml /etc/grr/

Now I get 
grr.lib.config_lib.FilterError: Unable to find resource install_data/etc while interpolating:  %(install_data/etc|resource) %(Config.directory)/server.local.yaml


I feel like this is a never ending stream of errors, but could be prevent or is a simple fix, but I am not seeing it.  Any advice?

**Comment by destijl** [comment]
All of this is a symptom of GRR not running in a virtualenv properly as it expects to. As andy says, this should be a proper entry point so it can be run from any directory and have all the environment set up as expected. We don't find this NSRL info particularly useful, so the script isn't really maintained. You'd be better off spending your time adding it as an entry point like the others:

https://github.com/google/grr/blob/master/grr/lib/distro_entry.py

than trying to battle through these errors.

**Comment by scudette** [comment]
You should be able to simulate that by using the python inside the
virtualenv instead of the system python. This might work:

/usr/share/grr-server/bin/python
/usr/share/grr-server/lib/python2.7/site-packages/grr/tools/import_nsrl_hashes.py
--config /etc/grr/grr-server.yaml --filename /nsrl/NSRLFile.txt
