### ISSUE TITLE
grr_config_updater initialize fails with new commit

### ISSUE THREAD

**Issue by smozarmi** [google/grr#419]
Apologies if this is not the right place to place this issue, this is my first time commenting on the grr github. This is posted here just in case it is any potential help to solving a bug issue on the nonstandard centos7 + mysql grr platform.

I am running this on CentOS 7 -- my configuration file specifies the SQLAdvancedDataStore (mysql 5.7 is installed). I am using three different servers for http server, worker, and db.
The initialization and component installs worked fine on the previous commmit 2997e69346124028f15fff83d082b3eba4bbef8b "Fixed Bower config to fix UI build"

When I pulled the new code from this commit: Fix multitypecollection bug (618f5f23e8d14d7bd01878a6cc56f0b1ca96336a)., I received this error 

$ grr_config_updater initialize

```
Configuration parameters set. You can edit these in /home/grrworker/Documents/grrProj/install_data/etc/server.local.yaml
Traceback (most recent call last):
  File "/home/grrworker/Documents/GRR_NEW/pyenv/bin/grr_config_updater", line 9, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_config_updater')()
  File "/home/grrworker/Documents/grrProj/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/home/grrworker/Documents/grrProj/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/home/grrworker/Documents/grrProj/grr/tools/config_updater.py", line 751, in main
    Initialize(config_lib.CONFIG, token=token)
  File "/home/grrworker/Documents/grrProj/grr/tools/config_updater.py", line 668, in Initialize
    AddUsers(token=token)
  File "/home/grrworker/Documents/grrProj/grr/tools/config_updater.py", line 576, in AddUsers
    startup.Init()
  File "/home/grrworker/Documents/grrProj/grr/lib/startup.py", line 92, in Init
    registry.Init()
  File "/home/grrworker/Documents/grrProj/grr/lib/registry.py", line 207, in Init
    InitHook().Init(skip_set)
  File "/home/grrworker/Documents/grrProj/grr/lib/registry.py", line 172, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/home/grrworker/Documents/grrProj/grr/lib/registry.py", line 162, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/home/grrworker/Documents/grrProj/grr/lib/registry.py", line 155, in _RunSingleHook
    cls_instance.RunOnce()
  File "/home/grrworker/Documents/grrProj/grr/gui/django_lib.py", line 67, in RunOnce
    from grr.gui import gui_plugins
  File "/home/grrworker/Documents/grrProj/grr/gui/gui_plugins.py", line 12, in <module>
    from grr.gui import api_call_robot_router
  File "/home/grrworker/Documents/grrProj/grr/gui/api_call_robot_router.py", line 6, in <module>
    from grr.gui import api_call_router
  File "/home/grrworker/Documents/grrProj/grr/gui/api_call_router.py", line 12, in <module>
    from grr.gui.api_plugins import cron as api_cron
  File "/home/grrworker/Documents/grrProj/grr/gui/api_plugins/cron.py", line 151, in <module>
    class ApiListCronJobFlowsArgs(rdf_structs.RDFProtoStruct):
  File "/home/grrworker/Documents/grrProj/grr/gui/api_plugins/cron.py", line 152, in ApiListCronJobFlowsArgs
    protobuf = api_pb2.ApiListCronJobFlowsArgs
AttributeError: 'module' object has no attribute 'ApiListCronJobFlowsArgs'




```

**Comment by mkunz7** [comment]
This might be related. The latest quickstart for ubuntu 16.04 failed on grr_config_updater and I had to install python-pandas as suggested by this.

https://github.com/google/grr/issues/294

**Comment by grrrrrrrrr** [comment]
It seems like your protobuf files are out of date. According to https://github.com/google/grr-doc/blob/master/troubleshooting.adoc , you need to rerun python setup.py build. Does that help?

**Comment by smozarmi** [comment]
From initial testing I think the setup.py rerun did the job. Thanks!
