### ISSUE TITLE
Crash when viewing ArtifactCollectorFlow results

### ISSUE THREAD

**Issue by zbuc** [google/grr#424]
Running revision `ad77429`.

I created and ran an `ArtifactCollectorFlow` with a few Darwin-targeting subflows and a CSV `OutputPlugin` on a single client, and when attempting to view the `results` tab of any of the subflows under the top-level `ArtifactCollectorFlow` I receive the following reproducible bug:

**Can't fetch output plugins list: Object aff4:/C.a3066addab02e7aa/flows/C.a3066addab02e7aa is of type AFF4Volume, but required_type is GRRFlow.**

```
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 427, in HandleRequest
    rendered_data = self.CallApiHandler(handler, args, token=token)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 193, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/gui/api_plugins/flow.py", line 175, in Handle
    flow_urn, aff4_type=flow.GRRFlow, mode="r", token=token)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4.py", line 783, in Open
    (urn, result.__class__.__name__, aff4_type.__name__))
InstantiationError: Object aff4:/C.a3066addab02e7aa/flows/C.a3066addab02e7aa is of type AFF4Volume, but required_type is GRRFlow
```

Please let me know if I can provide any other information.

**Comment by destijl** [comment]
@mbushkov I can reproduce in prod just by clicking a subflow in the UI and rendering flow information. So it's not just a "we don't write subflow results" problem.

**Comment by grrrrrrrrr** [comment]
This should be fixed now, @mbushkov can you verify and close this?

**Comment by grrrrrrrrr** [comment]
Fixed.
