### ISSUE TITLE
 ArtifactDefinitionError: Artifact LinuxAtJobs missing from registry

### ISSUE THREAD

**Issue by giray** [google/grr#429]
Running grrdocker/grr:v3.1.0.2-latest, and I get the following error

`Validate raise ArtifactDefinitionError(e) ArtifactDefinitionError: Artifact LinuxAtJobs missing from registry. You may need to sync the artifact repo by running make in the artifact directory.`

detailed trace:
```
Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, 
in RunStateMethod responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, 
in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/discovery.py", line 153, 
in Platform next_state="ProcessKnowledgeBase") File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 790, 
in CallFlow **kwargs) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 908, 
in CallFlow **kwargs) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 933, 
in StartFlow flow_obj.Start() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact.py", line 143, 
in Start first_flows = self.GetFirstFlowsForCollection() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact.py", line 407, 
in GetFirstFlowsForCollection artifact_registry.REGISTRY.GetArtifact(artifact_name) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_registry.py", line 293, 
in GetArtifact self._CheckDirty() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_registry.py", line 222, 
in _CheckDirty self._ReloadArtifacts() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_registry.py", line 201, 
in _ReloadArtifacts self._LoadArtifactsFromFiles(files_to_load) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_registry.py", line 140,
in _LoadArtifactsFromFiles artifact_value.Validate() File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_registry.py", line 762, 
in Validate raise ArtifactDefinitionError(e) ArtifactDefinitionError: Artifact LinuxAtJobs missing from registry. You may need to sync the artifact repo by running make in the artifact directory.
```

**Comment by destijl** [comment]
Thanks for the report. Sorry for the slow response, you caught us at a very busy time, but I hope to get this fixed soon.

**Comment by destijl** [comment]
I looked at this today. Older versions of grrdocker/grr:v3.1.0.2-latest work but pulling a fresh copy does not.

Running head "grrdocker/grr:latest" works fine, so that's the workaround.

For some reason I haven't figured out yet the artifact directory in:
/usr/share/grr-server/lib/python2.7/site-packages/grr/artifacts

is empty, i.e. the makefile doesn't get run.

I'll look at this again on monday, but probably just pointing people at a newer docker build by default is the solution rather than going down the rabbit hole on the older version.

**Comment by destijl** [comment]
This should be fixed now, just need to wait on dockerhub to build it:
https://hub.docker.com/r/grrdocker/grr/builds/

and then docker pull.

Or you could build it yourself by checking out the branch.
