### ISSUE TITLE
Unable to import NSRL Hashes -- aaf4_type=NSRLFileStore must be a type

### ISSUE THREAD

**Issue by zbuc** [google/grr#431]
I'm getting an error while trying to import the NSRL hashes according to the [documentation](https://github.com/google/grr-doc/blob/master/user_manual.adoc#importing-the-nsrl):

```
(GRR_NEW) [grr_user@ip-10-0-1-52 ~]$ python grr/grr/tools/import_nsrl_hashes.py --config GRR_NEW/install_data/etc/server.local.yaml --filename /mnt/extra/NSRLFile.txt
Traceback (most recent call last):
  File "grr/grr/tools/import_nsrl_hashes.py", line 101, in <module>
    flags.StartMain(main)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "grr/grr/tools/import_nsrl_hashes.py", line 94, in main
    token=aff4.FACTORY.root_token) as store:
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4.py", line 1005, in Create
    aff4_type = _ValidateAFF4Type(aff4_type)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4.py", line 268, in _ValidateAFF4Type
    raise TypeError("aff4_type=%s must be a type" % aff4_type)
TypeError: aff4_type=NSRLFileStore must be a type
```

**Comment by grrrrrrrrr** [comment]
Thanks for the report! During a recent refactor we forgot about this script. I have a fix ready, this will be working again after the next code push.

**Comment by zbuc** [comment]
Thanks!

I get further now but the complete import still fails:

```
$ python grr/grr/tools/import_nsrl_hashes.py --config GRR_NEW/install_data/etc/server.local.yaml --filename /mnt/extra/NSRLFile.txt
Failed at 3 with aff4_type=NSRLFile must be a type
Imported 2 hashes

$ head -n5 /mnt/extra/NSRLFile.txt
"SHA-1","MD5","CRC32","FileName","FileSize","ProductCode","OpSystemCode","SpecialCode"
"0000000F8527DCCAB6642252BBCFA1B8072D33EE","68CE322D8A896B6E4E7E3F18339EC85C","E39149E4","Blended_Coolers_Vanilla_NL.png",30439,28948,"358",""
"000000206738748EDD92C4E3D2E823896700F849","392126E756571EBF112CB1C1CDEDF926","EBD105A0","I05002T2.PFB",98865,3095,"WIN",""
"0000002D9D62AEBE1E0E9DB6C4C4C7C16A163D2C","1D6EBB5A789ABD108FF578263E1F40F3","FFFFFFFF","_sfx_0024._p",4109,21000,"358",""
"0000004DA6391F7F5D2F7FCCF36CEBDA60C6EA02","0E53C14A3E48D94FF596A2824307B492","AA6A7B16","00br2026.gif",2226,228,"WIN",""
```

**Comment by zecchino1** [comment]
I get a similar error related to the flags.StartMain(main):

Traceback (most recent call last):
  File "import_nsrl_hashes.py", line 100, in <module>
    flags.StartMain(main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "import_nsrl_hashes.py", line 83, in main
    startup.Init()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/startup.py", line 86, in Init
    ConfigInit()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/startup.py", line 37, in ConfigInit
    config_lib.ParseConfigCommandLine()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1662, in ParseConfigCommandLine
    CONFIG.Initialize(filename=flags.FLAGS.config, must_exist=True)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1178, in Initialize
    raise ConfigFormatError("Unable to parse config file %s" % filename)
grr.lib.config_lib.ConfigFormatError: Unable to parse config file /etc/grr/grr-server.yaml

**Comment by grrrrrrrrr** [comment]
The NSRL filestore has been refactored quite a bit, the original problem is fixed (obsolete) at this point so I'm going to close this bug.

@zecchino1 if you still have those issues, please file a new bug since your error is totally unrelated.
