### ISSUE TITLE
`GET :44449/varz` results in TypeError: keys must be a string

### ISSUE THREAD

**Issue by zbuc** [google/grr#439]
Looks like the JSON encoding is failing because the `results` object isn't structured correctly.

This is running checkout 85d29757e2eba0ee26ab6835617e5d39beb6985f.

When I access the URL http://localhost:44449/varz (which I was considering using for uptime monitoring), I receive a 200 response with an empty body and the following appears in the logs:

```
127.0.0.1 - - [20/Sep/2016 16:50:39] "GET /varz HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 21365)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/server/stats_server.py", line 65, in do_GET
    self.wfile.write(encoder.encode(results))
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
----------------------------------------
```

**Comment by mbushkov** [comment]
Hi Chris,
Thanks for reporting this. Looks like a bug. I'll investigate.

Cheers,
Misha

**Comment by mbushkov** [comment]
Hi Chris,
The issue was fixed in
https://github.com/google/grr/commit/7dd3cdfcb90c7d89bc89a5b1a65139ee8eebd178

Cheers,
Misha

**Comment by zbuc** [comment]
Verified fixed, thank you!
