### ISSUE TITLE
protobuf plugin instance missing ApiOutputPluginDescriptor

### ISSUE THREAD

**Issue by zbuc** [google/grr#440]
After updating to 7dd3cdfcb90c7d89bc89a5b1a65139ee8eebd178 from e3495c614102b122bc41ea03b1f8864565c3faef I am unable to start any instances of `grr_server`.

Looks like a nonexistent attribute `ApiOutputPluginDescriptor` is trying to be accessed on the `api_pb2` object.

```
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/bin/grr_server", line 11, in <module>
    load_entry_point('grr-response-server', 'console_scripts', 'grr_server')()
  File "/home/grr_user/grr/grr/lib/distro_entry.py", line 82, in GrrServer
    flags.StartMain(grr_server.main)
  File "/home/grr_user/grr/grr/lib/flags.py", line 112, in StartMain
    main([sys.argv[0]])
  File "/home/grr_user/grr/grr/tools/grr_server.py", line 40, in main
    admin_ui.main([argv])
  File "/home/grr_user/grr/grr/gui/admin_ui.py", line 33, in main
    startup.Init()
  File "/home/grr_user/grr/grr/lib/startup.py", line 92, in Init
    registry.Init()
  File "/home/grr_user/grr/grr/lib/registry.py", line 207, in Init
    InitHook().Init(skip_set)
  File "/home/grr_user/grr/grr/lib/registry.py", line 172, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/home/grr_user/grr/grr/lib/registry.py", line 162, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/home/grr_user/grr/grr/lib/registry.py", line 155, in _RunSingleHook
    cls_instance.RunOnce()
  File "/home/grr_user/grr/grr/gui/django_lib.py", line 67, in RunOnce
    from grr.gui import gui_plugins
  File "/home/grr_user/grr/grr/gui/gui_plugins.py", line 12, in <module>
    from grr.gui import api_call_robot_router
  File "/home/grr_user/grr/grr/gui/api_call_robot_router.py", line 7, in <module>
    from grr.gui import api_call_router
  File "/home/grr_user/grr/grr/gui/api_call_router.py", line 9, in <module>
    from grr.gui import api_value_renderers
  File "/home/grr_user/grr/grr/gui/api_value_renderers.py", line 14, in <module>
    from grr.gui.api_plugins import output_plugin as api_output_plugin
  File "/home/grr_user/grr/grr/gui/api_plugins/output_plugin.py", line 21, in <module>
    class ApiOutputPluginDescriptor(rdf_structs.RDFProtoStruct):
  File "/home/grr_user/grr/grr/gui/api_plugins/output_plugin.py", line 23, in ApiOutputPluginDescriptor
    protobuf = api_pb2.ApiOutputPluginDescriptor
AttributeError: 'module' object has no attribute 'ApiOutputPluginDescriptor'
```

**Comment by scudette** [comment]
When you git pull you need to do a pip install -e again because it has to
rebuild protobufs.

**Comment by zbuc** [comment]
That got it, thank you!
