### ISSUE TITLE
Worker tries writing empty state for newly launched flows

### ISSUE THREAD

**Issue by zbuc** [google/grr#441]
Currently having an issue on release 7dd3cdfcb90c7d89bc89a5b1a65139ee8eebd178

When I launch a new flow, it never changes its state from `RUNNING` in the UI, and I see the following in the worker log:

```
ERROR:2016-09-27 19:59:17,864 worker:385] Error processing session aff4:/C.c6259a0da13eab27/flows/F:4974F718: Trying to write an empty state for flow aff4:/C.c6259a0da13eab27/flows/F:4974F718.
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/worker.py", line 357, in _ProcessMessages
    self._ProcessRegularFlowMessages(flow_obj, notification)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4.py", line 2252, in __exit__
    self.Close()
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow.py", line 579, in Close
    self.WriteState()
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow.py", line 555, in WriteState
    raise IOError("Trying to write an empty state for flow %s." % self.urn)
IOError: Trying to write an empty state for flow aff4:/C.c6259a0da13eab27/flows/F:4974F718.
```

**Comment by zbuc** [comment]
I'm also seeing quite a few of these in the `grr-worker.log` that may be related:

```
ERROR:2016-09-27 20:18:29,877 cronjobs:152] Error processing cron job aff4:/cron/ProcessHuntResultCollectionsCronFlow: 'context'
Traceback (most recent call last):
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4_objects/cronjobs.py", line 149, in RunOnce
    cron_job.Run(force=force)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4_objects/cronjobs.py", line 527, in Run
    self.KillOldFlows()
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4_objects/cronjobs.py", line 496, in KillOldFlows
    if self.IsRunning():
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/aff4_objects/cronjobs.py", line 444, in IsRunning
    runner = current_flow.GetRunner()
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow.py", line 602, in GetRunner
    self.runner = self.runner_cls(self)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 173, in __init__
    self.context = self.flow_obj.state.context
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/rdfvalues/flows.py", line 251, in __getattr__
    return getattr(self.data, item)
  File "/home/grr_user/GRR_NEW/local/lib/python2.7/site-packages/grr/lib/utils.py", line 1489, in __getattr__
    raise AttributeError(e)
```

**Comment by zbuc** [comment]
This was an issue with running a different checkout (selected an old AMI) on my worker servers versus my frontend servers.
