### ISSUE TITLE
Unable to parse config file /etc/grr/grr-server.yaml when trying to import NSRL Hashes

### ISSUE THREAD

**Issue by zecchino1** [google/grr#460]
When running import_nsrl_hashes.py to import the NSRL the following error is received:

Traceback (most recent call last):
File "import_nsrl_hashes.py", line 100, in 
flags.StartMain(main)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
main([sys.argv[0]])
File "import_nsrl_hashes.py", line 83, in main
startup.Init()
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/startup.py", line 86, in Init
ConfigInit()
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/startup.py", line 37, in ConfigInit
config_lib.ParseConfigCommandLine()
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1662, in ParseConfigCommandLine
CONFIG.Initialize(filename=flags.FLAGS.config, must_exist=True)
File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/config_lib.py", line 1178, in Initialize
raise ConfigFormatError("Unable to parse config file %s" % filename)
grr.lib.config_lib.ConfigFormatError: Unable to parse config file /etc/grr/grr-server.yaml

**Comment by destijl** [comment]
This just looks like you have an error in your config. Do the other parts of GRR run with the same config? Try importing it as yaml in ipython:

```
yaml.load(open(filename, "rb"))
```

**Comment by zecchino1** [comment]
Actually I think the problem is that one that was built was local.server.yaml, if it ok to just change it to this, since I saw here it looks like it could be either or?

To Encrypt and add a password to the code & driver signing certificates

Copy the keys (PrivateKeys.executable_signing_private_key & PrivateKeys.driver_signing_private_key) from the current GRR configuration file (whichever you’re using)

/etc/grr/grr-server.yaml

/etc/grr/server.local.yaml

Save these two keys as new text files temporarily. You’ll need to convert the key text to the normal format by removing the leading whitespace and blank lines:

**Comment by zecchino1** [comment]
destijl, 

Thank you for you help, I was able to resolve this issue by doing the following:

In my /etc/grr directory, I didn't have the grr-server.yaml. 
I moved a copy of it from the /grr-server/install_data/etc folder, re-ran grr_config_updater initialize

After this the import NSRL command worked
