### ISSUE TITLE
analyze memory client is not working

### ISSUE THREAD

**Issue by dfuschini** [google/grr#470]
I have been trying to make this feature works but so far wit no success. I ve already downloaded de the repository, created the .rekallrc with the git url and the directory to the repository local.
The proxy is also figured and working fine.

Regards

**Comment by grrrrrrrrr** [comment]
Hey,

I don't think you need to do any of this. The AnalyzeClientMemory flow
should basically work out of the box. What is the error you see? Also, what
OS is the client you are running this against?

Cheers,
-Andy

**Comment by dwendt** [comment]
Hey, here's my backtrace. I've been trying to get various rekall modules to run, here's the backtrace from the MemoryCollector flow. 
```
	Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 93, in CheckAnalyzeClientMemory raise flow.FlowError("Unable to image memory: %s." % responses.status) FlowError: Unable to image memory: message GrrStatus { child_session_id : SessionID: aff4:/C.395a9a8be104b5aa/flows/F:70C7DBD0/F:516064CD cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.078125 } error_message : u'Traceback (most recent call last):\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 613, in RunStateMethod\n responses=responses)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 353, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 138, in ComponentLoaded\n raise flow.FlowError("Component load failed.")\nFlowError: Component load failed.\n' network_bytes_sent : 560 status : GENERIC_ERROR }.
```

**Comment by grrrrrrrrr** [comment]
This is an issue with component loading, one of the reasons we want to get rid of them. I assume that you get the same backtrace with all AnalyzeClientMemory flows as well?

Sadly, it's really hard to troubleshoot those import problems. It's probably some library that doesn't work on your machine for some reason but finding out which one will be hard.

If you really need this functionality, you might want to try the components (and maybe the clients too) from the nightly build at https://ci.appveyor.com/project/destijl/grr/build/artifacts

**Comment by lodr74** [comment]
Getting the same error on the following hosts:

- Windows , 2012ServerR2 6.3.9600SP0
- Linux , RedHat 7.3
- Debian, Ubuntu 16.4
-  Windows, 2016 Server Datacenter


GRR Client Version
3102

**Comment by grrrrrrrrr** [comment]
Hm I just set up a server to try this. Worked on both my test machines:
Windows , 2012ServerR2 6.3.9600SP0
Windows , 2008ServerR2 6.1.7601SP1

All I did was running the install script from scratch and it just works. Might need another look next week.

**Comment by grrrrrrrrr** [comment]
@lodr74 you have a completely different error. Your client can't decrypt the component it got from the server. Wrong keys might be one reason or maybe the components also don't exist on the server at all. You could try redoing the grr_config_updater upload_components step?

**Comment by lodr74** [comment]
yes redoing the grr_config_updater and then uploading them to the repository fixed the issue.

**Comment by grrrrrrrrr** [comment]
I'm not sure what needs to be done here. I tried to run the memory analysis and it worked just fine without any problems. @dfuschini if there is anything else we can help with, please reopen but I'll mark this one as done.

**Comment by dfuschini** [comment]
No problem Andreas. thank you.

Regards

Diego 

Enviado do meu iPhone
