### ISSUE TITLE
grr_config_updater download_missing_rekall_profiles not working (auth problem)

### ISSUE THREAD

**Issue by pettai** [google/grr#493]
GRR version: 3.1.0.2, installed via the script (.deb package) 

This seems to be an auth problem, but should it really require auth ?

root@grr:~# grr_config_updater --secondary_configs /etc/grr/server.local.yaml download_missing_rekall_profiles
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/grr/server.local.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Downloading missing Rekall profiles.
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 76, in ConfigUpdater
    flags.StartMain(config_updater.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 991, in main
    s.GetMissingProfiles()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rekall_profile_server.py", line 156, in GetMissingProfiles
    for metadata in aff4.FACTORY.Stat(urn_to_profile):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/aff4.py", line 973, in Stat
    token=token):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 738, in MultiResolvePrefix
    limit=remaining_limit)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 772, in ResolvePrefix
    token, [subject], self.GetRequiredResolveAccess(attribute_prefix))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/aff4_objects/user_managers.py", line 45, in Decorated
    result = func(this, token, *args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/aff4_objects/user_managers.py", line 297, in CheckDataStoreAccess
    ValidateToken(token, subjects))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/aff4_objects/user_managers.py", line 125, in ValidateToken
    subject=GetSubjectForError())
grr.lib.access_control.UnauthorizedAccess: Must give an authorization token for [<aff4:/rekall_profiles/v1.0/nt/GUID/DFEF9132713A43689FC9FB795CC7567E2 age=2017-05-01 05:38:16>]

The documentation also seems falling behind, this option isn't documented...

But the working workaround (running grr_console instead) was documented here:
https://github.com/google/grr-doc/blob/master/troubleshooting.adoc#missing-rekall-profiles

**Comment by grrrrrrrrr** [comment]
This code has been updated and a token is now passed (https://github.com/google/grr/blob/master/grr/server/rekall_profile_server.py#L157) so this is fixed.

**Comment by pettai** [comment]
Was this also pushed to the autobuilds ?

I get a different error message while executing this on the latest autobuild version of grr-server
(from 2017-08-18T15:10UTC_5ca186b50f48098d66ea26bd0278c9d1866f0005/travis_job_712.6_server_deb)

grr_config_updater download_missing_rekall_profiles
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/grr//server.local.yaml" >
Downloading missing Rekall profiles.
Exception in thread profiles-Thread-22 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Exception in thread profiles-Thread-24 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-31 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-39 (most likely raised during interpreter shutdown):
 Exception in thread profiles-Thread-40 (most likely raised during interpreter shutdown):
 Exception in thread profiles-Thread-47 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-5 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-8 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-13 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Exception in thread profiles-Thread-21 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/threadpool.py", line 158, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread profiles-Thread-15 (most likely raised during interpreter shutdown):
 Exception in thread profiles-Thread-17 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Traceback (most recent call last):Traceback (most recent call last):
 Exception in thread profiles-Thread-49 (most likely raised during interpreter shutdown):
 Exception in thread profiles-Thread-12 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-7 (most likely raised during interpreter shutdown):
 Exception in thread profiles-Thread-45 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerException in thread profiles-Thread-37 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-25 (most likely raised during interpreter shutdown):Exception in thread profiles-Thread-6 (most likely raised during interpreter shutdown):

Traceback (most recent call last):Exception in thread profiles-Thread-27 (most likely raised during interpreter shutdown):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
 Exception in thread profiles-Thread-42 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/threadpool.py", line 158, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'Exception in thread profiles-Thread-48 (most likely raised during interpreter shutdown):


Traceback (most recent call last):

**Comment by pettai** [comment]
Right, it seems to be working fine, I just wasn't expecting the clutter...
