### ISSUE TITLE
"AnalyzeClientMemory" Flow - yarascan_physical plugin is invalid

### ISSUE THREAD

**Issue by kalle44** [google/grr#522]
Hi,

I tried to detect a malware on a windows client using the "AnalyzeClientMemory" Flow with the yarascan-plugin. 
The flow ran without an error. 
The Yara-Rule I used: https://raw.githubusercontent.com/Yara-Rules/rules/master/malware/MALW_Kovter.yar
The Client was NOT infected by the Kovter Malware at this time.
Some part of Result-Output of the AdminUI:

![yarascan_detect1](https://user-images.githubusercontent.com/29337312/27608280-2998cbc4-5b87-11e7-80fe-4e54e3299473.PNG)

The Output looks like the Output of the traditionally yarascan plugin in Rekall. Every line represents a 
hit, right?
It seems that a hit ist listed even if just a part of a string matches. The same problem occurs, when I 
use other yara-rules. 
This problem is descripted in hier http://www.rekall-forensic.com/docs/References/Papers/DIIN_673.pdf by Michael Cohan. 
I think, the solution for my issue would be to use the Rekall-Plugin "yarascan_physical".
Using this plugin produces a ValueError with this traceback:

Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 586, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 276, in End raise flow.FlowError("Error running plugins: %s" % all_errors) FlowError: Error running plugins: Traceback (most recent call last): File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\grr_rekall.py", line 296, in Iterate rekal_session.RunPlugin(plugin_request.plugin, **plugin_args) File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\rekall\session.py", line 843, in RunPlugin self._HandleRunPluginException(ui_renderer, e) File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\rekall\session.py", line 839, in RunPlugin "Invalid plugin: %s" % original_plugin_obj) ValueError: Invalid plugin: yarascan_physical

I'm using the GRR version from Head, so I need so set the component_version to 0.4 otherwise this error occurs 

![rekall_component version error](https://user-images.githubusercontent.com/29337312/27626026-d5c9bda4-5be6-11e7-90e0-be6d39586b2f.PNG)

Does the Vaue Error occure because the _yarascan_physical_ plugin is not available in the component version 0.4?

Hopefully someone can help me with this :)

Greetings,
John

**Comment by kalle44** [comment]
I installed Rekall version 1.6.0 manual on my windows client. The plugin yarascan_physical is available in this version. 
So basically, solving the component error issue descriped above would help me a lot :)
