### ISSUE TITLE
GRR Rekall Component - How to update version 0.4 to 1.6.0?

### ISSUE THREAD

**Issue by kalle44** [google/grr#523]
Hi,

I thougt closing my issue #522  and open a new one with the actual problem would be the better idea.

I want to start a "AnalyzeClientMemory" flow using the Rekall-Plugin _yarascan_physical_.
Because I'm using the GRR Version from HEAD in a docker-container I need to set the component version to 0.4 bevor starting the flow. 
This error occures:
### 
Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 586, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 276, in End raise flow.FlowError("Error running plugins: %s" % all_errors) FlowError: Error running plugins: Traceback (most recent call last): File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\grr_rekall.py", line 296, in Iterate rekal_session.RunPlugin(plugin_request.plugin, **plugin_args) File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\rekall\session.py", line 843, in RunPlugin self._HandleRunPluginException(ui_renderer, e) File "C:\Windows\System32\GRR\3.1.0.2\components\grr-rekall\0.4\rekall\session.py", line 839, in RunPlugin "Invalid plugin: %s" % original_plugin_obj) ValueError: Invalid plugin: yarascan_physical

I think that the plugin is not available in the component version 0.4.

Regarding #508 I set up a new virtual machine an installed grr from head using a docker container.
I looked up the installed component version after installation finished:
_-rw-r--r-- 1 root root 3622993 Jun 20 12:44 grr-rekall_0.4_cp27-cp27m-win32.bin
-rw-r--r-- 1 root root 3613110 Jun 20 12:44 grr-rekall_0.4_cp27-cp27m-win_amd64.bin
-rw-r--r-- 1 root root 5154052 Jun 20 12:44 grr-rekall_0.4_cp27-cp27mu-linux_i686.bin
-rw-r--r-- 1 root root 5217293 Jun 20 12:44 grr-rekall_0.4_cp27-cp27mu-linux_x86_64.bin_

I didn't run _grr_config_updater initialize_ yet, so there are no binaries in AdminUI.

Is there a way, I can install the component version 1.6.0 ? :)

Greetings,
John

**Comment by mbushkov** [comment]
You can download a nightly client templates+components build:
https://ci.appveyor.com/project/destijl/grr/build/artifacts

As these are the nightly builds, they may be rather unstable, but using them is probably the easiest option until we release a new GRR client version with an updated Rekall (unless you want to build a Windows client/component yourself from scratch).

Please note that using the nightly-built components on a release client version most likely won't work: i.e. you'll need to use a nightly client template _and_ a nightly component. You'll need to repack client templates into installers (https://github.com/google/grr-doc/blob/5ca3a69315ca311c7c4d81f66a03879bf3c96371/admin.adoc#repacking-the-client-with-a-new-configuration) and upload the components to GRR server using grr_config_updater (https://github.com/google/grr/blob/1aeb8d1ee69b448c3dc55e419440a61e40ddac1f/grr/client/components/README.txt). This process may not be entirely smooth, please see:
  * https://groups.google.com/d/msg/grr-users/kpx6rLj2Fp4/TB7WiRRhAAAJ
  * https://github.com/google/grr/issues/508

As soon as I have a bit of time, I'll try to go through this process myself and will check if it works as expected.

Another thing to note is that these nightly builds are built on AppVeyor's infrastructure. If you're going to deploy these clients/components on your machines, you're effectively trusting AppVeyor to be secure.

**Comment by kalle44** [comment]
Hi mbushkov,
first of all thank you for answer :)

I downloaded the templates and copy the: 
 grr-client GRR_3.1.2.7_i386.exe.zip **into** /usr/share/grr-server/grr-response-templates/templates/
 Rekall-Component  grr-rekall_1.6.0_cp27-cp27m-win_amd64.bin **into** /usr/share/grr-server/grr-response-templates/components/ 
After this I ran grr_config_updater repack-clients. Now I can see the client and the component on the AdminUI. I downloaded the client.exe and ran it on my windows client. This created a new folder in C:\Windows\System32\GRR\3.1.2.7

The client-version shown on the AdminUI is 3127 now.

I started a "AnalyzeClientMemory" Flow with the "pslist" plugin to give it a try.
The rekall-component was pushed to the client, but the flow chrashed with this traceback:

Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 586, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 276, in End raise flow.FlowError("Error running plugins: %s" % all_errors) FlowError: Error running plugins: Traceback (most recent call last): File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\grr_rekall.py", line 303, in Iterate rekal_session.RunPlugin(plugin_request.plugin, **plugin_args) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\session.py", line 862, in RunPlugin self._HandleRunPluginException(ui_renderer, e) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\session.py", line 858, in RunPlugin "Invalid plugin: %s" % original_plugin_obj) ValueError: Invalid plugin: pslist 

Maybe the  context-information can help:
![image](https://user-images.githubusercontent.com/29337312/27691312-ee9ecfa6-5ce3-11e7-89cb-d232d09fea51.png)

Do you know, why I get this traceback?

**Comment by mbushkov** [comment]
Sounds like Rekall has an issue with finding a profile for the system. Can you please run AnalyzeClientMemory with debug logging turned on (you'll find the option in the "advanced" section of the flow) and paste the full log here (you'll see the log either in Results or Log tab of the flow)?

Also, does anything change after you update the profiles on GRR server  (`grr_config_updater download_missing_rekall_profiles`)?

**Comment by kalle44** [comment]
Hi mbushkov,
I took some screenshots of the log:

![image](https://user-images.githubusercontent.com/29337312/27724608-f9cdd84c-5d72-11e7-927f-ff9eaafb8a4d.png)
![image](https://user-images.githubusercontent.com/29337312/27724650-1ceb7ff0-5d73-11e7-8809-5e35a5fb1891.png)
![image](https://user-images.githubusercontent.com/29337312/27724661-2e0db5fa-5d73-11e7-8138-291ef63a8f9c.png)

When I run (grr_config_updater download_missing_rekall_profiles) I got this Error:

(grr-server) root@b19a0e28d0fa:/# grr_config_updater download_missing_rekall_profiles
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Downloading missing Rekall profiles.
ERROR:2017-06-30 06:54:31,792 threadpool:109] Caught exception in worker thread (Unnamed task): <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/threadpool.py", line 101, in ProcessTask
    target(*args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rekall_profile_server.py", line 77, in GetProfileByName
    profile_name, version=version)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rekall_profile_server.py", line 93, in GetProfileByName
    handle = urllib2.urlopen(url, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: urlopen error timed out

Looks like grr can't access the rekall-profile repository through the docker-container? 

I copied the files from the rekall_profil folder of the grr client 3.1.0.2 into to the rekall folder of the 3.1.2.7 because the windows profile seems to be in the 3.1.0.2 folder. 
This doesn't help to solve the issue.

**Comment by scudette** [comment]
It looks like Rekall failed to load the pmem driver properly. Can you
check that it is running on the system? You can do this by :

sc query pmem

at an elevated prompt.  Can you also check that you can run the normal
Rekall on this system using:

rekall -v --live Memory pslist

(This is equivalent to what GRR is trying to do so this will determine
if the issue is with Rekall or GRR).

I think on recent windows systems under some configurations it is not
allowed to add a driver to the system after boot (like Rekall is
trying to do here). In these systems you will need to load the pmem
driver in the system at boot time before you can access raw memory.

Thanks
Michael.

**Comment by kalle44** [comment]
Hi Michael,

I just reinstalled the Windows VM to avoid further problems :D
The flow runs without an error and GRR shows the result.

But, should'nt there be _translated_ field in the Hex Dump column to show the user which string of the yara-rule fires? 
![image](https://user-images.githubusercontent.com/29337312/27782346-703cd86e-5fd2-11e7-9a1f-7db197bd877c.png)

I appreciate your support, you're doing a great job :)

Thanks,
John

**Comment by mbushkov** [comment]
John, thank you :)

Judging by Rekall's code (https://github.com/google/rekall/blob/e13d794542052de0d138acb07ef3f032b008ae94/rekall-core/rekall/plugins/windows/malware/yarascan.py#L329), there should be a "Rule" column with a matching rule. Do you see it in the results?

I'd also suggest clicking on "Download As: CSV" button - this way you'll get a flattened CSV file which may be easier to look at/analyze.

**Comment by kalle44** [comment]
The "Rule" column is in front of the HexDump column. I thought, the relation between the Rule and the Hexdump column is the matching string. So, the HexValue shows which string of the Yara-Rule was found?

Another thing I don't understand is, why does GRR show me the hit in the same context for more than once?

![image](https://user-images.githubusercontent.com/29337312/27816957-f73e31fc-608e-11e7-9796-e762f7910a40.png)
![image](https://user-images.githubusercontent.com/29337312/27817049-67b0a37a-608f-11e7-9162-632eef1f9b1b.png)
![image](https://user-images.githubusercontent.com/29337312/27817010-35c17e70-608f-11e7-9d09-971de6a57e95.png)

**Comment by grrrrrrrrr** [comment]
You get one hit for each string the rule matches on. If your rule is like

rule ABC {
strings:
  $a="a"
  $b="b"
  $c="c"
condition:
  all of them
}

you will get three hits in the same context (fewer than 3 and the rule will not trigger as per the conditions) and the middle character of the three hexdumps will be an "a","b", and "c" respectively. The rule name will be "ABC" for all three hits (since there might be more hexdumps that correspond to different rules).

Does that make sense?

**Comment by kalle44** [comment]
Ok, thank you.:) It  makes perfectly sense for me.
There is a proverb here in Germany:  can't see the wood for the trees...
I used the condition "all of them" because of this and the same string for 2 times i get the exact same entry twice.:D
