### ISSUE TITLE
PluginError: Failed to compile yara expression: undefined string "$*"

### ISSUE THREAD

**Issue by kalle44** [google/grr#524]
Hi, 

when I create a GRR flow with the Rekall Plugin yarascan_physical and hand over a Yara-Rule
like this one:

rule xy
{
strings:
           $s1="blah"
           $s2="Hello"
           $s3="World"
condition:
            all of them
}

I get this Traceback:
Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow_runner.py", line 586, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flow.py", line 307, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flows/general/memory.py", line 276, in End raise flow.FlowError("Error running plugins: %s" % all_errors) FlowError: Error running plugins: Traceback (most recent call last): File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\grr_rekall.py", line 303, in Iterate rekal_session.RunPlugin(plugin_request.plugin, **plugin_args) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\session.py", line 862, in RunPlugin self._HandleRunPluginException(ui_renderer, e) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\session.py", line 855, in RunPlugin plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\session.py", line 914, in _GetPluginObj return plugin_cls(*args, **kwargs) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\obj.py", line 139, in __call__ return self._target(*(self._args + args), **new_kwargs) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\registry.py", line 72, in __call__ res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs) File "C:\Windows\System32\GRR\3.1.2.7\components\grr-rekall\1.6.0\rekall\plugins\windows\malware\yarascan.py", line 288, in __init__ "Failed to compile yara expression: %s" % e) PluginError: Failed to compile yara expression: undefined string "$*"

To make it run without this error, I need to remove the tabs in every line of the yara-rule.
I'm using a python skript to start the flow via the grr_api_shell. 
This makes it easy to apply this workaround, I just replace the "\t" with ""

I looked up the Code of the Plugin:
https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/windows/malware/yarascan.py
But I don't understand, why this error occures!?
Can somebody explain it to me, pls? :)

Thanks,
John

**Comment by grrrrrrrrr** [comment]
This is a Rekall bug, Rekall has its own parser for Yara signatures that is broken:

$ from rekall.plugins.tools import yara_support

$ sig_notab
'rule xy\n{\nstrings:\n$s1="blah"\n$s2="Hello"\n$s3="World"\ncondition:\nall of them\n}\n'

$ yara_support.parse_yara_to_ast(sig_notab)
[{'condition': 'all of them\n',
  'meta': {},
  'name': 'xy',
  'strings': [('$s1', '"blah"'), ('$s2', '"Hello"'), ('$s3', '"World"')]}]

$ sig
'rule xy\n{\nstrings:\n\t$s1="blah"\n\t$s2="Hello"\n\t$s3="World"\ncondition:\n\tall of them\n}\n'

$ yara_support.parse_yara_to_ast(sig)
[{'condition': '$s1="blah"\n\t$s2="Hello"\n\t$s3="World"\ncondition:\n\tall of them\n',
  'meta': {},
  'name': 'xy',
  'strings': []}]

@scudette is probably the best person to look at the parser, in the meantime please just strip the tabs.

**Comment by scudette** [comment]
Yarascan_physical plugin transforms the yara expression in order to more efficiently find physical memory hits (if you are interested in how it works, I encourage you to read http://www.rekall-forensic.com/docs/References/Papers/DIIN_673.html). 

Due to this, only a small subset of the yara syntax is supported. For example we do not support more complex conditions. Additionally since in the yara syntax tabs use is not well defined (we do not support tabs).

To give an example, use of tabs as you use them is equivalent to whitespace when outside a string, but they actually mean literal tab within a regex or string (from the yara test case - Note that here \\t means literal tab and not the escaped version \t):

```
"rule test { strings: $a = /ppi\\tmi/ condition: $a }"
```

For this reason we do not automatically strip tabs before parsing and we do not have logic to indicate when tabs are considered keywords and when they are considered whitespace. Although the specific yara test case above is *very* obscure (who would add a literal tab inside a regex instead of escaping it?), so maybe it makes sense to always treat tabs as whitespace and just fail on the more obscure yara examples.

**Comment by grrrrrrrrr** [comment]
I'll close this here as it's not a GRR issue but a Rekall one (if it even is an issue at all).
