### ISSUE TITLE
new user having trouble installing docker image 

### ISSUE THREAD

**Issue by ema1904** [google/grr#533]
Hello I'm trying to install the docker image for google grr but i keep getting these errors 

ERROR:2017-08-07 18:55:15,956 sqlite_data_store:272] DB error in file: /usr/share/grr-server/lib/python2.7/site-packages/grr/var/grr-datastore/W/4.sqlite for query: ('SELECT predicate, value, timestamp FROM tbl\n               WHERE subject = ? AND predicate LIKE ?\n                     AND timestamp >= ? AND timestamp <= ?\n                     ORDER BY timestamp DESC LIMIT ?', ('aff4:/W/4', 'notify:%', 0, 1502132115955619, 10000))
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
    return self.cursor.execute(*args)
OperationalError: no such table: tbl
ERROR:2017-08-07 18:55:15,958 sqlite_data_store:272] DB error in file: /usr/share/grr-server/lib/python2.7/site-packages/grr/var/grr-datastore/W/4.sqlite for query: ('SELECT predicate, value, timestamp FROM tbl\n               WHERE subject = ? AND predicate LIKE ?\n                     AND timestamp >= ? AND timestamp <= ?\n                     ORDER BY timestamp DESC LIMIT ?', ('aff4:/W/4', 'notify:%', 0, 1502132115945142, 10000))
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
    return self.cursor.execute(*args)
OperationalError: no such table: tbl
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_server", line 11, in <module>
    sys.exit(GrrServer())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 82, in GrrServer
    flags.StartMain(grr_server.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "/usr/share/grr-server/bin/grr_server", line 11, in <module>
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 32, in main
        sys.exit(GrrServer())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 82, in GrrServer
    worker.main([argv])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/worker/worker.py", line 29, in main
flags.StartMain(grr_server.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
        worker_obj.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 106, in Run
    main([sys.argv[0]])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 32, in main
    processed = self.RunOnce()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 148, in RunOnce
worker.main([argv])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/worker/worker.py", line 29, in main
    worker_obj.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 106, in Run
        processed = self.RunOnce()
queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 148, in RunOnce
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 566, in GetNotificationsByPriority
        queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 566, in GetNotificationsByPriority
    self._GetUnsortedNotifications(queue_shard).values(), queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 635, in _GetUnsortedNotifications
self._GetUnsortedNotifications(queue_shard).values(), queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 635, in _GetUnsortedNotifications
        limit=10000):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 799, in ResolvePrefix
    limit=10000):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 799, in ResolvePrefix
    end, new_limit)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/utils.py", line 63, in NewFunction
    return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 377, in GetValuesFromPrefix
    end, new_limit)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/utils.py", line 63, in NewFunction
    data = self.Execute(query, args).fetchall()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 377, in GetValuesFromPrefix
        return self.cursor.execute(*args)
sqlite3data = self.Execute(query, args).fetchall()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
.OperationalError:     no such table: tbl
return self.cursor.execute(*args)
sqlite3.OperationalError: no such table: tbl
ERROR:2017-08-07 18:55:15,954 sqlite_data_store:272] DB error in file: /usr/share/grr-server/lib/python2.7/site-packages/grr/var/grr-datastore/W/4.sqlite for query: ('SELECT predicate, value, timestamp FROM tbl\n               WHERE subject = ? AND predicate LIKE ?\n                     AND timestamp >= ? AND timestamp <= ?\n                     ORDER BY timestamp DESC LIMIT ?', ('aff4:/W/4', 'notify:%', 0, 1502132115952988, 10000))
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
    return self.cursor.execute(*args)
OperationalError: no such table: tbl
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_server", line 11, in <module>
    sys.exit(GrrServer())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/distro_entry.py", line 82, in GrrServer
    flags.StartMain(grr_server.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 121, in StartMain
    main([sys.argv[0]])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/tools/grr_server.py", line 32, in main
    worker.main([argv])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/worker/worker.py", line 29, in main
    worker_obj.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 106, in Run
    processed = self.RunOnce()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/worker.py", line 148, in RunOnce
    queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 566, in GetNotificationsByPriority
    self._GetUnsortedNotifications(queue_shard).values(), queue)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/queue_manager.py", line 635, in _GetUnsortedNotifications
    limit=10000):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 799, in ResolvePrefix
    end, new_limit)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/utils.py", line 63, in NewFunction
    return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 377, in GetValuesFromPrefix
    data = self.Execute(query, args).fetchall()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/data_stores/sqlite_data_store.py", line 269, in Execute
    return self.cursor.execute(*args)
sqlite3.OperationalError: no such table: tbl

**Comment by mbushkov** [comment]
Hi! I tried to reproduce with grr:latest docker image and couldn't. GRR worked for me - I could run a flow on a client and run a hunt.
A few questions:
* Did you follow the instructions from https://github.com/google/grr-doc/blob/master/docker.adoc?
* What command did you use to run Docker?
* Which operations triggered the traceback?

**Comment by Kwantem** [comment]
I know that this was addressed, but the command that you use is very important in order to run the Docker. If you need any hands on assistance please feel free to contact me.

**Comment by ema1904** [comment]
yes I used those exact instructions 
it appears when running " grrdocker/grr:v3.1.0.2-latest grr " and " grrdocker/grr:latest grr "

**Comment by ema1904** [comment]
i got it to work, I installed docker.io first but when I uninstalled it and installed docker following this link 
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce 
I was able to install it. my issue now is downloading the server i get this error 


electing previously unselected package grr-server.
(Reading database ... 214015 files and directories currently installed.)
Preparing to unpack grr-server_3.1.0-2_amd64.deb ...
Unpacking grr-server (3.1.0-2) ...
dpkg: dependency problems prevent configuration of grr-server:
 grr-server depends on prelink; however:
  Package prelink is not installed.

dpkg: error processing package grr-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Errors were encountered while processing:
 grr-server

**Comment by demonchild2112** [comment]
This is the Docker file that is used to generate the grr:latest docker image. We recently stopped including prelink in the image: https://github.com/google/grr/commit/a76dbe219a1c492a92bb0a7826732e87803fe5b3

The 3.1.0-2 server deb had prelink as a dependency, which is why you are getting that error.

Are you trying to install the server deb from inside the Docker container?

**Comment by ema1904** [comment]
I'm following the link provided in the installation guide (https://github.com/google/grr-doc/blob/master/docker.adoc). I can access the admin UI in http:localhost:8000 but when I put in the username and password it doesn't login (localhost:demo)

**Comment by ema1904** [comment]
I'm following the link provided in the installation guide (https://github.com/google/grr-doc/blob/master/docker.adoc). I can access the admin UI in http:localhost:8000 but when I put in the username and password it doesn't login.

**Comment by ema1904** [comment]
i got the server to work but when trying to download the client, there is nothing in manage binaries. it shows none under python hacks, executalbes and components

**Comment by demonchild2112** [comment]
For the v3.1.0.2 image, we repacked client templates and uploaded them to the datastore, which is why they appear under 'Manage Binaries'. For the latest image, we are not doing that. If you would like to use the latest version of GRR, I recommend installing the server deb (see https://github.com/google/grr/releases)

**Comment by ema1904** [comment]
do you recommend using the v3.1.0.2 or the latest version ?

**Comment by demonchild2112** [comment]
v3.1.0.2 is more than a year old. To get the latest features and improvements, you should install the 3.2.0 server and clients. Note however that v3.2.0 is still in beta. We should have a final release candidate soon.

**Comment by demonchild2112** [comment]
I've added client templates to the 'grrdocker/grr:latest' image. They should get repacked when a container for the image is created.

Commit: https://github.com/google/grr/commit/c6a250c20afe4de95d360b408842996e340503a9
