### ISSUE TITLE
Exporting flow results with "download as" function in AdminUI fails

### ISSUE THREAD

**Issue by B3N4K** [google/grr#538]
Hello,

I just ran into a problem when exporting results from my flows. When i try to use the web ui to download the results in zipped archive (csv, yaml or sqlite doesn't matter) the download stops after approximately 16MB, the archive with the results is corrupted and in admin_ui application output i get following error(s):

```
::ffff:127.0.0.1 - - [27/Sep/2017 12:55:17] "GET /api/clients/C.08fcb0dad0ed71a7/flows/F:1CF66C75/exported-results/csv-zip HTTP/1.1" 200 16629262
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/usr/local/grr/grr/gui/api_call_handler_base.py", line 45, in GenerateContent
    for chunk in self.content_generator:
  File "/usr/local/grr/grr/server/instant_output_plugin.py", line 264, in ApplyPluginToMultiTypeCollection
    for chunk in plugin.ProcessValues(stored_cls, GetValues):
  File "/usr/local/grr/grr/server/instant_output_plugin.py", line 227, in ProcessValues
    for chunk in self.ProcessSingleTypeExportedValues(value_type, generator):
  File "/usr/local/grr/grr/server/output_plugins/csv_plugin.py", line 63, in ProcessSingleTypeExportedValues
    first_value = next(exported_values, None)
  File "/usr/local/grr/grr/server/instant_output_plugin.py", line 169, in _GenerateSingleTypeIteration
    for converted_response in converted_responses:
  File "/usr/local/grr/grr/server/instant_output_plugin.py", line 208, in _GenerateConvertedValues
    batch_with_metadata, token=self.token):
  File "/usr/local/grr/grr/server/export.py", line 357, in BatchConvert
    for result in self.Convert(metadata, value, token=token):
  File "/usr/local/grr/grr/server/export.py", line 348, in Convert
    class_obj = self.MakeFlatRDFClass(value)
  File "/usr/local/grr/grr/server/export.py", line 314, in MakeFlatRDFClass
    dict(Flatten=Flatten))
  File "/usr/local/grr/grr/lib/rdfvalues/structs.py", line 1472, in __init__
    super(RDFStructMetaclass, cls).__init__(name, bases, env_dict)
  File "/usr/local/grr/grr/lib/rdfvalue.py", line 62, in __init__
    super(RDFValueMetaclass, cls).__init__(name, bases, env_dict)
  File "/usr/local/grr/grr/lib/registry.py", line 45, in __init__
    (cls, cls.classes[cls.__name__]))
RuntimeError: Duplicate names for registered classes: <class 'abc.AutoExportedRDFString'>, <class 'abc.AutoExportedRDFString'>
::ffff:127.0.0.1 - - [27/Sep/2017 12:55:17] "GET /api/clients/C.08fcb0dad0ed71a7/flows/F:1CF66C75/exported-results/csv-zip HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 35528, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

When i try to download smaller result sets all is working well. Only larger resultsets are failing in this manner. Is this (know) bug or is something wrong on my side? When i view the results in adminui all is displayed correctly and works well.

Also related question, the documentation mentions that i can also export by using tool grr_export however i have no such tool available in my GRR installation. Is that information deprecated and the grr_export tool is no longer available?

Thanks for any help!

**Comment by grrrrrrrrr** [comment]
Hm this is a bug. We generate those AutoExported... classes on the fly and it seems we generate them multiple times instead of reusing the cached values. Have to look why the cache doesn't work here. Thanks for the report!

**Comment by B3N4K** [comment]
Thank you!

**Comment by mbushkov** [comment]
Quick question - what flow produced the results that you were trying to export?

We deprecated grr_export utility in the latest release in favor of the "Download as" functionality and GRR API. I'll update the documentation accordingly. 

In the meantime (while we're fixing the bug) you can fetch the results in JSON format by either triggering the URL:
/api/v2/clients/C.08fcb0dad0ed71a7/flows/F:1CF66C75/results?count=1000000

You can also use grr_api_shell to download the results in text-protobuf format:
```
grr_api_shell --basic_auth_username "user" --basic_auth_password "pwd" \
  --exec_code 'for r in grrapi.Client("C.1234567890ABCDEF").Flow("F:BB628B23").ListResults(): print str(r.payload)' \
  http://localhost:1234
```

Or in JSON format:
```
grr_api_shell --basic_auth_username "user" --basic_auth_password "pwd" \
  --exec_code 'from google.protobuf import json_format; print "[%s]" % ",".join(json_format.MessageToJson(r.payload) for r in grrapi.Client("C.1234567890ABCDEF").Flow("F:BB628B23").ListResults())' \
  http://localhost:1234
```

(More about GRR api client shell here: https://github.com/google/grr/tree/master/api_client/python#using-command-line-api-shell)

**Comment by B3N4K** [comment]
The flow that produced the undownloadable results was **ArtifactCollectorFlow**, specifically (for example) collecting following artifacts:

```
WindowsEnvironmentVariableAllUsersAppData
WindowsEnvironmentVariableProgramFiles
WindowsEnvironmentVariableProgramFilesX86
WindowsEnvironmentVariableSystemDrive
WindowsEnvironmentVariableTemp
WindowsEnvironmentVariableWinDir
WindowsFileTypeAutorunAssociations
WindowsMostRecentApplication
WindowsPersistenceMechanisms
WindowsProgramsCache
WindowsRecycleBin
WindowsTempDirectories
WindowsUpdateStatus
WindowsUserDownloadsDirectory
WindowsUserRecentFiles
```

Thanks!

**Comment by grrrrrrrrr** [comment]
We fixed the export in head with https://github.com/google/grr/commit/9248765d6bbc799de1511971c6c3af75e4847f6b

Let us know if there are more issues!
