### ISSUE TITLE
Adding more artifacts into Interrogate doesn't work

### ISSUE THREAD

**Issue by B3N4K** [google/grr#549]
Hello,

I wanted to add some artifacts into Interrogate so that when new client enrolls it will be interrogated for slightly more info than what the default interrogate asks for. I looked at grr/config/artifacts.py and found out that this should be possible fairly easiely with options provided by this config options. So I tried to add those artifacts i want as part of interrogate to both (one at a time) Artifacts.knowledge_base_additions and Artifacts.interrogate_store_in_aff4_additions but neither works.

When i add them to the interrogate_store_in_aff4_additions then i get following errors:

```
Traceback (most recent call last):
  File "/usr/local/grr/grr/server/flow_runner.py", line 589, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/usr/local/grr/grr/server/flow.py", line 301, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 617, in ProcessCollected
    aff4_output_map, output_collection_map)
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 776, in _ParseResponses
    aff4_output_map)
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 823, in _WriteResultToMappedAFF4Location
    self.GetAFF4PathForArtifactResponses(result_type))
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 873, in GetAFF4PathForArtifactResponses
    (output_type, artifact.GRRArtifactMappings.rdf_map.keys()))
ArtifactProcessingError: No defined RDF type for ExecuteResponse.  See the description for  the store_results_in_aff4 option, you probably want it set to false. Supported types are: [\'Volume\', \'HardwareInfo\', \'SoftwarePackage\']
```
where "ExecuteResponse" is different for different artifacts (sometimes i get Dict etc...).

When i add them to the knowledge_base_additions list then the whole GRR will get broken while grr_worker is cycling incredibly fast in something along following lines:
![image](https://user-images.githubusercontent.com/3751422/32991465-6e07a90c-cd3c-11e7-8737-05ebfa558829.png)

Did i misunderstand those config options and they are in fact not for adding artifacts into interrogate process or is there something else wrong? Those artifacts I am adding are working perfectly fine outside interrogate (when called normally by ArtifactCollector flow).

Thanks for any input!

**Comment by grrrrrrrrr** [comment]
Hey,

adding the artifact to knowledge_base_additions is the right thing to do. It seems like your artifact has an error though, could it be that it calls itself somehow? Does the artifact you want to add work if you just run it without the interrogate?

Cheers,
-Andy

**Comment by B3N4K** [comment]
Hello,

Yes the artifacts in question work perfectly fine outside interrogate (I tested the same artifacts on the same client on the same GRR insallation and it worked just fine) and the artifacts definitely do not call themselves. I even tried it with just 4 artifacts that were all `COMMAND` type and the result was the same.

Unfortunately i am not able to reproduce it now however i get completely different problem now. I have an artifact (defined below, but specific artifact is not at fault, i get same problems with just any other artifacts) and i can launch it just fine by itself. If i have empty `knowledge_base_additions` Interrogate works perfectly fine and i can launch the mentioned artifact just fine afterwards and it passes and results are correct. However if i include this artifact in `knowledge_base_additions` variable, the Interrogate fails and whole GRR gets broken (won't be able to launch any artifacts - even stock ones). Here is an example causing this error:

I have following in `grr/install_data/etc/grr-server.yml`:
```
Artifacts.knowledge_base_additions:
  - XWindowsFirewallRules
```

Following in `grr/grr/artifacts/local/our_artifacts.yml`:
```
---
name: XWindowsFirewallRules
doc: Gets firewall rules.
sources:
- type: COMMAND
  attributes:
    args: ["advfirewall", "firewall", "show", "rule", "name=all"]
    cmd: netsh.exe
labels: [System]
supported_os: [Windows]
urls: ['https://technet.microsoft.com/en-us/library/bb490939.aspx']
```
And both netsh.exe with specified arguments are whitelisted. This artifact is working perfectly on its own when executed outside of interrogate context. When i include it in interrogate context, interrogate fails (state ERROR) with following:
```
ERROR:2017-11-20 15:54:00,597 flow_runner:911] Error in flow aff4:/C.d869a0394ac99750/flows/E:616C8086 (aff4:/C.d869a0394ac99750). Trace: Traceback (most recent call last):
  File "/usr/local/grr/grr/server/flow_runner.py", line 589, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/usr/local/grr/grr/server/flow.py", line 301, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/grr/grr/server/flows/general/discovery.py", line 186, in ProcessKnowledgeBase
    raise flow.FlowError("Error collecting artifacts: %s" % responses.status)
FlowError: Error collecting artifacts: message GrrStatus {
 child_session_id : SessionID:
    aff4:/C.d869a0394ac99750/flows/E:616C8086/E:EC7140C
 cpu_time_used :   message CpuSeconds {
     system_cpu_time : 0.015625
     user_cpu_time : 0.046875
    }
 error_message : u'Traceback (most recent call last):
  File "/usr/local/grr/grr/server/flow_runner.py", line 589, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/usr/local/grr/grr/server/flow.py", line 301, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/grr/grr/server/artifact.py", line 249, in ProcessBase
    deps = self.SetKBValue(responses.request_data["artifact_name"], responses)
  File "/usr/local/grr/grr/server/artifact.py", line 324, in SetKBValue
    ": %s" % artifact_obj)
RuntimeError: Attempt to set a knowledge base value with multiple provides clauses without using Dict.: message Artifact {
 conditions : [
  ]
 doc : u\'Gets firewall rules.\'
 labels : [
   u\'System\'
  ]
 name : ArtifactName:
    XWindowsFirewallRules
 provides : [
  ]
 sources : [
     message ArtifactSource {
      attributes :   message Dict {
          dat : [
              message KeyValue {
               k :   message DataBlob {
                   data : \'cmd\'
                  }
               v :   message DataBlob {
                   data : \'netsh.exe\'
                  }
              }
              message KeyValue {
               k :   message DataBlob {
                   data : \'args\'
                  }
               v :   message DataBlob {
                   list :   message BlobArray {
                       content : [
                           message DataBlob {
                            data : \'advfirewall\'
                           }
                           message DataBlob {
                            data : \'firewall\'
                           }
                           message DataBlob {
                            data : \'show\'
                           }
                           message DataBlob {
                            data : \'rule\'
                           }
                           message DataBlob {
                            data : \'name=all\'
                           }
                        ]
                      }
                  }
              }
           ]
         }
      conditions : [
       ]
      returned_types : [
       ]
      supported_os : [
       ]
      type : COMMAND
     }
  ]
 supported_os : [
   u\'Windows\'
  ]
 urls : [
   u\'https://technet.microsoft.com/en-us/library/bb490939.aspx\'
  ]
}
'
 network_bytes_sent : 258323
 status : GENERIC_ERROR
}
```

Moreover any other artifact collection on this client further on (even stock artifacts) throws following error (in this case i am running stock WMI artifact):
```
ERROR:2017-11-20 16:04:34,223 flow_runner:604] Flow aff4:/C.d869a0394ac99750/flows/F:1D98401F raised Attempt to initialize Knowledge Base failed..
Traceback (most recent call last):
  File "/usr/local/grr/grr/server/flow_runner.py", line 589, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/usr/local/grr/grr/server/flow.py", line 301, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 127, in StartCollection
    "Attempt to initialize Knowledge Base failed.")
KnowledgeBaseUninitializedError: Attempt to initialize Knowledge Base failed.
ERROR:2017-11-20 16:04:34,250 flow_runner:911] Error in flow aff4:/C.d869a0394ac99750/flows/F:1D98401F (aff4:/C.d869a0394ac99750). Trace: Traceback (most recent call last):
  File "/usr/local/grr/grr/server/flow_runner.py", line 589, in RunStateMethod
    direct_response=direct_response, request=request, responses=responses)
  File "/usr/local/grr/grr/server/flow.py", line 301, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/local/grr/grr/server/flows/general/collectors.py", line 127, in StartCollection
    "Attempt to initialize Knowledge Base failed.")
KnowledgeBaseUninitializedError: Attempt to initialize Knowledge Base failed.
```

**Comment by grrrrrrrrr** [comment]
Hey,

I now understand a bit better what's going on, this is all kind of expected / your use case is not really supported.

I told you earlier to add the artifact to the knowledge_base_additions. That is not really correct, those artifacts are used to populate the knowledge base so they need to specify what KB field they provide. Your artifact doesn't write to the KB so the "provides" specification is missing and gives that error (it says multiple provides but the check is just for number of provides != 1 so 0 provides yields the same error, fix is on the way).

Now your other option is to have the artifact write to the clients AFF4 object by using interrogate_store_in_aff4_additions, which is not really what you want either. The underlying assumption here is that interrogation runs and populates the client object + KB while nobody ever looks at the results of the actual flow.

Is running this artifact as part of Interrogate a requirement? We could just add another set of artifacts to run as a config option in that case. Otherwise, maybe you could just run a cron hunt that collects this artifact? Sounds much easier to me, just takes a few clicks to set up. Wdyt?

Cheers,
-Andy

**Comment by B3N4K** [comment]
Hello,

Thank you for the reply. That is what i was afraid of from my understanding of knowledgebase so I kind of expected this outcome.

The use case is a bit different - we want to have "agentless" binary/package that we could run once on a system. It would enroll, receive a list of artifacts to collect, collect and store them and then would turn off and never report again (as it would be most likely removed from the machine right after). The idea is that this way we would collect data from systems that are not acceptable to have constantly running agent on them. Also we want to have it integrated with GRR because we chose GRR as ours unified way to collect forensics data so using just some script for this use case (as we were up until we decided for GRR) would be a step back. Also that would mean that running CRON job to run the collection would be suboptimal (as client would have to be waiting for CRON job to start instead of immediately starting the collection, by then it could have already went to the sleeping state for 10 minutes before checking again if its supposed to run any jobs - even though that could be fixed by changing the `Client.foreman_check_frequency` or `Client.poll_max` variables).

If it would be possible to add another config option to run some artifacts after interrogate as you are suggesting, that would be most definitely the best option for us. What do you think about this?

Thanks a lot for your help and input! It's much appreciated.

Benjamin

**Comment by grrrrrrrrr** [comment]
Hey Benjamin,

Were you able to add more artifacts to interrogate in the end? Is there anything left to do here or can I close this issue?

**Comment by B3N4K** [comment]
Hi,

It's still on my TODO list (and i hope i will get back to it in a month or two).

The cron job you suggested in your last post unfortunately won't be good enough for us. I will have to look into implementing it the way you suggested:

> [to] add another set of artifacts to run as a config option

We are in the final phases of preparation to deploy GRR in our infrastructure (couple thousands computers for starters) and we will need this functionality for "agentless" client that we would be able to use to collect data from those computers where we cannot have the client preinstalled. Therefore it's at the moment priority number two and as soon as we have the GRR up and running this will be the main priority.

If you could hint in any way how to implement this possibility that would be greatly appreciated. I've fiddled with the possibilities a bit but i haven't looked at the code yet and tbh its a bit overwhelming. So i would be thankful for any hint and tip how this "adding of another set of artifacts to be ran on client interrogate" could be implemented.

Thanks a lot!
