### ISSUE TITLE
grr_fuse attempts to contact client even with --refresh_policy=never

### ISSUE THREAD

**Issue by itsnotapt** [google/grr#552]
Even when the `refresh_policy` is used, grr_fuse will attempt to connect to the client agent. I believe the issue is when a file has been seen i.e. we have the stat, however the content has not been downloaded.

Is it possible to add a check in [Read](https://github.com/google/grr/blob/master/grr/tools/fuse_mount.py#L251) for whether the file has content or not? I suppose if there is no content available, just return a 0 byte file?
 
```
$ grr_fuse --config /etc/grr/server.local.yaml --mountpoint=/grrfuse --refresh_policy=never
```

```
$ ls -lh /grrfuse/C.e6b717e5235681c1/fs/os/C:/
-r--r--r-- 0 root root 376K Jul 16  2016 bootmgr
-rw-rw-rw- 0 root root    1 Jul 16  2016 BOOTNXT
drwxrwxrwx 0 root root    0 Jun  4 20:03 Dell
drwxrwxrwx 0 root root    0 Dec 27  2016 Documents and Settings
-rw-rw-rw- 0 root root 6.4G Nov 30 10:31 hiberfil.sys
drwxrwxrwx 0 root root    0 May 26  2017 Intel
dr-xr-xr-x 0 root root    0 Dec 27  2016 MSOCache
drwxrwxrwx 0 root root    0 May 30  2017 NVIDIA
-rw-rw-rw- 0 root root 7.5G Nov 30 10:31 pagefile.sys
drwxrwxrwx 0 root root    0 Jul 16  2016 PerfLogs
drwxrwxrwx 0 root root  12K Dec  1 14:18 ProgramData
dr-xr-xr-x 0 root root  12K Nov  1 17:38 Program Files
dr-xr-xr-x 0 root root  12K Nov 14 08:58 Program Files (x86)
drwxrwxrwx 0 root root 4.0K Dec  1 12:10 Python27
drwxrwxrwx 0 root root    0 Dec 27  2016 Recovery
drwxrwxrwx 0 root root 4.0K May 26  2017 $Recycle.Bin
drwxrwxrwx 0 root root 4.0K Jul 24 22:10 sqlite
-rw-rw-rw- 0 root root  16M Nov 30 10:31 swapfile.sys
drwxrwxrwx 0 root root 160K Nov 30 10:31 System Volume Information
dr-xr-xr-x 0 root root 4.0K May 26  2017 Users
drwxrwxrwx 0 root root  28K Oct 25 03:21 Windows

$ file bootmgr
^C
```

... hangs waiting for timeout.

Timeout errors in the grr_fuse module.

```
Traceback (most recent call last):
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
Traceback (most recent call last):
    return func(*args, **kwargs) or 0
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 583, in read
    offset, fh)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/utils.py", line 35, in Wrapped
    return getattr(self, f)(*args)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/fuse_mount.py", line 518, in Read
    size_threshold=self.size_threshold)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow_utils.py", line 141, in StartFlowAndWait
    return func(*args, **kwargs) or 0
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 583, in read
    WaitForFlow(flow_urn, token=token, timeout=timeout)
    offset, fh)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow_utils.py", line 114, in WaitForFlow
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/utils.py", line 35, in Wrapped
    return getattr(self, f)(*args)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/fuse_mount.py", line 518, in Read
    size_threshold=self.size_threshold)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow_utils.py", line 141, in StartFlowAndWait
    WaitForFlow(flow_urn, token=token, timeout=timeout)
  File "/home/ubuntu/GRR_ENV/local/lib/python2.7/site-packages/grr/server/flow_utils.py", line 114, in WaitForFlow
    raise IOError("Timed out trying to access client! Is it connected?")
IOError: Timed out trying to access client! Is it connected?
```

**Comment by grrrrrrrrr** [comment]
I tried to fix this in https://github.com/google/grr/commit/98786545228edf8c3ecb2fa554ebf51cd1e08cb5#diff-d7104ab7e3e6c408261b0f99a9a5a402 but TBH, the fuse code is a bit outdated and could need some work, there are some crazy things happening there. Sadly, we don't have any spare cycles at this point so I just tried to work around some of the weirdnesses. Let me know if this fixes the issue for you!

**Comment by crruthe** [comment]
Thanks for taking a look.
This definitely fixes the timeout issues associated with contacting the client. The issue now is that it attempts to download large files by requesting each block, e.g.

```
Read(length=100k, offset=0)
Read(length=100k, offset=100k)
Read(length=100k, offset=200k)
Read(length=100k, offset=300k)
```

Unfortunately, this seems to be working as expected due to the abstraction for sparse files. I didn't see an obvious way to exit early when querying a large file (but I'll keep looking).

**Comment by crruthe** [comment]
I'm very new to the GRR codebase, but would `fd.Get(fd.Schema.SIZE) == 0` indicate whether we have data stored for the file or not?

**Comment by crruthe** [comment]
So I modified `GRRFuseDatastoreOnly.Read` with:

```
    if not fd.Get(fd.Schema.SIZE):
      return -errno.ENOENT
```

That seems to be working well.
