### ISSUE TITLE
Artifact Manager - dictionary changed size during iteration 

### ISSUE THREAD

**Issue by pettai** [google/grr#553]
During my tests with AdminUI.webauth_manager: RemoteUserWebAuthManager  (SSO using Shibboleth)  I stumbled on this error then I go into the Artifact Manager:

##  dictionary changed size during iteration
```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 475, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 291, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/artifact.py", line 58, in Handle
    reload_datastore_artifacts=True),
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/artifact_registry.py", line 412, in GetArtifacts
    for artifact in self._artifacts.itervalues():
RuntimeError: dictionary changed size during iteration
```

(it seems to be related to operations, like deleting a bunch of artifacts, refreshing the page etc. but it doesn't occur every time. also note that my SSO username is user@realm, not something I've seen in GRRs examples or documentation)

**Comment by grrrrrrrrr** [comment]
I assume this error happens only a single time and then disappears? This can happen when an uploaded artifact is broken for some reason and gets removed when accessed. I sent a fix to suppress the error in https://github.com/google/grr/commit/b4ca66c69ca1893b3f0de81098f637cc754aeed1 , let me know if that commit fixes it for you!

**Comment by pettai** [comment]
Seems gone, closing
thx
