### ISSUE TITLE
SSO - username with "@realm" get errors

### ISSUE THREAD

**Issue by pettai** [google/grr#555]
Then I login using SSO (using EPPN as username (format username@realm)) and go into "Start new flow", I'm getting this error:
 
## Email address 'user@scope@grr_server.domain' not well formed.
```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 475, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/http_api.py", line 291, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/flow.py", line 943, in Handle
    result.append(ApiFlowDescriptor().InitFromFlowClass(cls, token=token))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/gui/api_plugins/flow.py", line 131, in InitFromFlowClass
    self.default_args = flow_cls.GetDefaultArgs(username=token.username)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flows/general/administrative.py", line 434, in GetDefaultArgs
    email="%s@%s" % (username, config.CONFIG.Get("Logging.domain")))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 1570, in __init__
    setattr(self, arg, value)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 2200, in <lambda>
    lambda self, x: self._Set(x, field_desc), None,
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 1737, in _Set
    value = type_descriptor.Validate(value, container=self)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/structs.py", line 1422, in Validate
    value = self.type(value)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalue.py", line 208, in __init__
    self.ParseFromString(initializer)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/standard.py", line 78, in ParseFromString
    super(DomainEmailAddress, self).ParseFromString(value)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/standard.py", line 71, in ParseFromString
    raise ValueError("Email address %r not well formed." % self._value)
ValueError: Email address 'user@scope@grr_server.domain' not well formed.
```

**Comment by pettai** [comment]
Does logging domain really need to be appended?

**Comment by mbushkov** [comment]
We basically want to not append the domain if there's "@" in the username, right?
In your example - do we want to send an email to user@scope? Or is the idea not to send an email at all if there's "@" in the username?

**Comment by pettai** [comment]
EPPN in SSO is a (globally) unique user identifier, hence the @scope.
It may or may not be an valid working email-address.
So GRR should not auto-map the username to an expected working email-address (even thought it's very convenient :) (email-address should a separate setting).
(In Shibboleth SSO there is separate attribute, "mail" for the email address of the user)

So the simple fix would be not to send emails if there's a "@" in the username.
The longterm fix would be to add a configurable "mail" attribute to the user (if possible)

I can live with the simple fix...

**Comment by grrrrrrrrr** [comment]
Having a configurable email option should be pretty straightforward given we already have the admin UI flag (debug/basic/...) as a user setting, we could just extend that dialog and use the email as an override if set?!

**Comment by pettai** [comment]
That would be nice!

Will GRR always try to send email with or without "mail" attribute being present?
(with and without username containing a "@" sign.)

I'd like to default to "no" unless the (new) "mail" attribute is filled in.
I think is the sane default for applications that are capable of sending emails, 
especially those that are security-related so they don't leak information in emails by default.

But that changes the default behaviour of GRR, which others probably would hate ...

**Comment by mol123** [comment]
We've introduced custom E-Mail addresses for GRR users, so this should be fixed.

See:
https://grr-doc.readthedocs.io/en/latest/maintaining-and-tuning/email-configuration.html#custom-email-addresses
