### ISSUE TITLE
Grr MemoryCapture (aff4acquire) failure 

### ISSUE THREAD

**Issue by prats84** [google/grr#566]
GRR Version 3.2.1 
Grr Server Installed on -  Ubuntu 16.04
Memory acquired from Client : Ubuntu 16.04 

The Flow MemoryCapture fails with the below error in the UI but reviewing the files on the Client. The memory was actually dumped at /var/tmp/grr/GRR. 

The issue seems to be Network Based. Any ideas to fix this ?
=====

Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow_runner.py", line 589, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow.py", line 301, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flows/general/memory.py", line 101, in CheckAnalyzeClientMemory raise flow.FlowError("Unable to image memory: %s." % responses.status) FlowError: Unable to image memory: message GrrStatus { child_session_id : SessionID: aff4:/C.cb7d2b6ea69479c8/flows/F:EE385B51/F:AA2641F7 cpu_time_used : message CpuSeconds { system_cpu_time : 24.0099983215 user_cpu_time : 395.510070801 } error_message : u'Traceback (most recent call last):\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow_runner.py", line 589, in RunStateMethod\n direct_response=direct_response, request=request, responses=responses)\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flow.py", line 301, in Decorated\n res = f(*args[:f.func_code.co_argcount])\n File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/flows/general/memory.py", line 289, in End\n raise flow.FlowError("Error running plugins: %s" % all_errors)\nFlowError: Error running plugins: Traceback (most recent call last):\n File "grr/client/components/rekall_support/grr_rekall.py", line 278, in Run\n File "site-packages/rekall/session.py", line 862, in RunPlugin\n File "site-packages/rekall/session.py", line 859, in RunPlugin\n File "site-packages/rekall/plugin.py", line 726, in render\n File "site-packages/rekall/plugins/tools/aff4acquire.py", line 577, in collect\n File "site-packages/rekall/plugins/tools/aff4acquire.py", line 602, in collect_acquisition\n File "site-packages/rekall/plugins/tools/aff4acquire.py", line 650, in _collect_acquisition\n File "site-packages/rekall/plugins/tools/aff4acquire.py", line 530, in copy_files\n File "site-packages/rekall/plugins/tools/aff4acquire.py", line 440, in _copy_file_to_image\n File "site-packages/rekall/utils.py", line 1009, in __get__\n File "site-packages/rekall/session.py", line 1055, in profile\n File "site-packages/rekall/session.py", line 761, in GetParameter\n File "site-packages/rekall/session.py", line 796, in _RunParameterHook\n File "site-packages/rekall/plugins/guess_profile.py", line 760, in calculate\nRuntimeError: Unable to find a valid profile for this image. Try using -v for more details.\n\n' network_bytes_sent : 3893387485 status : GENERIC_ERROR }.

**Comment by mbushkov** [comment]
For every OS type Rekall deals with, it needs a special profile file (see [this article](http://blog.rekall-forensic.com/2014/02/rekall-profiles.html) for detailed information about profiles).

IIUC, you're trying to acquire memory on a Linux machine. According to the article mentioned above:

> For Linux there are so many versions, that users must build their own by compiling a kernel module in debug mode, and dumping the output of dwarfdump.

As far as I understand here's Rekall documentation on how to build a Linux profile: https://github.com/google/rekall/blob/master/tools/linux/README

Effectively you need to do this for every variation of Linux in your fleet. As this workflow is complicated and doesn't scale well, it'd be fair to say that Rekall is almost never used with GRR on Linux boxes. Consequently, IIRC, there's no easy documented way to put a custom built Linux profile into GRR datastore (and thus make it visible to GRR clients).

If you think that building Linux profiles is worthwhile for you (and if the process described in Rekall docs works), I'd be happy to make a new FAQ entry with a console snippet to upload a custom Rekall profile to GRR datastore.

**Comment by scudette** [comment]
You do not need a profile to acquire memory:

http://docs.rekall-forensic.com/en/latest/plugins.html#aff4acquire-aff4acquire

However there have been a few fixes lately in Linux memory analysis
around fixing ASLR support for newer kernels (more distributions seem
to turn on ASLR by default). This means you probably will need to use
a relatively new Rekall. I am not sure how old the GRR's version of
Rekall is but it might be too old.

**Comment by scudette** [comment]
Actually it looks like the original issue failed because the "also_mapped_files" flag was set. Maybe try to set it to False? Obviously Rekall will need a profile if you ask it to dump mapped files from memory but this flag should be off by default.

**Comment by prats84** [comment]
@scudette Yes, there is not need for a profile to acquire but it was suspicious to me on why the flow would failed in-spite of completing the capture as I  was able to access the Memory dump.

I did not realize about the also_mapped_files. Will give that a test and update.

**Comment by prats84** [comment]
also_mapped_files set to false but still the same issue.  
set the also_mapped_files the Struct directly as false.

**Comment by grrrrrrrrr** [comment]
Did this work in the end? Rekall is unsupported in GRR at this point so I'm going to close this issue. I'm happy to help though, let me know if there is anything else we can look at.
