### ISSUE TITLE
Python Errors when running when administrative commands

### ISSUE THREAD

**Issue by 666reda** [google/grr#571]
Hi,
Whatever the version or the method I use to install GRR server in my ubuntu 14.04, I keep getting Python-like errors,
In my last attemp I tried to install it using the PIP/virtualenv method, and when running `grr_console` I got this :
```
(GRR_ENV) root@reda:/home/reda# grr_console
Traceback (most recent call last):
  File "/home/reda/GRR_ENV/bin/grr_console", line 11, in <module>
    sys.exit(Console())
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/distro_entry.py", line 46, in Console
    from grr.tools import console
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/console.py", line 21, in <module>
    from grr.lib import server_plugins
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 18, in <module>
    from grr.server import server_plugins
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/server_plugins.py", line 14, in <module>
    from grr.server import export
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/export.py", line 24, in <module>
    from grr.server.aff4_objects import filestore
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/aff4_objects/filestore.py", line 19, in <module>
    from grr.server.aff4_objects import aff4_grr
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/aff4_objects/aff4_grr.py", line 10, in <module>
    from grr_response_client.components.rekall_support import rekall_types as rdf_rekall_types
ImportError: No module named grr_response_client.components.rekall_support
```

When trying  `grr_config_updater initialize` :
```
(GRR_ENV) root@reda:/home/reda# grr_config_updater initialize
Traceback (most recent call last):
  File "/home/reda/GRR_ENV/bin/grr_config_updater", line 11, in <module>
    sys.exit(ConfigUpdater())
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/distro_entry.py", line 52, in ConfigUpdater
    from grr.tools import config_updater
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/tools/config_updater.py", line 20, in <module>
    from grr.lib import server_plugins
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/lib/server_plugins.py", line 18, in <module>
    from grr.server import server_plugins
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/server_plugins.py", line 14, in <module>
    from grr.server import export
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/export.py", line 24, in <module>
    from grr.server.aff4_objects import filestore
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/aff4_objects/filestore.py", line 19, in <module>
    from grr.server.aff4_objects import aff4_grr
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/server/aff4_objects/aff4_grr.py", line 10, in <module>
    from grr_response_client.components.rekall_support import rekall_types as rdf_rekall_types
ImportError: No module named grr_response_client.components.rekall_support
```

Thank's

**Comment by grrrrrrrrr** [comment]
Hm it seems like you are mixing different GRR versions. What version of grr-response-client do you have in your virtualenv? 3.2.1post7 is current...

**Comment by 666reda** [comment]
Thank's for the fast reply,
I use the `pip install` which, AFAIK, install the current version.
I managed to get ride of some errors using `pip install <package-name>`, but I'm unable to get it work yet
```
(GRR_ENV) root@reda:~# grr_config_updater initialize
Traceback (most recent call last):
  File "/home/reda/GRR_ENV/bin/grr_config_updater", line 7, in <module>
    from grr.server.distro_entry import ConfigUpdater
  File "/home/reda/GRR_ENV/local/lib/python2.7/site-packages/grr/__init__.py", line 25, in <module>
    from urllib.request import urlopen
ImportError: No module named request
```
Also, I rely on the the [documentation](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-released-pip.html#) get install & deploy GRR, and it didn't mention that I should install `grr-response-client`, is there another resource ?

**Comment by grrrrrrrrr** [comment]
I'm pretty confused about this error. This doesn't seem to be grr code at all? We don't use urllib in any __init__.py file. The issue is that the code you are trying to run was written for Python 3 (GRR doesn't have any Python 3 code yet) and so it fails. Do you have any idea where this file comes from?

**Comment by grrrrrrrrr** [comment]
I quickly did an install on a clean Ubuntu machine (17.10). I agree that there is a bug, the server code somehow depends on the client so the install instructions do not work currently. However, after doing a

pip install grr-response-client

the server worked without any issues. I'd advise you to start over from a clean virtualenv, there is something wrong with the one you are using that has nothing to do with GRR.

**Comment by 666reda** [comment]
Your help is much appreciated @grrrrrrrrr 
do you recommend purging `python 3` and relying only on `python 2.7` ? and should I migrate also to Ubuntu 17 instead of 14.04 ?

**Comment by grrrrrrrrr** [comment]
No need to purge python3, you can have both versions installed side by side. Just makes sure that you use Python2 for actually running GRR.

I think Ubuntu 14.04 should work ok. But then, why use a distribution that old if you don't have to...

**Comment by 666reda** [comment]
Thank's a lot
