### ISSUE TITLE
How do I remove a client

### ISSUE THREAD

**Issue by KennethVanMele** [google/grr#592]
More of a question really. How do I remove clients from the UI? In my testing environment, I have a whole list of duplicates of which most are down. I bet I'm missing something obvious and don't know where else to put this.

**Comment by grrrrrrrrr** [comment]
You can't remove clients (or delete any actual data) directly from the UI. It's pretty straightforward to delete clients from the console though, I added a short example at:

https://github.com/google/grr-doc/blob/master/maintaining-and-tuning/low-level-maintenance-with-console.md

**Comment by Zakaren** [comment]
Hi, 
I think that the command lines provided in the documentation are outdated :

when i run the commandline below :
data_store.REL_DB.DeleteClient(self, u"C.83558528f50f993e")

I get the following error : 
NameError: name 'self' is not defined

Could you fix it please, or provide us with the correct command ? 

Thank you,

**Comment by grrrrrrrrr** [comment]
Hey,

you are right, the 'self' should not be there. I changed the docs, let me know if they still don't work for you...

**Comment by Zakaren** [comment]
Hi, 

Thank you for your reply, 

Unfortunately, the new commandline doesn't work either. Got the following error :  (FYI : I'm using a docker image installation)

In [2]: data_store.REL_DB.DeleteClient(u"C.XXXXXXXXX")
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/console.pyc in <module>()
----> 1 data_store.REL_DB.DeleteClient(u"C.XXXXXXXXX")

/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.pyc in DeleteClient(self, client_id)
    611     # yet. When the functionality for deleting clients is required, make sure to
    612     # delete all associated metadata (history, stats, flows, messages, ...).
--> 613     raise NotImplementedError("Deletetion of Clients is not yet implemented.")
    614
    615   @abc.abstractmethod

NotImplementedError: Deletetion of Clients is not yet implemented.

**Comment by grrrrrrrrr** [comment]
Oh sorry, you are right. We totally missed this function and haven't actually implemented it yet.

I have done this today (https://github.com/google/grr/commit/03fb57bd17f95580c3da12b60d3e5f50f178a7ba) so if you really need this functionality you can update to a nightly deb.

**Comment by knsankar** [comment]
I am getting following error when I access the dashboard after deleting a client.

Actually, the client was in "Recently accessed", I think the UI is trying to access the deleted client, hence the error.
Is there a cleaner way to do it?



Traceback (most recent call last):
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 758, in ReadClientFullInfo
    return result[client_id]
KeyError: 'C.edeae1a8cd8c4f8f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 512, in HandleRequest
    result = self.CallApiHandler(handler, args, context=context)
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 310, in CallApiHandler
    result = handler.Handle(args, context=context)
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 955, in Handle
    items = list(itertools.islice(approvals, args.offset, end))
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 658, in _FilterRelationalApprovalRequests
    client_approval = approval_create_fn(ar)
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 948, in <lambda>
    approvals, lambda ar: ApiClientApproval().InitFromDatabaseObject(ar),
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 405, in InitFromDatabaseObject
    db_obj.subject_id)
  File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 760, in ReadClientFullInfo
    raise UnknownClientError(client_id)
grr_response_server.databases.db.UnknownClientError: Client with id 'C.edeae1a8cd8c4f8f' does not exist
