### ISSUE TITLE
runlog2timeline not working

### ISSUE THREAD

**Issue by anweshm** [google/grr#612]
Unable to sort out this issue with runlog2timeline

root@ubuntu:/home/labuser# grr_console --command_file=runlog2timeline.py
No token available for access to aff4:/C.af09198401d29a7d
Processing:  /grrfuse/C.af09198401d29a7d/fs/os/C:/Windows/System32/winevt/Logs
Traceback (most recent call last):
  File "/usr/share/grr-server//bin/grr_console", line 11, in <module>
    sys.exit(Console())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/distro_entry.py", line 48, in Console
    flags.StartMain(console.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/flags.py", line 140, in StartMain
    main(sys.argv)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/bin/console.py", line 131, in main
    execfile(flags.FLAGS.command_file)
  File "runlog2timeline.py", line 24, in <module>
    RunLog2Timeline(c[0].urn, DIRS)
  File "runlog2timeline.py", line 15, in RunLog2Timeline
    subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/bin/log2timeline.py --single-thread --hashers sha256 -p /tmp/plaso/01HW.plaso "/grrfuse/C.af09198401d29a7d/fs/os/C:/Windows/System32/winevt/Logs" > /dev/null 2>&1' returned non-zero exit status 2

**Comment by grrrrrrrrr** [comment]
Friendly ping on this one. We can have a quick look if there is something obvious wrong with the script if you want but otherwise I'd like to close this issue as this is not really a GRR problem.

**Comment by grrrrrrrrr** [comment]
This issue seems to be abandoned.
