### ISSUE TITLE
Flows get Stuck in GRR 3.2.3.2

### ISSUE THREAD

**Issue by n3x77** [google/grr#627]
Hi all,

we recognized some strange behaviour of the GRR Server in Version 3.2.3.2.
After executing flows on clients, some of the flows will be executed and suddenly some of them get stuck. After deploying the debug agents on this clients we can see that the client does not receive messages from the server (find attached log). We also figure out some problems with GRR Artifact Collection when we try to use the %%users.appdatalocal%% Knowledgebase, the flow gots killed: 

`Traceback (most recent call last): File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flow_runner.py", line 587, in RunStateMethod direct_response=direct_response, request=request, responses=responses) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flow.py", line 297, in Decorated res = f(*args[:f.func_code.co_argcount]) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flows/general/collectors.py", line 128, in StartCollection self.Collect(artifact_obj) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flows/general/collectors.py", line 175, in Collect self.GetFiles(source, self.GetPathType(), self.args.max_file_size) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flows/general/collectors.py", line 226, in GetFiles ignore_errors=self.args.ignore_interpolation_errors)) File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_utils.py", line 116, in InterpolateKbAttributes e)) KnowledgeBaseInterpolationError: Failed to interpolate %%users.localappdata%%\Microsoft\Windows\UsrClass.dat with the knowledgebase. users.localappdata `

The connection between the clients and the server works well.

We're currently using the following setup: 
1x GRR-Server on Hardware:
1x HA-Proxy that distribute the Client connections between 3 GRR HTTP-Frontend server
6x Workers

GRR-Version 3.2.3.2
Datastore: Sqlite.

At the moment I have now clue what the problem is. Could you please provide some advice on debugging?

[agent.log](https://github.com/google/grr/files/2393737/issue.log)

Thx for your help.

**Comment by mbushkov** [comment]
Hi Sven,
Re localappdata: can you please check "Full Details" tab of the hosts's
"Host Information" page? In the details table there should be a "Knowledge
Base" row. Do you see any "Users" fields in this row? If yes, does any of
the "User" records have a "localappdata" field?

Given that you have an issue with flows being stuck, it may be that clients
do not finish an interrogation process properly and, as a result, don't
have a proper KnowledgeBase filled in. Without a properly filled in
KnowledgeBase artifact collection may fail with an errors that you see.

Re debugging communication issues. It would be great to exclude some weird
SQLite datastore bugs (SQLite datastore is deprecated and is going to be
removed in the next release anyway). Can you try running the server with a
MySQL server as a backend and see if that helps? (details on how to quickly
set up MySQL server can be found here:
https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html
).

Cheers,
Misha

**Comment by grrrrrrrrr** [comment]
The appdata entry in the knowledge_base is populated by the "WindowsUserShellFolders" artifact, what happens if you just run this one? Also, just to make sure, there are active users on the system you are looking at?

For the NTUSER.DAT question, do you mean the WindowsUserRegistryFiles artifact? If you are trying to collect the NTUSER.DAT file, you have to use tsk (sleuthkit). Windows will prevent GRR from opening that file via the normal file api. Have you checked the use tsk box?

**Comment by n3x77** [comment]
Hi Andreas,

collecting this files via the file finder or artifact collector using tsk
works. I am always trying to Use tsk.

The WindowsUserShellFolders Artifact gives no results in all oft the
systems. Even if there are active users in the system.

How is the vfs HKEY_Users Key populated?

I also checked that the agents are running with the appropriate rights.
They run with NTAuthority/System.

The only thing that I am trying to Figure out is if there are some strange
ACL permissions set in the user registry files so that the grr agent can
not access this files. Does the Agent Use the Windows API in the registry
finder ?

Thanks for your hell!

Andreas Moser <notifications@github.com> schrieb am Mi., 19. Sep. 2018,
18:40:

**Comment by grrrrrrrrr** [comment]
I did some more investigation on this and it seems like something is broken - I also don't get results for the artifact collector when looking at registry keys. We are going to look into this...

**Comment by n3x77** [comment]
Thank you Andreas,

If I can help with logs or Debugging just let me know.
Andreas Moser <notifications@github.com> schrieb am Mi. 19. Sep. 2018 um
21:40:

**Comment by grrrrrrrrr** [comment]
Ok it looks like our Windows box just had no active users anymore since nobody had logged in for a while. The artifact now produces the correct result.

Can you try to run a glob flow with Path HKEY_USERS\* and Pathtype REGISTRY? That should give you the contents of HKEY_USERS and you should be able to poke around there using the virtual file system.

Also, just in case, are you running any special Windows version?

**Comment by n3x77** [comment]
Hi Andreas,

So the Artifact WindowsUserShellFolders does not retrieve any artifacts. The glob flow did not show any entries in the user registry file. 

We're using a normal windows Installation. At the moment I think maybe something is blocking the access to the needed files but I am not sore. Could you please tell me in more detail which files the WindowsUserShellFolder Artifact uses and how the access is done in the grr agent?

**Comment by grrrrrrrrr** [comment]
You can get detailed descriptions of the artifacts in the collector ui. In the right pane it will have all paths the artifact will collect when you select one.

The access to the registry is done normally via the OS API, nothing special there.

Are you saying the glob flow for HKEY_USERS\\* also returns no results? Is there any data in the client vfs view under registry at all? If there are some entries there, what happens if you click the refresh from the client button? Does it come back with data?

**Comment by n3x77** [comment]
Hi the glob flow for HKEY_USERS\* returns no results. In the VFS view I can see Data from HKEY_LOCAL_MACHINE and subkeys. I can refresh the HKLM keys from there and use VFS as suggested. But for HKEY_USERS I do not get any data back.

**Comment by n3x77** [comment]
Hi Andreas,

to push this further. On a few systems I can see entries in the registry vfs view. On this systems the WindowsUserShellFolder Artifact also returns 0 results but during the Interrogate it seems that a few paths could be resolved to `HKEY_USERS\<SID>\Environment 
HKEY_USERS\<SID>\Software/Microsoft/Windows/CurrentVersion/Explorer/Shell Folders
HKEY_USERS\<SID>\Environment\Volatile Environment
`
But this entries were not saved in the knowledgebase of the system. So for me it looks like there are problems of getting the knowledgebase filled with information.
