### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by babusubrahmani** [google/grr#628]
Team,

I am facing small issue, whenever a new flow start:

Failed to interpolate %%users.homedir%%\Desktop\**5\* with the knowledgebase. 'NoneType' object has no attribute 'Get'

`Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/gui/http_api.py", line 494, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/gui/http_api.py", line 291, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/gui/api_plugins/flow.py", line 888, in Handle
    runner_args=args.flow.runner_args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flow.py", line 617, in StartFlow
    flow_obj.Start()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flow.py", line 297, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flows/general/file_finder.py", line 102, in Start
    collect_ext_attrs=action.stat.collect_ext_attrs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/server/grr_response_server/flows/general/filesystem.py", line 745, in GlobForPaths
    patterns.extend(path.Interpolate(client=client))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/rdfvalues/paths.py", line 280, in Interpolate
    for pattern in patterns:
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr/lib/artifact_utils.py", line 116, in InterpolateKbAttributes
    e))
KnowledgeBaseInterpolationError: Failed to interpolate %%users.homedir%%\Desktop\**5\* with the knowledgebase. 'NoneType' object has no attribute 'Get'`

Also, is there anyway to fetch following details at once from the remote system:

- List of installed programs (**_WMIInstalledSoftware_**)

- All files / folder names (**%%users.homedir%%\Documents\**5\***)

I tried these two commands together in 'FLOW' but no luck.

Thanks in Advance

Regards

Babu

**Comment by grrrrrrrrr** [comment]
Hey Babu,

This part of GRR has changed recently and this doesn't fail if running on HEAD. What version of GRR are you on? Is this a release version? We sent some fixes to this recently but they might not be included in the version you use.

Cheers,
-Andy

**Comment by babusubrahmani** [comment]
Dear Andy,
Thanks for your reply and FYI, problem was resolved without upgrading it. But, the client is inactive, after  upgrading through HEAD, as advised. Also earlier version was grr-server_3.2.3-2_amd64.deb and current version is 3.2.4-1. Well appreciated you and your team contribution to forensics community.

Thanks

Babu

**Comment by babusubrahmani** [comment]
Dear Andy,
Thanks for your reply and FYI, problem was resolved without upgrading it. But, the client is inactive, after  upgrading through HEAD, as advised. Also earlier version was grr-server_3.2.3-2_amd64.deb and current version is 3.2.4-1. Well appreciated you and your team contribution to forensics community.

Thanks

Regards
Babu
