### ISSUE TITLE
GRR client fails to connect to server when a FTP proxy is configured in the environment

### ISSUE THREAD

**Issue by wootski** [google/grr#631]
Hi,

We are seeing that when GRR 3.2.3.2 autodetects the system proxies and attempts to establish the connection with a FTP proxy (e.g. ftp://myftpproxy.corp) it appears to be locked in an infinite loop. See below:

```
DEBUG:2018-09-26 17:52:52,755 client_utils_windows:187] Found proxy servers: ['http://authenticatedproxy.corp:8080', 'ftp://myftpproxy.corp:8080', 'http://webproxy.corp:8080']
...
WARNING:2018-09-26 17:54:21,753 comms:1321] Uncaught exception caught: Traceback (most recent call last):
  File "site-packages\grr_response_client\comms.py", line 1318, in Run
  File "site-packages\grr_response_client\comms.py", line 1159, in RunOnce
  File "site-packages\grr_response_client\comms.py", line 1275, in _FetchServerCertificate
  File "site-packages\grr_response_client\comms.py", line 239, in OpenServerEndpoint
  File "site-packages\grr_response_client\comms.py", line 316, in OpenURL
  File "site-packages\grr_response_client\comms.py", line 380, in _RetryRequest
  File "site-packages\requests\api.py", line 53, in request
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 343, in send
  File "site-packages\requests\adapters.py", line 254, in get_connection
  File "site-packages\requests\adapters.py", line 160, in proxy_manager_for
  File "site-packages\requests\packages\urllib3\poolmanager.py", line 281, in proxy_from_url
  File "site-packages\requests\packages\urllib3\poolmanager.py", line 232, in __init__
ProxySchemeUnknown: Not supported proxy scheme ftp
...
WARNING:2018-10-09 08:10:22,989 comms:1321] Uncaught exception caught: Traceback (most recent call last):
  File "site-packages\grr_response_client\comms.py", line 1318, in Run
  File "site-packages\grr_response_client\comms.py", line 1159, in RunOnce
  File "site-packages\grr_response_client\comms.py", line 1275, in _FetchServerCertificate
  File "site-packages\grr_response_client\comms.py", line 239, in OpenServerEndpoint
  File "site-packages\grr_response_client\comms.py", line 316, in OpenURL
  File "site-packages\grr_response_client\comms.py", line 380, in _RetryRequest
  File "site-packages\requests\api.py", line 53, in request
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 343, in send
  File "site-packages\requests\adapters.py", line 254, in get_connection
  File "site-packages\requests\adapters.py", line 160, in proxy_manager_for
  File "site-packages\requests\packages\urllib3\poolmanager.py", line 281, in proxy_from_url
  File "site-packages\requests\packages\urllib3\poolmanager.py", line 232, in __init__
ProxySchemeUnknown: Not supported proxy scheme ftp
```

The relevant code for this appears to be in grr/client/grr_response_client/comms.py line #1267, the error appears in the client log as it retries more than 500 times to make this connection, but the client never moves through the list of additional proxies that were found.

**Comment by grrrrrrrrr** [comment]
Yeah this is indeed a bug, we did not anticipate this exception. We'll send a fix shortly, thanks for the report!

**Comment by grrrrrrrrr** [comment]
This is now fixed in https://github.com/google/grr/commit/07155aa89cac4b9c6769657932b95d5211fa5ddb
