### ISSUE TITLE
Collect client IDs for a given hostname

### ISSUE THREAD

**Issue by Shubham-gupta007** [google/grr#636]
Traceback (most recent call last):
  File "clientid.py", line 5, in <module>
    search_result = grrapi.SearchClients("host:192.168.110.166")
  File "/home/ubuntu/grr/api_client/python/grr_api_client/api.py", line 28, in SearchClients
    return client.SearchClients(query, context=self._context)
  File "/home/ubuntu/grr/api_client/python/grr_api_client/client.py", line 267, in SearchClients
    items = context.SendIteratorRequest("SearchClients", args)
  File "/home/ubuntu/grr/api_client/python/grr_api_client/context.py", line 52, in SendIteratorRequest
    first_page = pages.next()
  File "/home/ubuntu/grr/api_client/python/grr_api_client/context.py", line 35, in _GeneratePages
    result = self.connector.SendRequest(handler_name, args_copy)
  File "/home/ubuntu/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 245, in SendRequest
    self._InitializeIfNeeded()
  File "/home/ubuntu/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 136, in _InitializeIfNeeded
    self.csrf_token = self._GetCSRFToken()
  File "/home/ubuntu/grr/api_client/python/grr_api_client/connectors/http_connector.py", line 70, in _GetCSRFToken
    cert=self.cert)
  File "/home/ubuntu/GRR_NEW/local/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/GRR_NEW/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/GRR_NEW/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/GRR_NEW/local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ubuntu', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f376af59710>: Failed to establish a new connection: [Errno 111] Connection refused',))
Collect client IDs for a given hostname

>>clientid.py
from grr_api_client import api
grrapi = api.InitHttp(api_endpoint="http://ubuntu:8000",
                      auth=("admin", "qwerty"))

search_result = grrapi.SearchClients("host:192.168.110.166")
result = {}
for client in search_result:
  client_id = client.client_id
  client_last_seen_at = client.data.last_seen_at
  result[client_id] = client_last_seen_at
print result

I do installation from GRR API client library only.
should i also install https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-released-pip.html
this thing?
thanks in advance.

-

**Comment by mbushkov** [comment]
To talk to the server you only need to install grr-api-client, no other packages are necessary.
It seems that grr-api-client can't reach your server. What happens if you try to use CURL to connect to the same endpoint?

Something like:
```bash
curl -u admin:qwerty "http://ubuntu:8000/api/v2/clients?query=host:192.168.110.166"
```

**Comment by grrrrrrrrr** [comment]
Given the long inactivity on this issue I'd say it's obsolete and close here. Please reopen if we can still help with something.
