### ISSUE TITLE
GRR windows clients 3.2.3.2+ stuck in Manage launched flows view

### ISSUE THREAD

**Issue by pettai** [google/grr#638]
GRR Server 3.2.3.2+
Seems to only hit windows agents 3.2.3.2+

Then looking at a clients "Manage launched flows", it get stuck in "Loading..."
 and the following error appears in the system log: 

Oct 29 16:15:24 MyGRRR grr_server[64079]: 127.0.0.1 - - [29/Oct/2018 16:15:24] "GET /api/clients/C.a3a0b90baba297e4/flows?count=100&offset=0 HTTP/1.1" 200 4889242
Oct 29 16:15:24 MyGRRR grr_server[64079]: Traceback (most recent call last):
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.finish_response()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.write(data)
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.send_headers()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.send_preamble()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
Oct 29 16:15:24 MyGRRR grr_server[64079]:     'Date: %s\r\n' % format_date_time(time.time())
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/socket.py", line 328, in write
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.flush()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Oct 29 16:15:24 MyGRRR grr_server[64079]: error: [Errno 32] Broken pipe
Oct 29 16:15:24 MyGRRR grr_server[64079]: 127.0.0.1 - - [29/Oct/2018 16:15:24] "GET /api/clients/C.a3a0b90baba297e4/flows?count=100&offset=0 HTTP/1.1" 500 59
Oct 29 16:15:24 MyGRRR grr_server[64079]: Traceback (most recent call last):
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.finish_request(request, client_address)
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.RequestHandlerClass(request, client_address, self)
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.finish()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.wfile.close()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self.flush()
Oct 29 16:15:24 MyGRRR grr_server[64079]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Oct 29 16:15:24 MyGRRR grr_server[64079]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Oct 29 16:15:24 MyGRRR grr_server[64079]: error: [Errno 32] Broken pipe

Note that this seems true for "Manage Binaries" view too...

**Comment by pettai** [comment]
this was a red herring, it was a proxy timeout issue.
