### ISSUE TITLE
Interrogate fails on Windows client machine (not English UI/Localization)

### ISSUE THREAD

**Issue by mmogilko** [google/grr#653]
Hello!

I have an error with default interrogate flows on all non-english UI windows clients. Maybe, there should be `decode('utf-8')` or `encoding='utf-8'` strings in code? 
GRR Server: 3.2.4-5
GRR Client: 3.2.3.2
Backtrace:

```
Traceback (most recent call last):  
 File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_runner.py", line 568, in RunStateMethod method(responses)  
 File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flows/general/discovery.py", line 299, in ProcessKnowledgeBase client_index.CreateClientIndex(token=self.token).AddClient(client)  
 File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/client_index.py", line 269, in AddClient client_id, keywords = self.AnalyzeClient(client)  
 File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/client_index.py", line 222, in AnalyzeClient TryAppend("user", user.username)  
 File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/client_index.py", line 183, in TryAppend keywords.append(prefix + ":" + keyword_string) UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)  
```

Thanks in advance!

**Comment by mbushkov** [comment]
@mmogilko - thanks for reporting the issue! I think the bug should be fixed now (https://github.com/google/grr/commit/a868278abbd0e4e2d2ef03f1189ba9b6c57f63ee).
Can you please upgrade to the latest build I did in HEAD (https://storage.googleapis.com/autobuilds.grr-response.com/_latest_server_deb/grr-server_3.2.4-6_amd64.deb) and see if the error goes away?

**Comment by mmogilko** [comment]
@mbushkov - thanks a lot! It is fixed now.
Have a nice evening!
