### ISSUE TITLE
docker_image_install_fails

### ISSUE THREAD

**Issue by siftuser** [google/grr#667]
**OS:** Ubuntu 18.04.1 LTS

**commad =>** docker run   --name grr-server   -e EXTERNAL_HOSTNAME="localhost"   -e ADMIN_PASSWORD="demo"   -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 grrdocker/grr:latest 

**Error:**
Status: Downloaded newer image for grrdocker/grr:latest
 * Starting MySQL database server mysqld
   ...done.
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 11, in <module>
    load_entry_point('grr-response-server==3.2.4.post7', 'console_scripts', 'grr_config_updater')()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 23, in ConfigUpdater
    from grr_response_server.bin import config_updater
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 18, in <module>
    from grr_response_server import server_plugins
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_plugins.py", line 18, in <module>
    from grr_response_server import export
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/export.py", line 34, in <module>
    from grr_response_server import aff4
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/aff4.py", line 41, in <module>
    from grr_response_server import data_store
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/data_store.py", line 73, in <module>
    from grr_response_server.databases import registry_init
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/registry_init.py", line 20, in <module>
    from grr_response_server.databases import mysql
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 51, in <module>
    mysql_error_constants.TOO_MANY_CONCURRENT_TRXS,
AttributeError: 'module' object has no attribute 'TOO_MANY_CONCURRENT_TRXS'

**Comment by demonchild2112** [comment]
This is a bug that has been fixed in https://github.com/google/grr/commit/0abb895bb0a1f0c030807b768bd1bd9746cd9fa2.

The latest image should be working now.
