### ISSUE TITLE
The GRR server's handling of misnamed config options needs to be more user friendly

### ISSUE THREAD

**Issue by demonchild2112** [google/grr#671]
Currently, if an unrecognized config option is provided in the writeback file, restarting the GRR server components causes the writeback to be renamed by attaching a '.bak' suffix. In addition, a new empty writeback gets created. After this happens though, the server components cannot start, because the writeback is not initialized:

```text
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_console", line 11, in <module>
    sys.exit(Console())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 14, in Console
    flags.StartMain(console.main)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/flags.py", line 147, in StartMain
    main(sys.argv)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/console.py", line 107, in main
    server_startup.Init()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_startup.py", line 88, in Init
    raise RuntimeError("Config not initialized, run \"grr_config_updater"
RuntimeError: Config not initialized, run "grr_config_updater initialize". If the server is already configured, add "Server.initialized: True" to your config.
```

**Comment by mbushkov** [comment]
The issue is caused by the fact that we share the configuration code between GRR server and GRR client. This defensive/silent behavior kind of makes sense for the client - it has to be resilient against potential misconfiguration errors or version incompatibilities (when a client runs against a config with an already deprecated option). For the server, however, this doesn't make any sense. We have to ensure that the server fails early and provides a clear error message.

**Comment by alexandrucosminmihai** [comment]
Hello!

I investigated this issue, but had problems reproducing it. 
Looking at the code I found out that the writeback file gets parsed and its options are verified when calling the following chain of methods of `GrrConfigManager`: `SetWriteBack` -> `LoadSecondaryConfig` -> `MergeData`.

Inside `MergeData`, when an unknown option is found, a `MissingConfigDefinitionError` is raised if the `disallow_missing_config_definitions` flag is set, otherwise the option gets added as is to the `raw_data` OrderedDict and is pretty much ignored afterwards, I believe.

The `MissingConfigDefinitionError` is caught inside [`SetWriteBack`][1] and, if the `rename_invalid_writeback` argument is True, the writeback file gets renamed. Either way, **the exception is propagated** at the end of the try-except block and it contains a description message with the name of the faulty option. So, if both server components and clients are run with the `disallow_missing_config_definitions` flag, the desired behavior can be obtained by using different values for `rename_invalid_writeback`.

I discovered that, when starting server components, the `rename_invalid_writeback` argument is set to False in [`grr_response_server/server_setup.py`][2] and thanks to it, if an unknown option is present in the writeback file, trying to start server components multiple times consecutively will raise the same `MissingConfigDefinitionError` which indicates the problematic option. This works thanks to the fact that the writeback file does not get renamed with a `.bak` extension, therefore not causing any problems related to not finding the writeback file.

I looked at the [git history][3] and it seems like the **issue was fixed** by @ogarod and now everything works as desired (?)
Is this correct or did I miss something?

Thank you! 


[1]: https://github.com/google/grr/blob/eb0ca58ffa6f561ec61cf4253893392fd492f425/grr/core/grr_response_core/lib/config_lib.py#L799
[2]: https://github.com/google/grr/blob/eb0ca58ffa6f561ec61cf4253893392fd492f425/grr/server/grr_response_server/server_startup.py#L73
[3]: https://github.com/google/grr/commit/a4e4179d9be01d0c85af9fbf0c94ccfb5f42c665#diff-1387339ecf2298fce3baded7e2194f21R78

**Comment by mbushkov** [comment]
@alexandrucosminmihai , thank you for investigating this and for such a detailed summary! 

Quick question: `disallow_missing_config_definitions` is set to `False` by default, as defined here: https://github.com/google/grr/blob/b2969c7ed6f5c6e62919fa66625d992e7b5e0b34/grr/core/grr_response_core/lib/config_lib.py#L56

Is this flag turned on by default for server components? I.e. if we have a clean vanilla GRR deployment and make a mistake in the secondary config, would the exception get propagated and reported correctly or ignored?

**Comment by alexandrucosminmihai** [comment]
@mbushkov I believe `disallow_missing_config_definitions` flag is set to True for server components (and the exception gets propagated) :
- for Debian deployment here:
https://github.com/google/grr/blob/eb0ca58ffa6f561ec61cf4253893392fd492f425/debian/grr-server%40.service#L15

- for Docker deployment here:
https://github.com/google/grr/blob/eb0ca58ffa6f561ec61cf4253893392fd492f425/docker/docker-entrypoint.sh#L9-L12

Please correct me if I'm wrong or if there are more deployment ways where the flag should be set.

**Comment by ogarod** [comment]
Everything Alex says is correct. Importantly - this issue should be closed; I forgot to do so when I submitted the fix.

**Comment by mbushkov** [comment]
@alexandrucosminmihai - you're absolutely right. Thanks for the context!

I think the current approach works, however, I think we can improve it a bit. Fundamentally, right now a behavior that seems to be the most intuitive (raise errors) has to be explicitly turned on by the flag. Whereas, the opposite, less intuitive behavior (ignore errors) is the default for the server components. This seems to be suboptimal, especially given that the users might launch GRR server binaries with a different set of command line options.

Would it make sense to alter `grr_response_server/server_setup.py` to set `disallow_missing_config_definitions` to `False`, just as it's done for `rename_invalid_writeback`? This way we'd also be able to simplify the config files that you referenced in your previous comments by removing the explicit `--disallow_missing_config_definitions` argument.

**Comment by panhania** [comment]
Since negative flags with true value as default are counter-intuitive (at least for me), I would also suggest renaming the flag to `--allow_missing_config_definitions` and reverse the behaviour.

**Comment by mbushkov** [comment]
@panhania - it's a valid point. However, this flag has a default true value for server components and a default false value for the client component. If `allow_missing_config_definitions` flag is introduced, you'll end up in the opposite situation: it will have to default to True on the clients and to False on the server components. While this would be an improvement, I'm not sure it's worth it, given that it's one of the rare command line flags that's actually widely used (because of how Docker and GRR service files are written) - so the change would either require everybody to migrate or us to support both flags at the same time for a while.

At the very least I'd keep 2 issues separate: renaming the flag and ensuring the reasonable default behavior on server/client components.
