### ISSUE TITLE
Client hang when running chrome and firefox web cache flows

### ISSUE THREAD

**Issue by GalacticMaster** [google/grr#682]
Hi Guys,

We really love GRR and we have been using it for quite some time but we have hit a problem we are struggling to resolve.  

Clients appears to semi consistently hang when running the chrome and Firefox web cache flows (This doesn’t happen with IE)

We have seen this issue inconsistently in version 3.2.3.2 and consistently in version 3.2.4.6 (we are testing this version and this is on a small number of clients for now). 

- It happened in both the normal and debug version of the client.
- Happens on both windows 7 and windows 10.
- We can’t find anything definitively in either the client or server logs which would explain the issue.
- We have tried
  - Both TSK and OS have the same results.
  - Running the flows without dependency have the same results.
  - Running the flows with and without ignore interpolation errors have same results. 
- Each time the client hangs
  - The client is still able to communicate with server but will not accept any new flows.
  - Restarting the client results in it processing the new flows.
  - Each time it’s hang all the current requests are transfer buffer.

Here is a case of file not found message, we are not sure if this is the cause of the issue or something legitimately comes when file do not exist. We see lots of this errors.

```
DEBUG:2019-04-02 11:00:14,368 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 616
INFO:2019-04-02 11:00:14,371 comms:1203] aff4:/C.4d6c390b748803fe: Sending 0(634), Received 0 messages in 0.364999771118 sec. Sleeping for 5.0 sec.
INFO:2019-04-02 11:00:15,457 actions:167] Job Error (Find): File not found: message PathSpec {
 nested_path :   message PathSpec {
     nested_path :   message PathSpec {
         nested_path :   message PathSpec {
             nested_path :   message PathSpec {
                 nested_path :   message PathSpec {
                     nested_path :   message PathSpec {
                         nested_path :   message PathSpec {
                             path : u'User Data'
                             path_options : CASE_INSENSITIVE
                             pathtype : TSK
                            }
                         path : u'Chrome SxS'
                         path_options : CASE_INSENSITIVE
                         pathtype : TSK
                        }
                     path : u'Google'
                     path_options : CASE_INSENSITIVE
                     pathtype : TSK
                    }
                 path : u'Local'
                 path_options : CASE_INSENSITIVE
                 pathtype : TSK
                }
             path : u'AppData'
             path_options : CASE_INSENSITIVE
             pathtype : TSK
            }
         path : u'username'
         path_options : CASE_INSENSITIVE
         pathtype : TSK
        }
     path : u'Users'
     path_options : CASE_INSENSITIVE
     pathtype : TSK
    }
 path : u'C:\\'
 path_options : CASE_INSENSITIVE
 pathtype : TSK
}
DEBUG:2019-04-02 11:00:19,380 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:00:19,915 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 616
```

Another example of different file not found message.

```
DEBUG:2019-04-02 11:00:47,443 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:00:47,821 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 616
INFO:2019-04-02 11:00:47,823 comms:1203] aff4:/C.4d6c390b748803fe: Sending 2(1019), Received 0 messages in 0.380000114441 sec. Sleeping for 0.2 sec.
INFO:2019-04-02 11:00:47,979 actions:167] Job Error (Find): File not found: message PathSpec {
 mount_point : u'C:'
 nested_path :   message PathSpec {
     inode : 288502
     nested_path :   message PathSpec {
         path : u'GPUCache'
         path_options : CASE_INSENSITIVE
         pathtype : TSK
        }
     path : u'/Users/usnername/AppData/Local/Google/Chrome/User Data/BrowserMetrics'
     path_options : CASE_LITERAL
     pathtype : TSK
    }
 path : u'/\\\\?\\Volume{1dca11ef-0000-0000-0000-401f00000000}'
 path_options : CASE_LITERAL
 pathtype : OS
}
```

An I/O errors encountered, that happen when using TSK drivers. We have seen this error only once so may not be related.
 
```
INFO:2019-04-02 11:04:39,266 comms:1203] aff4:/C.4d6c390b748803fe: Sending 448(18333), Received 224 messages in 5.60600018501 sec. Sleeping for 0.2 sec.
DEBUG:2019-04-02 11:04:39,529 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:04:46,513 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 6201
INFO:2019-04-02 11:04:46,536 comms:1203] aff4:/C.4d6c390b748803fe: Sending 574(22941), Received 287 messages in 6.98799991608 sec. Sleeping for 0.2 sec.
INFO:2019-04-02 11:04:46,703 actions:167] Job Error (HashFile): IOError(u'/Users/username/AppData/Local/Google/Chrome/User Data/Default/Cache/f_097dd5 is not a file.',): /Users/username/AppData/Local/Google/Chrome/User Data/Default/Cache/f_097dd5 is not a file.
DEBUG:2019-04-02 11:04:46,703 actions:170] Traceback (most recent call last):
  File "site-packages\grr_response_client\actions.py", line 143, in Execute
  File "site-packages\grr_response_client\client_actions\standard.py", line 151, in Run
  File "site-packages\grr_response_client\client_utils_common.py", line 251, in HashFile
  File "site-packages\grr_response_core\lib\utils.py", line 58, in Wrapped
  File "site-packages\grr_response_client\vfs_handlers\sleuthkit.py", line 271, in Read
IOError: /Users/username/AppData/Local/Google/Chrome/User Data/Default/Cache/f_097dd5 is not a file.

DEBUG:2019-04-02 11:04:46,861 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:04:52,673 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 4985
INFO:2019-04-02 11:04:52,688 comms:1203] aff4:/C.4d6c390b748803fe: Sending 445(18589), Received 223 messages in 5.81299996376 sec. Sleeping for 0.2 sec.
DEBUG:2019-04-02 11:04:52,948 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:04:59,848 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 3993
INFO:2019-04-02 11:04:59,859 comms:1203] aff4:/C.4d6c390b748803fe: Sending 571(23245), Received 164 messages in 6.90299987793 sec. Sleeping for 0.2 sec.
DEBUG:2019-04-02 11:05:00,105 connectionpool:205] Starting new HTTP connection (1): xxxx:80
DEBUG:2019-04-02 11:05:05,289 connectionpool:393] http://xxxx:80 "POST /control?api=3 HTTP/1.1" 200 616
```

Any help you guys can provide in troubleshoot this will be massively appreciated as we are completely stuck. We have tried everything we can think of.

**Comment by grrrrrrrrr** [comment]
There used to be an issue with those exact flows since they generate so many responses but we fixed them a while back. Is this still a problem?
