### ISSUE TITLE
Python API fails on a call to /api/v2/reflection/api-methods with "Can not find message descriptor by type_url: type.googleapis.com/ApiListApproverSuggestionsArgs"

### ISSUE THREAD

**Issue by atkinsj** [google/grr#685]
This is a strange issue. GRR 3.2.4.5.

`curl -v http://localhost:8000/api/v2/reflection/api-methods` results in this:

```* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/v2/reflection/api-methods HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Tue, 23 Apr 2019 18:02:06 GMT
< Server: WSGIServer/0.1 Python/2.7.12
< Content-Type: application/json; charset=utf-8
< Content-Length: 221603
< Content-Disposition: attachment; filename=response.json
< X-Content-Type-Options: nosniff
< X-API-Method: ListApiMethods
< X-No-Log: True
< Set-Cookie: csrftoken=$ATOKEN; Expires=Wed, 24-Apr-2019 04:02:06 GMT; Max-Age=36000; Path=/
< 
)]}'
{"items": [{"category":
```

note the `)]}'` returned as the first 4 bytes of the response. This breaks the GRR Python API client because it can't parse the return. If I use the raw API shell, it seems to succeed.

Any idea what's going on here?

**Comment by mbushkov** [comment]
`)]}'` symbols are used intentionally, it's a XSSI protection. See [this link](https://security.stackexchange.com/questions/110539/how-does-including-a-magic-prefix-to-a-json-response-work-to-prevent-xssi-attack) for more details.

grr_api_client ignores these characters (see [this line](https://github.com/google/grr/blob/master/api_client/python/grr_api_client/connectors/http_connector.py#L37) and [this line](https://github.com/google/grr/blob/master/api_client/python/grr_api_client/connectors/http_connector.py#L107) in GRR API client code).

You mention that these characters break the GRR Python API client. Can you paste some sample code and a traceback?

**Comment by atkinsj** [comment]
Ah, duh! I assumed that's what the issue was. Here's a traceback from the API client:

```
Traceback (most recent call last):
  File "grr_export.py", line 32, in <module>
    search_result = grrapi.SearchClients("host:blah")
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/api.py", line 28, in SearchClients
    return client.SearchClients(query, context=self._context)
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/client.py", line 267, in SearchClients
    items = context.SendIteratorRequest("SearchClients", args)
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/context.py", line 52, in SendIteratorRequest
    first_page = pages.next()
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/context.py", line 35, in _GeneratePages
    result = self.connector.SendRequest(handler_name, args_copy)
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/connectors/http_connector.py", line 245, in SendRequest
    self._InitializeIfNeeded()
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/connectors/http_connector.py", line 138, in _InitializeIfNeeded
    self._FetchRoutingMap()
  File "/usr/local/lib/python2.7/site-packages/grr_api_client/connectors/http_connector.py", line 112, in _FetchRoutingMap
    json_format.Parse(json_str, proto, ignore_unknown_fields=True)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse items field: Failed to parse argsTypeDescriptor field: Failed to parse default field: Can not find message descriptor by type_url: type.googleapis.com/ApiListApproverSuggestionsArgs..
```

**Comment by mbushkov** [comment]
Thanks for the traceback and for the output sample!

Which grr-api-client version are you using? (you can run `pip freeze` to output that)

**Comment by atkinsj** [comment]
Aha, I upgraded the server to 3.2.4.6 but didn't think about the Python library. I was running:

```grr-api-client==3.2.4.post3
grr-response-proto==3.2.4.post3```

upgrading to `grr-api-client-3.2.4.post6` resolved it.

Thanks for the handholding. ;)

**Comment by mbushkov** [comment]
Sure, glad I could help :)
We should output a warning message in the grr-api-client if we detect a newer server version (created an issue for this: https://github.com/google/grr/issues/686).
