### ISSUE TITLE
3.3

### ISSUE THREAD

**Issue by eulmatxlm** [google/grr#708]

**Comment by eulmatxlm** [comment]
Context:

- fresh installed mysql database (5.7) on a remote server (Ubuntu 18.04LTS)
- privileges granted to grr user with **GRANT ALL ON grr.* TO 'grr'@'%';**

When trying to install the new 3.3.0.0 version on a Ubuntu 18.04LTS from the provided package, the error below is encountered.

Could you please clarify why oh why we need now to grant such privileges to grr clients?
thanks...

> Writing configuration to /etc/grr//server.local.yaml.
I0531 14:10:59.088855 139980464236352 config_lib.py:490] Writing back configuration to file /etc/grr//server.local.yaml
Initializing the datastore.
I0531 14:10:59.268388 139980464236352 server_logging.py:186] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 10, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 24, in ConfigUpdater
    config_updater.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 412, in Run
    app.run(main, flags_parser=lambda argv: parser.parse_args(argv[1:]))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 303, in main
    token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater_util.py", line 554, in Initialize
    prompt=True)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater_util.py", line 473, in FinalizeConfigInit
    server_startup.Init()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_startup.py", line 91, in Init
    registry.Init()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/registry.py", line 306, in Init
    InitHook().Init(skip_set)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/registry.py", line 272, in Init
    self._RunAllHooks(executed_hooks, skip_set)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/registry.py", line 261, in _RunAllHooks
    self._RunSingleHook(hook_cls, executed_hooks)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/registry.py", line 244, in _RunSingleHook
    cls_instance.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/data_store.py", line 1592, in Run
    REL_DB = db.DatabaseValidationWrapper(cls())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 466, in __init__
    _SetupDatabase(**self._connect_args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 291, in _SetupDatabase
    ca_cert_path=ca_cert_path)) as conn:
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 382, in _Connect
    _SetPacketSizeForFollowingConnections(cursor)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 181, in _SetPacketSizeForFollowingConnections
    _SetGlobalVariable("max_allowed_packet", MAX_PACKET_SIZE, cursor)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 90, in _SetGlobalVariable
    cursor.execute("SET GLOBAL {}=%s".format(name), [value])
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.OperationalError: (1227, 'Access denied; you need (at least one of) the SUPER privilege(s) for this operation')
dpkg: error processing package grr-server (--configure):
 installed grr-server package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 grr-server

**Comment by mbushkov** [comment]
At the moment GRR is sensitive to the `max_allowed_packet` setting. If it's lower than 20971520 bytes, GRR tries to set the `max_allowed_packet` value itself (see https://github.com/google/grr/blob/master/grr/server/grr_response_server/databases/mysql.py#L177).

Effectively, there are 2 ways to fix the issue:
1. Increase the value of the `max_allowed_packet` in your DB settings.
2. Grant GRR SUPER privileges necessary to set global variables, so that GRR can set the global variable itself. Whether it's a reasonable idea (security wise) or not depends on how your deployment is structured.

**Comment by eulmatxlm** [comment]
Oki, thanks for the quick reply :)

Would it be possible to amend the documentation (release note) with this?
And maybe get a more explicit error for non-dev .....

**Comment by mbushkov** [comment]
Sure! Will do that.

**Comment by mari0d-grab** [comment]
Hello, I'm trying to use Amazon RDS as a datastore, but RDS does not allow granting of SUPER privs. I am able to set max_allowed_packet however - is there anyway I can move forward with my install without the SUPER privs?

**Comment by mbushkov** [comment]
@mari0d-grab - if you set the `max_allowed_packet` to a value higher than 20971520 bytes, GRR should start fine without SUPER privs.

Another thing to keep an eye on is this: your `binlog_format` has to be "MIXED" or "ROW". I'm not sure what's the default setting for the Amazon RDS is.

**Comment by mari0d-grab** [comment]
@mbushkov GRR did indeed start fine without SUPER once I bumped max_allowed_packet. The RDS parameter group I'm using doesn't expose binlog_format for some reason, but everything seems to be working fine (in a testing environment anyways...).

**Comment by mari0d-grab** [comment]
I did however get a SUPER-related error when I repackaged my clients:
`root@grr-5ff7759558-gt7lh:/# grr_config_updater set_var Client.server_urls http://<redacted>/
I0702 05:12:15.164561 140084871976704 server_logging.py:186] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Setting Client.server_urls to http://internal-a35d64be49c7411e9be9f067fcd48692-1155096962.ap-southeast-1.elb.amazonaws.com:8080/
(grr-server) root@grr-5ff7759558-gt7lh:/# grr_config_updater repack_clients
I0702 05:12:20.063663 139683642664704 server_logging.py:186] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_amd64.exe.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Windows', u'Target:Windows', u'Target:Windows'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/GRR_3.3.0.3_amd64.exe
Repacking as debug installer: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_amd64.exe.zip.
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_amd64.exe.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Windows', u'Target:Windows', u'Target:Windows', u'DebugClientBuild Context'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/dbg_GRR_3.3.0.3_amd64.exe
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_i386.exe.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Windows', u'Target:Windows', u'Target:Windows'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/GRR_3.3.0.3_i386.exe
Repacking as debug installer: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_i386.exe.zip.
Repacking template: /usr/share/grr-server/grr-response-templates/templates/GRR_3.3.0.3_i386.exe.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Windows', u'Target:Windows', u'Target:Windows', u'DebugClientBuild Context'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/dbg_GRR_3.3.0.3_i386.exe
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.3_amd64.deb.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Linux', u'Target:Linux', u'Target:LinuxDeb', u'Target:Linux'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/grr_3.3.0.3_amd64.deb
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.3_amd64.rpm.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Linux', u'Target:Linux', u'Target:LinuxRpm', u'Target:Linux'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/grr_3.3.0.3_amd64.rpm
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.3_amd64.xar.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Darwin', u'Target:Darwin', u'Target:Darwin'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/grr_3.3.0.3_amd64.pkg
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.3_i386.deb.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Linux', u'Target:Linux', u'Target:LinuxDeb', u'Target:Linux'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/grr_3.3.0.3_i386.deb
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.3_i386.rpm.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:i386', u'Platform:Linux', u'Target:Linux', u'Target:LinuxRpm', u'Target:Linux'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/grr_3.3.0.3_i386.rpm
Exception in thread DataStore flusher thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/utils.py", line 131, in run
    self.target(*self.args, **self.kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/utils.py", line 85, in NewFunction
    return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/data_stores/mysql_advanced_data_store.py", line 508, in Flush
    super(MySQLAdvancedDataStore, self).Flush()
TypeError: super() argument 1 must be type, not None`

No noticeable effect though - clients successfully repackaged and are available via the admin UI. Testing on new build hosts with the newly repackaged clients worked as expected.

**Comment by grrrrrrrrr** [comment]
This is just the interpreter shutting down, confusing a background thread. Not related to the issue here at all.

**Comment by grrrrrrrrr** [comment]
This is just the interpreter shutting down, confusing a background thread. Not related to the issue here at all.
