### ISSUE TITLE
Stability issues under 3.3.0.0 on REL_DB

### ISSUE THREAD

**Issue by atkinsj** [google/grr#712]
Hi all,

Details a little light as I'm not sure the best way to troubleshoot this.

I'm getting `A server error occurred.  Please contact the administrator.` served up sporadically on the GRR Admin web server. This started happening in this specific case on Friday afternoon, the 7th, and the log lines switch like so:

```
::ffff:$internal_ip - - [07/Jun/2019 19:53:42] "GET /api/users/me/notifications/pending/count HTTP/1.1" 200 21
::ffff:$internal_ip - - [07/Jun/2019 19:54:16] "GET / HTTP/1.1" 403 63
```

This log line appears sporadically over the next two days until I noticed that the admin interface is down:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 40, in <lambda>
    return update_wrapper(lambda *a: f(*a)(*a[-2:]), f)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/wsgiapp.py", line 325, in __call__
    return endpoint(request)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/webauth.py", line 269, in Wrapper
    return WEBAUTH_MANAGER.SecurityCheck(func, request, *args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/webauth.py", line 187, in SecurityCheck
    return func(request, *args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/wsgiapp.py", line 168, in Wrapper
    server_logging.LOGGER.LogHttpAdminUIAccess(request, response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_logging.py", line 72, in LogHttpAdminUIAccess
    data_store.REL_DB.WriteAPIAuditEntry(entry)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 3273, in WriteAPIAuditEntry
    return self.delegate.WriteAPIAuditEntry(entry)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 526, in _RunInTransaction
    connection.rollback()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 136, in rollback
    self.con.rollback()
OperationalError: (2006, 'MySQL server has gone away')
```

We're running 3.3.0.0 as a Docker image with admin instances running as `/bin/bash /usr/src/grr/scripts/docker-entrypoint.sh grr admin_ui`.

We have two load balanced behind an AWS ALB with Nginx acting as a SAML SSO reverse proxy in-front of them.  I've established that the issues we're having happen even if we remove the SSO reverse proxy and hit the admin interface directly.

Any ideas on how to proceed or what might be happening here? A bounce of the service seems to resolve the issue and then it repapears a few days later. Frontend/workers seem to be functioning, although hard to validate for sure. `grr_console` and the GRR API are also throwing errors while this is happening.

**Comment by atkinsj** [comment]
Turns out the frontend instances are dying as well but maybe unrelated? Is there a way to make e-mail notifications optional and fail quietly?

```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 208, in do_POST
    self.Control()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 55, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 33, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 269, in Control
    request_comms, responses_comms)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 55, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 33, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/frontend_lib.py", line 400, in HandleMessageBundles
    self.ReceiveMessages(source, messages)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/frontend_lib.py", line 638, in ReceiveMessages
    return self.ReceiveMessagesRelationalFlows(client_id, messages)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/frontend_lib.py", line 617, in ReceiveMessagesRelationalFlows
    "ClientCrash", crash_details, token=self.token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/events.py", line 51, in PublishEvent
    cls.PublishMultipleEvents({event_name: [msg]}, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/events.py", line 76, in PublishMultipleEvents
    event_cls().ProcessMessages(messages, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flows/general/administrative.py", line 229, in ProcessMessages
    is_html=True)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/email_alerts.py", line 153, in SendEmail
    (config.CONFIG["Worker.smtp_server"], e))
RuntimeError: Could not connect to SMTP server to send email. Please check config option Worker.smtp_server. Currently set to localhost. Error: [Errno 99] Cannot assign requested address
ERROR:2019-06-05 04:05:41,173 12 MainProcess 139746256860928 Thread-47411 frontend:214] Had to respond with status 500.
```

**Comment by atkinsj** [comment]
Further hint in the worker logs, any idea how this could be happening?

```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/foreman.py", line 87, in _RunAction
    hunt.StartHuntFlowOnClient(client_id, rule.hunt_id)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/hunt.py", line 422, in StartHuntFlowOnClient
    parent_hunt_id=hunt_id)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow.py", line 499, in StartFlow
    flow_obj.FlushQueuedMessages()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/flow_base.py", line 661, in FlushQueuedMessages
    data_store.REL_DB.WriteFlowRequests(self.flow_requests)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 3510, in WriteFlowRequests
    return self.delegate.WriteFlowRequests(requests)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 520, in _RunInTransaction
    ret = function(connection)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 257, in Closure
    return func(self, *args, **new_kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_flows.py", line 660, in WriteFlowRequests
    raise db.AtLeastOneUnknownFlowError(flow_keys, cause=e)
AtLeastOneUnknownFlowError: At least one flow with client id/flow_id in '[(u'C.38074d5298bd8337', u'67FD8847')]' does not exist: (1062, "Duplicate entry '4037280608106152759-1744668743-1' for key 'PRIMARY'")
````

**Comment by grrrrrrrrr** [comment]
The backtraces you posted are all not super critical except for the first one. For the non critical ones:

- You should remove the Worker.smtp_server option so the server doesn't raise when it wants to send an email.
- That last backtrace is weird, it tries to store a flow request that already exists in the db. If hunts get stuck it might be interesting to look at those but I would ignore this one for now.

The first backtrace says the MySQL server went away. Can you maybe check if there are any errors in the MySQL logs? Maybe a request went over the max packet size limit or something like that.

**Comment by atkinsj** [comment]
`Worker.smtp_server` isn't present in my server.local.yaml, so I guess it defaults to localhost?

The only thing I have in the MySQL logs are:

`2019-06-10T18:51:05.127332Z 3847 [Note] Aborted connection 3847 to db: 'grr' user: 'grr' host: '10.10.21.216' (Got timeout reading communication packets)`

**Comment by grrrrrrrrr** [comment]
You are right, that smtp setting defaults to localhost, we should change that.

For the mysql issue, it looks like the MySQL server closes the connection - maybe the adminui was idle for too long - and then the UI is stuck with a broken connection. We could easily catch that specific error and just open a new connection, in many cases (timeouts, ...) that would resolve the issue. We'll look into this.

**Comment by atkinsj** [comment]
Thanks. Is that something that changed with 3.3.0.0? We've never had any issues with this deployment in the past but the console has become unavailable twice since 3.3.0.0 and required a manual service restart.

**Comment by atkinsj** [comment]
FYI, I also just got this:

```
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 524, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 310, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/user.py", line 1852, in Handle
    return self.HandleRelationalDB(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/user.py", line 1826, in HandleRelationalDB
    state=rdf_objects.UserNotification.State.STATE_NOT_PENDING)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 3247, in UpdateUserNotifications
    username, timestamps, state=state)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 520, in _RunInTransaction
    ret = function(connection)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 257, in Closure
    return func(self, *args, **new_kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_users.py", line 371, in UpdateUserNotifications
    cursor.execute(query, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 197, in execute
    return self._forward(self.cursor.execute, query, args=args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 166, in _forward
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
```

**Comment by mbushkov** [comment]
Hi! Thanks for reporting these issues! A few questions:
* Which database are you using - MySQL or MariaDB, and which version?
* Do you have any non-default settings in the database configuration?
* Re "You have an error in your SQL syntax". Do you think you can enable MySQL query logging to see what kind of query that was?

**Comment by atkinsj** [comment]
- MySQL 5.7 on AWS RDS (r4.large)
- No, only the max_allowed_packets tweak to 1073741824.
- I can do that; I'll do that later today.

I'm not sure if the below is related, if I can dig in to it more and RCA I'll open a new issue...

I've also hit a pretty severe issue last night with the frontend dying trying to process response to a very basic hunt across the fleet (File Finder for a glob) and what looks like a memory leak. The log is flooded with the following until the grr_server process is eventually killed by the OOM killer. As of right now, our GRR deployment is totally non-functional as the frontend servers handle very large incoming requests from clients causing this crash (`RX packets 1564225  bytes 2129846742 (1.9 GiB)`). I've just enabled access logs so hopefully I can dig in to it more when I get in to the office.

```
Exception happened during processing of request from ('::ffff:10.10.16.202', 14320, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
---------------------------------
```

I caught the last two lines of a stack trace (AWS autoscaling group that nuked the host before I grabbed the rest, keeping an eye out for the full trace):

```
data = zlib.decompress(packed_message_list.message_list)
MemoryError
```

**Comment by demonchild2112** [comment]
- Regarding the error 'MySQL server has gone away': The issue is that GRR was trying to rollback a transaction after the MySQL connection broke. That is now fixed in HEAD.

- Regarding the SMTP error: That is a red herring, as @grrrrrrrrr mentioned. The server deb sets `grr-monitoring@localhost` as the monitoring email address by default during installation, and there currently isn't a validation step after the email is configured. When clients crash when executing flows (which does happen occasionally), GRR attempts to send the crash details to the configured monitoring email, and that fails when the email address isn't valid. I've submitted a mitigation for this, so we now log a warning instead of printing a stack-trace and returning an error to clients. To skip sending emails entirely, you can set `Monitoring.alert_email` to the empty string in your writeback file.

- Regarding the large payloads from clients: I'd be interested to see the arguments for the hunt which is causing clients to return so much data.

- As for the DecryptionError: That is happening because a `ClientCommunication` proto received by the server is missing a required field, which GRR clients should always set. I'm puzzled as to why that would happen, since the `api_version` field appears to have been [set correctly](https://github.com/google/grr/blob/0abb895bb0a1f0c030807b768bd1bd9746cd9fa2/grr/core/grr_response_core/lib/communicator.py#L131). How easy is it to reproduce the error?

**Comment by atkinsj** [comment]
Thanks @demonchild2112. I actually had to entirely wipe the database and set-up some auto-restart policies to get past whatever issue was happening. It was a simple FileFinder flow with a `/Users/**/file.filetype`.

In terms of reproducibility.. hopefully I never see it again. ;) But all of yesterday up until I was experiencing these symptoms:

- Frontend server starts
- Frontend server spams logs with the SMTP error, broken pipe error, server response is not encrypted error
- Frontend server uses increasingly more memory until the host runs out of memory
- Frontend server becomes unresponsive causing it to fail the AWS ELB healthchecks, AWS kills the instance and spins it back up

I got past it with a cron to restart the frontend server every 30 minutes until whichever client was causing the issue either rebooted/crashed/stopped trying. Sorry I don't have much more data than that to share.

**Comment by atkinsj** [comment]
The original issue I described has happened again this morning:

`A server error occurred.  Please contact the administrator.`

Nothing abnormal in the admin instance logs, just lots of:

`::ffff:$src_ip- - [13/Jun/2019 17:28:36] "GET / HTTP/1.1" 403 63`

and one:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 40, in <lambda>
    return update_wrapper(lambda *a: f(*a)(*a[-2:]), f)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/wsgiapp.py", line 324, in __call__
    return endpoint(request)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/webauth.py", line 270, in Wrapper
    return WEBAUTH_MANAGER.SecurityCheck(func, request, *args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/webauth.py", line 188, in SecurityCheck
    return func(request, *args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/wsgiapp.py", line 167, in Wrapper
    server_logging.LOGGER.LogHttpAdminUIAccess(request, response)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_logging.py", line 72, in LogHttpAdminUIAccess
    data_store.REL_DB.WriteAPIAuditEntry(entry)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 3268, in WriteAPIAuditEntry
    return self.delegate.WriteAPIAuditEntry(entry)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 534, in _RunInTransaction
    cursor.execute(start_query)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 197, in execute
    return self._forward(self.cursor.execute, query, args=args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 166, in _forward
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
```

This is running off grrdocker/grr:latest. Restarting the admin instances resolved it.

I'll try launching them with --verbose tonight.

**Comment by demonchild2112** [comment]
Thanks @atkinsj btw for your efforts in debugging these issues.

From the stack trace in your previous post, what I think is happening is that though retries are now working as expected, there aren't enough of them to consume existing invalid connections in GRR's connection pool. I'll send out a fix for this.

**Comment by demonchild2112** [comment]
The fix is in. Let me know if you continue to see any more database errors.

**Comment by atkinsj** [comment]
I pushed the grrdocker/grr:latest tag to our deployment last week and we haven't had the issue reoccur since then, whereas it happening over the weekend was pretty much guaranteed previously.

Thanks for all the help @demonchild2112!
