### ISSUE TITLE
3.3.0-0 unable to remove label

### ISSUE THREAD

**Issue by 0x0BCA** [google/grr#716]
![image](https://user-images.githubusercontent.com/24981182/60351961-c5084400-99be-11e9-8738-9c78ba5f5f27.png)

with: can only concatenate list (not "RepeatedFieldHelper") to list

Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 524, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 310, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/client.py", line 859, in Handle
    data_store.REL_DB.RemoveClientLabels(cid, token.username, args.labels)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 2923, in RemoveClientLabels
    return self.delegate.RemoveClientLabels(client_id, owner, labels)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 44, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 520, in _RunInTransaction
    ret = function(connection)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 257, in Closure
    return func(self, *args, **new_kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_clients.py", line 643, in RemoveClientLabels
    args = [db_utils.ClientIDToInt(client_id), mysql_utils.Hash(owner)] + labels
TypeError: can only concatenate list (not "RepeatedFieldHelper") to list

**Comment by mbushkov** [comment]
Ah, this was already reported as a comment to an older issue from 2017 (https://github.com/google/grr/issues/492#issuecomment-497070144) and unfortunately has slipped from our radar.
Will look into this. We'll also have to issue a minor release with the fix.

**Comment by mbushkov** [comment]
Minor release pending. Will update this bug when it's done.

**Comment by clairmont32** [comment]
Thanks @mbushkov

**Comment by mbushkov** [comment]
JFYI: the minor GRR release 3.3.0.3 is now done. Docker image should be updated soon.

**Comment by mbushkov** [comment]
Docker image for 3.3.0.3 should be available as of now. The issue seems to be fully resolved.
