### ISSUE TITLE
Grr Docker Installation (Personalized Dockerfile)

### ISSUE THREAD

**Issue by Zakaren** [google/grr#724]
Hi,

I'm trying to install grr through a personalized DockerFile, but i'm getting some errors. Here is my personalized  dockerfile : 
```
# A Docker image capable of running all GRR components.
#
# See https://hub.docker.com/r/grrdocker/grr/
#
# We have configured Travis to trigger an image build every time a new server
# deb is been uploaded to GCS.
#
# Run the container with:
#
# docker run \
#    -e EXTERNAL_HOSTNAME="localhost" \
#    -e ADMIN_PASSWORD="demo" \
#    -p 0.0.0.0:8000:8000 \
#    -p 0.0.0.0:8080:8080 \
#    grrdocker/grr

FROM ubuntu:xenial

LABEL maintainer="grr-dev@googlegroups.com"

ENV GRR_VENV /usr/share/grr-server
ENV PROTOC /usr/share/protobuf/bin/protoc
ENV DEBIAN_FRONTEND noninteractive
# Buffering output (sometimes indefinitely if a thread is stuck in
# a loop) makes for a non-optimal user experience when containers
# are run in the foreground, so we disable that.
ENV PYTHONUNBUFFERED=0

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
  apt-get install -y \
  debhelper \
  default-jre \
  dpkg-dev \
  git \
  libffi-dev \
  libssl-dev \
  python-dev \
  python-pip \
  rpm \
  wget \
  zip \
  mysql-server \
  python-mysqldb

RUN pip install --upgrade --no-cache-dir pip virtualenv && \
    virtualenv --system-site-packages $GRR_VENV

# Install proto compiler
RUN mkdir -p /usr/share/protobuf && \
cd /usr/share/protobuf && \
wget --quiet "https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip" && \
unzip protoc-3.6.1-linux-x86_64.zip && \
rm protoc-3.6.1-linux-x86_64.zip

RUN $GRR_VENV/bin/pip install --upgrade --no-cache-dir wheel six setuptools nodeenv && \
    $GRR_VENV/bin/nodeenv -p --prebuilt --node=10.12.0 && \
    echo '{ "allow_root": true }' > /root/.bowerrc

# Copy the GRR code over.
# grr repo from (https://github.com/google/grr) .
ADD grr /usr/src/grr 

#chmod 777, because i was getting a permission deny error

RUN cd /usr/src/grr \
    chmod 777 /usr/src/grr/docker/install_grr_from_gcs.sh \
    /usr/src/grr/docker/install_grr_from_gcs.sh \
    chmod 777 /usr/src/grr/docker/docker-entrypoint.sh

ENTRYPOINT ["/usr/src/grr/docker/docker-entrypoint.sh"]

# Port for the admin UI GUI
EXPOSE 8000

# Port for clients to talk to
EXPOSE 8080

# Directories used by GRR at runtime, which can be mounted from the host's
# filesystem. Note that volumes can be mounted even if they do not appear in
# this list.
VOLUME ["/usr/share/grr-server/install_data/etc"]

# Copying my personalized configuration files
COPY server.local.yaml /usr/share/grr-server/install_data/etc/ 
COPY grr-server.yaml /usr/share/grr-server/install_data/etc/ 
COPY approvers.yaml /usr/share/grr-server/install_data/etc/
COPY api_acls.yaml /usr/share/grr-server/install_data/etc/

CMD ["grr"]
```
After a successful build : ``` sudo docker build -t grr .  ```
and  :
``` ** sudo docker run \
           -e EXTERNAL_HOSTNAME="localhost" \
           -e ADMIN_PASSWORD="demo" \
	   -v /var/lib/mysql \
           -p 0.0.0.0:8000:8000 \
           -p 0.0.0.0:8080:8080 \
           grr **
 ```

I'm getting the following error (output) :
```
 * Starting MySQL database server mysqld
   ...done.
Admin UI gui is at http://localhost:8000, clients will poll to http://localhost:8080
/usr/src/grr/docker/docker-entrypoint.sh: line 11: grr_server: command not found
/usr/src/grr/docker/docker-entrypoint.sh: line 11: grr_server: command not found
 ```
Do you have an idea how could I fix this ?
Thanks

**Comment by demonchild2112** [comment]
It looks like you are using an old version of the Dockerfile. Could you try again after syncing your local GRR repo to HEAD? You will need to [provide](https://github.com/google/grr/blob/03fb57bd17f95580c3da12b60d3e5f50f178a7ba/appveyor/docker_build/build_docker_image.sh#L13) the commit for the sdists that will be installed in the image, as well as the GCS bucket that they were uploaded to (use `autobuilds.grr-response.com` to fetch the official sdists), when building the image.

`grr_server: command not found` suggests that GRR did not install successfully in the image. If the error occurs again, it might be helpful if I could take a look at the full output of the `docker build` command.

Another thing - you should not have to `chmod 777` anything in order to build and use the image. Do you get permission-denied errors when building the image or when running a container?

**Comment by Zakaren** [comment]
Hi,
Thank you for your reply,
 
I'm afraid that I don't know what to put in the --build-arg GRR_COMMIT field, it is a path to some directory or file ? 

Thank you

**Comment by demonchild2112** [comment]
You can grab a commit SHA from the output of `git log` (or from [github](https://github.com/google/grr/commits/master)). For example, the current HEAD commit is `03fb57bd17f95580c3da12b60d3e5f50f178a7ba`.

**Comment by Zakaren** [comment]
Thank you, the build was successful, but I got some errors after :

```
sudo docker run  -e EXTERNAL_HOSTNAME="localhost"     -e ADMIN_PASSWORD="demo" -v /var/lib/mysql     -p 0.0.0.0:8000:8000     -p 0.0.0.0:8080:8080     grr1
```

The output : 

```
 * Starting MySQL database server mysqld
   ...done.
Admin UI gui is at http://localhost:8000, clients will poll to http://localhost:8080
E0723 13:52:09.164671 139779901744896 server_startup.py:76] Died during config initialization
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/server_startup.py", line 74, in Init
    config_lib.ParseConfigCommandLine(rename_invalid_writeback=False)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/config_lib.py", line 1709, in ParseConfigCommandLine
    _CONFIG.Initialize(filename=flags.FLAGS.config, must_exist=True)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/config_lib.py", line 1212, in Initialize
    self.parser = self.LoadSecondaryConfig(filename)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/config_lib.py", line 1143, in LoadSecondaryConfig
    clone.MergeData(parser.RawData())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/config_lib.py", line 1069, in MergeData
    self.MergeData(v, context_data)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/config_lib.py", line 1078, in MergeData
    raise MissingConfigDefinitionError(msg)
MissingConfigDefinitionError: Missing config definition for Datastore.security_manager. This option is likely deprecated or renamed. Check the release notes.
```

**Comment by Zakaren** [comment]
This is the part of code where the **Datastore.security_manager** is declared on the grr-server.yaml file : 

```
AdminUI Context:
  Logging.filename: "%(Logging.path)/grr-ui.log"
  Datastore.security_manager: FullAccessControlManager
  API.DefaultRouter: ApiCallRouterWithApprovalChecksWithRobotAccess
```

**Comment by Zakaren** [comment]
The issue is resolved, I should build the docker image, not a simple run. 

Thank you

**Comment by demonchild2112** [comment]
Btw, so I understand your motivations better - Are you only building a custom image so you do not have to mount the the config directory on the host every time you run a container (as described [here](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/via-docker.html))?

**Comment by Zakaren** [comment]
Yes, the second part of the documentation you provided, describes exactly what I want. Thanks
