### ISSUE TITLE
grr_config_updater upload_python fails when REL_DB is enabled

### ISSUE THREAD

**Issue by H8545** [google/grr#725]
If Docker image `v3.3.0.0` or above is used to build GRR, `grr_config_updater upload_python` fails.
However, upload function works if a row `--use_rel_db` is removed from a `docker-entrypoint.sh` script and Docker image built locally. It seems like uploading scripts is not working correctly when the REL_DB database format is used.

**Test environment**

```
user@dev:~$ uname -a
Linux dev 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Docker**

```
user@dev:~$ docker -v
Docker version 18.06.1-ce, build e68fc7a
```

**How to reproduce the issue**

_REL_DB is enabled:_

```
user@dev:~/grr$ docker images | grep grr
grr/grr-server-modified   latest              fe47973b917c        33 minutes ago      1.87GB
grrdocker/grr             v3.3.0.0            2418db3ab2c7        8 weeks ago         2.45GB

user@dev:~/grr$ docker run \
> --name grr-server-original \
> -e EXTERNAL_HOSTNAME="localhost" \
> -e ADMIN_PASSWORD="demo" \
> -v /var/lib/mysql \
> -p 0.0.0.0:8000:8000 \
> -p 0.0.0.0:8080:8080 \
> grrdocker/grr:v3.3.0.0

user@dev:~/grr$ docker ps --format "IMAGE: {{.Image}} \nNAME: {{.Names}} \nSTATUS: {{.Status}} \nPORTS: {{.Ports}}" --filter name=grr
IMAGE: grrdocker/grr:v3.3.0.0
NAME: grr-server-original
STATUS: Up About a minute
PORTS: 0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp

user@dev:~/grr$ export GRR_VENV=/usr/share/grr-server && \
> touch test.py && \
> docker cp test.py grr-server-original:/ && \
> docker exec grr-server-original ${GRR_VENV}/bin/grr_config_updater upload_python --file /test.py --platform linux
I0727 06:07:29.331058 140211623954176 server_logging.py:186] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 10, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 24, in ConfigUpdater
    config_updater.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 412, in Run
    app.run(main, flags_parser=lambda argv: parser.parse_args(argv[1:]))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 349, in main
    upload_subdirectory=args.upload_subdirectory)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater_util.py", line 713, in UploadSignedBinary
    private_key=signing_key.GetRawPrivateKey()))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_api_client/root.py", line 129, in Upload
    self._context.SendRequest("UploadGrrBinary", args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_api_client/context.py", line 28, in SendRequest
    return self.connector.SendRequest(handler_name, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/api_shell_raw_access_lib.py", line 90, in SendRequest
    rdf_result = self._CallMethod(method_name, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/api_shell_raw_access_lib.py", line 83, in _CallMethod
    raise errors.UnknownError(e)
grr_api_client.errors.UnknownError: No actual blob references provided.
```

_REL_DB is disabled:_

```
user@dev:~/grr$ docker images | grep grr
grr/grr-server-modified   latest              fe47973b917c        33 minutes ago      1.87GB
grrdocker/grr             v3.3.0.0            2418db3ab2c7        8 weeks ago         2.45GB

user@dev:~/grr$ docker run \
> --name grr-server-modified \
> -e EXTERNAL_HOSTNAME="localhost" \
> -e ADMIN_PASSWORD="demo" \
> -v /var/lib/mysql \
> -p 0.0.0.0:8000:8000 \
> -p 0.0.0.0:8080:8080 \
> grr/grr-server-modified:latest

user@dev:~/grr$ docker ps --format "IMAGE: {{.Image}} \nNAME: {{.Names}} \nSTATUS: {{.Status}} \nPORTS: {{.Ports}}" --filter name=grr
IMAGE: grr/grr-server-modified:latest
NAME: grr-server-modified
STATUS: Up 10 minutes
PORTS: 0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp

user@dev:~/grr$ export GRR_VENV=/usr/share/grr-server && \
> touch test.py && \
> docker cp test.py grr-server-modified:/ && \
> docker exec grr-server-modified ${GRR_VENV}/bin/grr_config_updater upload_python --file /test.py --platform linux
I0726 13:44:50.892924 140578048648960 server_logging.py:186] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/usr/share/grr-server/install_data/etc/server.local.yaml" >
Uploaded PYTHON_HACK to linux//test.py

user@dev:~/grr$ curl --user admin:demo \
> --request GET http://localhost:8000/api/config/binaries/python_hack/linux/test.py
)]}'
{
  "path": "linux/test.py",
  "has_valid_signature": true,
  "type": "PYTHON_HACK",
  "timestamp": 1564205830738592,
  "size": 0
}
```

**Comment by demonchild2112** [comment]
`grr_api_client.errors.UnknownError: No actual blob references provided.`: This means that the file you are attempting to upload is empty.

With the latest docker image, I am able to upload (non-empty) files without a problem.

**Comment by grrrrrrrrr** [comment]
This should work now. Closing this issue, please reopen if the problem still exists in recent versions.
