### ISSUE TITLE
Can't Fetch Artifacts List - grr 3.3.0.4

### ISSUE THREAD

**Issue by jvaldezjr1** [google/grr#729]
I'm new to GRR, and have no idea how to start troubleshooting so here is an error message I get from time to time.  Running in GCE on Ubuntu 16.04.  I was trying to create a flow with the ArtifactCollectorFlow.

![image](https://user-images.githubusercontent.com/7658588/63305273-7468e500-c2a3-11e9-9a3e-b5db767abd54.png)
![image](https://user-images.githubusercontent.com/7658588/63305309-8f3b5980-c2a3-11e9-969b-5041e6691e70.png)

Here is the code from the window:
`Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 528, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 309, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/artifact.py", line 64, in Handle
    reload_datastore_artifacts=True),
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/utils.py", line 85, in NewFunction
    return f(self, *args, **kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/artifact_registry.py", line 399, in GetArtifacts
    results.add(artifact)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/rdfvalue.py", line 218, in __hash__
    "mutation.".format(compatibility.GetName(type(self))))
AssertionError: Usage of Artifact violates Python data model: hash() has changed! Usage of RDFStructs as members of sets or keys of dicts is discouraged. If used anyway, mutating is prohibited, because it causes the hash to change. Be aware that accessing unset fields can trigger a mutation.
`

**Comment by max-vogler** [comment]
Thanks for your report jvaldezjr1. This was an issue in our code base and has been fixed in HEAD. If it occurs too often, please install [GRR from HEAD](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-head-deb.html). Otherwise, the release coming later this quarter will fix it.

**Comment by jvaldezjr1** [comment]
Thank you.  Will doing so upgrade my current install, or will I need to manually remove my current GRR package and reinstall from HEAD if it's an issue?  I'll close this bug also, thanks for the fast response.

**Comment by mbushkov** [comment]
@jvaldezjr1, Installing from a HEAD deb should upgrade your current installation. There's no need to remove the current GRR package. Also, after the server upgrade all the clients should continue to work without updating.
