### ISSUE TITLE
Downloading Flow Results - SQL syntax Error

### ISSUE THREAD

**Issue by keithtyler** [google/grr#732]
Collected ~700 files, when I go to export through the UI (Results tab, then generate archive) we get the following error:

> Archive generation failed for flow 90051C2E on client C.2adaf967040ba9e9: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")

The web UI has the following error in the log:
> ERROR:2019-09-03 20:38:39,443 1093 MainProcess 140060590860032 Thread-68406 http_api:593] Error while processing /api/clients/C.2adaf967040ba9e9/flows/90051C2E/results/files-archive (GET) with ApiGetFlowFilesArchiveHandler: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 532, in HandleRequest
    binary_stream, method_name=method_metadata.name)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/http_api.py", line 407, in _BuildStreamingResponse
    peek = next(content)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_call_handler_base.py", line 53, in GenerateContent
    for chunk in self.content_generator:
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/api_plugins/flow.py", line 634, in _WrapContentGenerator
    for item in generator.Generate(flow_results):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/gui/archive_generator.py", line 171, in Generate
    for chunk in file_store.StreamFilesChunks(client_paths):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/file_store.py", line 497, in StreamFilesChunks
    hash_ids_by_cp.values())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 3456, in ReadHashBlobReferences
    return self.delegate.ReadHashBlobReferences(hashes)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 53, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 259, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 557, in _RunInTransaction
    result = function(connection)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 257, in Closure
    return func(self, *args, **new_kw)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_blobs.py", line 155, in ReadHashBlobReferences
    cursor.execute(query, [hash_id.AsBytes() for hash_id in hashes])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 197, in execute
    return self._forward(self.cursor.execute, query, args=args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 166, in _forward
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue

Currently running 3.3.0post6. If you need additional details let me know!

**Comment by mbushkov** [comment]
@keithtyler , thanks for reporting this! What's your max_allowed_packet setting? If you increase it significantly (by doing `SET GLOBAL max_allowed_packet=<number>`, does the error go away?

**Comment by keithtyler** [comment]
Currently have it set to 160970752. I will double increase that and report back with results.

**Comment by grrrrrrrrr** [comment]
This is a different issue. Here:

https://github.com/google/grr/blob/d399ef6a19c6cef630a6d3edb858250939503121/grr/server/grr_response_server/file_store.py#L467

we call ReadHashBlobReferences without any hashes and that raises the error above. I have a fix ready that returns an empty dict from ReadHashBlobReferences in those cases which will prevent that error but it's unclear to me why there are no hashes for the given client paths in the first place. Maybe client_paths is already empty? This needs more investigation...

**Comment by mbushkov** [comment]
Keith, was it a FileFinder flow that you try to download the files for? Can
you please double check whether it ran with a DOWNLOAD or STAT action?

Cheers,
Misha

**Comment by keithtyler** [comment]
I checked and it was indeed set to HASH, downloading those results via "Download as CSV" worked.
