### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by theshades** [google/grr#742]
Changed the name of the executable and process name to PRO and it breaks on repack...  first saying it is not created, so I created the folder, and it still breaks:
`Repacked into /usr/share/grr-server/executables/installers/PRO_0.0.1_
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 10, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 24, in ConfigUpdater
    config_updater.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 408, in Run
    app.run(main, flags_parser=lambda argv: parser.parse_args(argv[1:]))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 321, in main
    repacking.TemplateRepacker().RepackAllTemplates(upload=upload)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_client_builder/repacking.py", line 236, in RepackAllTemplates
    upload=upload)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_client_builder/repacking.py", line 216, in RepackTemplate
    open(result_path, "rb").read(100 * 1024 * 1024),
IOError: [Errno 2] No such file or directory: u'/usr/share/grr-server/executables/installers/PRO_0.0.1_'
root@GRR-01BG:/etc/mysql/mysql.conf.d# mkdir /usr/share/grr-server/executables/installers/PRO_0.0.1_
root@GRR-01BG:/etc/mysql/mysql.conf.d# grr_config_updater repack_clients
I1029 02:30:30.220077 139721041270592 server_logging.py:185] Writing log file to /usr/share/grr-server/lib/python2.7/site-packages/grr_response_core/var/log//GRRlog.txt
Using configuration <GrrConfigManager  file="/usr/share/grr-server/install_data/etc/grr-server.yaml"  file="/etc/grr//server.local.yaml" >
Repacking template: /usr/share/grr-server/grr-response-templates/templates/grr_3.3.0.8_amd64.deb.zip
Using context: [u'ClientBuilder Context', u'ClientBuilder Context', u'Arch:amd64', u'Platform:Linux', u'Target:Linux', u'Target:LinuxDeb', u'Target:Linux'] and labels: []
Repacked into /usr/share/grr-server/executables/installers/PRO_0.0.1_
Traceback (most recent call last):
  File "/usr/share/grr-server/bin/grr_config_updater", line 10, in <module>
    sys.exit(ConfigUpdater())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/distro_entry.py", line 24, in ConfigUpdater
    config_updater.Run()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 408, in Run
    app.run(main, flags_parser=lambda argv: parser.parse_args(argv[1:]))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/config_updater.py", line 321, in main
    repacking.TemplateRepacker().RepackAllTemplates(upload=upload)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_client_builder/repacking.py", line 236, in RepackAllTemplates
    upload=upload)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_client_builder/repacking.py", line 216, in RepackTemplate
    open(result_path, "rb").read(100 * 1024 * 1024),
IOError: [Errno 21] Is a directory: u'/usr/share/grr-server/executables/installers/PRO_0.0.1_'
`

**Comment by mbushkov** [comment]
In order for us to reproduce this, please specify:
1. The OS version you run this on.
1. The GRR version.
1. Precise command that you used.
1. Configuration changes that you made.
