### ISSUE TITLE
centos 7-1810 installing problem

### ISSUE THREAD

**Issue by burakatabay** [google/grr#746]
ı use the source code installation documents.

but ı stacked here --

Running setup.py develop for grr-response-server
ERROR: Command errored out with exit status 1:
command: /root/INSTALL/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/grr/grr/server/setup.py'"'"'; file='"'"'/root/grr/grr/server/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps
cwd: /root/grr/grr/server/
Complete output (45 lines):
/root/INSTALL/lib/python2.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '3.3.0post8' to '3.3.0.post8'
normalized_version,
running develop

> core-js@3.2.1 postinstall /root/grr/grr/server/grr_response_server/gui/static/node_modules/core-js
> node scripts/postinstall || echo "ignore"

sh: node: command not found
ignore

> grpc@1.23.3 install /root/grr/grr/server/grr_response_server/gui/static/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: node-pre-gyp: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-05T21_05_16_115Z-debug.log
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/grr/grr/server/setup.py", line 225, in <module>
    setup(**setup_args)
  File "/root/INSTALL/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/root/python2.7.16/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/root/python2.7.16/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/root/python2.7.16/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/root/grr/grr/server/setup.py", line 103, in run
    make_ui_files()
  File "/root/grr/grr/server/setup.py", line 53, in make_ui_files
    "npm ci", shell=True, cwd="grr_response_server/gui/static")
  File "/root/python2.7.16/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'npm ci' returned non-zero exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /root/INSTALL/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/grr/grr/server/setup.py'"'"'; file='"'"'/root/grr/grr/server/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

ı cant understand this problem ?

**Comment by demonchild2112** [comment]
Hey @burakatabay 

It seems that node isn't installed in your virtualenv:

```bash
sh: node: command not found
```

Did you use [travis/install.sh](https://github.com/google/grr/blob/master/travis/install.sh) to install GRR? The script should take care of installing `node` in the virtualenv before trying to install GRR. To verify that `node` got installed:

- Activate the virtualenv: `source $HOME/INSTALL/bin/activate`
- Check that `node` is in the PATH: `which node`, which should print `~/INSTALL/bin/node`

Could you also check the Python version used in the virtualenv (`python --version`)? Centos 7's default Python version is 2.7.5, which is too old. GRR requires at least 2.7.11. You can follow the recipe in https://github.com/google/grr/blob/master/docker/Dockerfile.centos7 to install a newer version of Python on your machine, then use `virtualenv $HOME/INSTALL --python=$(which python2.7)` to create a virtualenv based on the newer Python version.

Generally, we recommend installing GRR server components on Ubuntu Xenial, since that is the only platform we explicitly support for running GRR servers. GRR *should* be installable on Centos, but installation may be a bit harder, as you have found.
