### ISSUE TITLE
The client does not work properly after installation

### ISSUE THREAD

**Issue by yexia553** [google/grr#747]
Hi all：
`uname -a` info is `Linux VM-111-46-ubuntu 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`. 
And I got grr by the command  ` wget https://storage.googleapis.com/releases.grr-response.com/grr-server_3.3.0-8_amd64.deb`，so my grr version is 3.3.0.8
I install grr according to this page [Installing from a release server deb (recommended)](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html), but I changed some steps.
1. I am using the MySQL instance provided by a Public Cloud, not the self-built MySQL on the same server
2. The value of max_allowed_packet is 1073741824, more than 20971520 
3. I change the command from`CREATE USER 'grr'@'localhost' IDENTIFIED BY 'password';` to `CREATE USER 'grr'@'%' IDENTIFIED BY 'password';` ,and `GRANT ALL ON grr.* TO 'grr'@'%';`， because the grr user of the database should be able to log in remotely
**I used root of MySQL when I installing grr，because it recommended me to use**，I don't know if this is correct.
and now my problem is : The client sometimes does not work properly. Like the picture I attached.
![hostinfo2-error](https://user-images.githubusercontent.com/25142514/68989356-7598b680-0880-11ea-89ff-8d9125d6aa2f.PNG)
![hostinfo-error](https://user-images.githubusercontent.com/25142514/68989357-76314d00-0880-11ea-832a-2a0798079046.png)

1. It stuck at the stage of host information collection stage, and a lot of host information can not be collected，like “Memory Size”、“Users”、“MAC”....,
2. Folw created by GRRWorker is always "running" but no result

I found  some "OperationalError: (2006, 'MySQL server has gone away')" in both grr-http-server.log and grr-worker.log , but Mysql is actually working properly.

**example of grr-worker.log:**
`ERROR:2019-11-16 05:29:54,143 21986 MainProcess 140281434961664 flow_processing_request_handler mysql_flows:1227] _FlowProcessingRequestHandlerLoop raised (2006, 'MySQL server has gone away').
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_flows.py", line 1218, in _FlowProcessingRequestHandlerLoop
    msgs = self._LeaseFlowProcessingReqests()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 52, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 245, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 576, in _RunInTransaction
    connection.rollback()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 136, in rollback
    self.con.rollback()
OperationalError: (2006, 'MySQL server has gone away')`

**example of grr-http-server.log:**
`ERROR:2019-11-15 20:05:21,507 21991 MainProcess 140303775708928 Thread-7537 frontend:189] Had to respond with status 500.
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 183, in do_POST
    self.Control()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 53, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 32, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 247, in Control
    request_comms, responses_comms)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 53, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 32, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/frontend_lib.py", line 239, in HandleMessageBundles
    request_comms)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/lib/communicator.py", line 492, in DecodeMessages
    remote_public_key = self._GetRemotePublicKey(source)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/frontend_lib.py", line 81, in _GetRemotePublicKey
    md = data_store.REL_DB.ReadClientMetadata(remote_client_id)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 676, in ReadClientMetadata
    result = self.MultiReadClientMetadata([client_id])
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db.py", line 2829, in MultiReadClientMetadata
    return self.delegate.MultiReadClientMetadata(client_ids)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/db_utils.py", line 52, in Decorator
    result = f(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_utils.py", line 245, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql.py", line 576, in _RunInTransaction
    connection.rollback()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/databases/mysql_pool.py", line 136, in rollback
    self.con.rollback()
`
and I find a lot of error log in grr-http-server.log like this.
`ERROR:2019-11-15 22:14:21,860 21991 MainProcess 140303307884288 Thread-16201 frontend:189] Had to respond with status 500.
Traceback (most recent call last):
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 183, in do_POST
    self.Control()
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 53, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_core/stats/stats_utils.py", line 32, in Decorated
    return func(*args, **kwargs)
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 252, in Control
    self.Send(responses_comms.SerializeToBytes())
  File "/usr/share/grr-server/local/lib/python2.7/site-packages/grr_response_server/bin/frontend.py", line 94, in Send
    self.wfile.write(header.encode("utf-8"))
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 104] Connection reset by peer
`
Thank you very much!

**Comment by mbushkov** [comment]
Hm, in this case it seems that the MySQL database gets overloaded and can't accept any more incoming requests. In this case, there's not much GRR can do - in-flight flows will fail.
Do you think you can get a bigger cloud instance for your MySQL db, so that it can handle more load? That might help.

**Comment by yexia553** [comment]
> Hm, in this case it seems that the MySQL database gets overloaded and can't accept any more incoming requests. In this case, there's not much GRR can do - in-flight flows will fail.
> Do you think you can get a bigger cloud instance for your MySQL db, so that it can handle more load? That might help.

Thank you very much, I will have a try.

**Comment by yexia553** [comment]
My system is “Ubuntu 18.04.1”，is not the required one in [DOC](https://grr-doc.readthedocs.io/en/latest/installing-grr-server/from-release-deb.html)(Ubuntu Xenial),this was a mistake caused by communication problems between departments，I will test in the correct system version。
