### ISSUE TITLE
Hunt does not schedule clients after TypeError.

### ISSUE THREAD

**Issue by huskyjag** [google/grr#751]
#### Description

We have deployed GRR v3.4.0.0 on our CentOS-based servers. The clients are still running on v3.2.4.6. We created some hunts, it was approved but when trying to start the hunt, it results in a TypeError (`TypeError: sequence item 0: expected str instance, bytes found`, see traceback below). Afterwards, the hunt is in STARTED state, but does not seem to schedule any clients. Further, the number of tasks on the worker are 0 (according to the exported metrics). There are no Errors on the Error tab in the hunt.

Flows are working fine.

#### To reproduce

1. Browse to Hunts
2. Create a new Hunt, for example: Interrogate with 20 clients at a rate of 5 clients.
3. Start the hunt and wait for approval
4. After approval is given, start the hunt.
5. Error message appears and hunt is in state STARTED, but does not schedule any clients

#### Traceback

```
ERROR:2019-12-17 09:46:55,627 59030 MainProcess 140430524016384 Thread-102 http_api:593] Error while processing /api/hunts/04776236 (PATCH) with ApiModifyHuntHandler: sequence item 0: expected str instance, bytes found
Traceback (most recent call last):
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 535, in HandleRequest
    result = self.CallApiHandler(handler, args, token=token)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 330, in CallApiHandler
    result = handler.Handle(args, token=token)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/hunt.py", line 1366, in Handle
    hunt_obj = hunt.StartHunt(hunt_obj.hunt_id)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/hunt.py", line 299, in StartHunt
    _ScheduleGenericHunt(hunt_obj)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/hunt.py", line 244, in _ScheduleGenericHunt
    data_store.REL_DB.WriteForemanRule(foreman_condition)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 3070, in WriteForemanRule
    return self.delegate.WriteForemanRule(rule)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/db_utils.py", line 52, in Decorator
    result = f(*args, **kwargs)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_utils.py", line 245, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql.py", line 557, in _RunInTransaction
    result = function(connection)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_utils.py", line 243, in Closure
    return func(self, *args, **new_kw)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_foreman_rules.py", line 26, in WriteForemanRule
    cursor.execute(query, [rule.hunt_id, exp_str, rule_str, exp_str, rule_str])
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_pool.py", line 197, in execute
    return self._forward(self.cursor.execute, query, args=args)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_pool.py", line 166, in _forward
    return method(*args, **kwargs)
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 234, in execute
    args = tuple(map(db.literal, args))
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 316, in literal
    s = self.escape(o, self.encoders)
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/converters.py", line 90, in quote_tuple
    return "(%s)" % (','.join(escape_sequence(t, d)))
TypeError: sequence item 0: expected str instance, bytes found
```

#### Environment
* GRR version: v3.4.0.0
* Operating System: CentOS 7
* Python: 3.6.9
* Datastore: MariaDB 10.4.8

Let me know if I can provide any further details.

Thanks!

**Comment by huskyjag** [comment]
After some more investigation, we've found the same error appearing on the **InterrogateClientsCronJob**:
```
sequence item 0: expected str instance, bytes found

Traceback (most recent call last):
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/cronjobs.py", line 110, in StartRun
    self.Run()
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/flows/cron/system.py", line 259, in Run
    self.StartInterrogationHunt()
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/flows/cron/system.py", line 242, in StartInterrogationHunt
    output_plugins=self.GetOutputPlugins())
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/hunt.py", line 225, in CreateAndStartHunt
    StartHunt(hunt_obj.hunt_id)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/hunt.py", line 299, in StartHunt
    _ScheduleGenericHunt(hunt_obj)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/hunt.py", line 244, in _ScheduleGenericHunt
    data_store.REL_DB.WriteForemanRule(foreman_condition)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 3070, in WriteForemanRule
    return self.delegate.WriteForemanRule(rule)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/db_utils.py", line 52, in Decorator
    result = f(*args, **kwargs)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_utils.py", line 245, in Decorated
    return self._RunInTransaction(Closure, readonly)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql.py", line 557, in _RunInTransaction
    result = function(connection)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_utils.py", line 243, in Closure
    return func(self, *args, **new_kw)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_foreman_rules.py", line 26, in WriteForemanRule
    cursor.execute(query, [rule.hunt_id, exp_str, rule_str, exp_str, rule_str])
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_pool.py", line 197, in execute
    return self._forward(self.cursor.execute, query, args=args)
  File "/opt/grr/lib64/python3.6/site-packages/grr_response_server/databases/mysql_pool.py", line 166, in _forward
    return method(*args, **kwargs)
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 234, in execute
    args = tuple(map(db.literal, args))
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 316, in literal
    s = self.escape(o, self.encoders)
  File "/opt/grr/lib64/python3.6/site-packages/MySQLdb/converters.py", line 90, in quote_tuple
    return "(%s)" % (','.join(escape_sequence(t, d)))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by mbushkov** [comment]
@huskyjag , thanks for reporting this!
Quick question: as 3.4.0.0 wasn't oficially released yet, did you build the server yourself or used the latest built debian package (built from HEAD) from us?

**Comment by huskyjag** [comment]
Hey @mbushkov, thanks for your reply. We've build the server ourselves (mostly based off the travis scripts that are also used for building the debian package).

I just saw the new version mentioned in the commits, maybe I should've waited :)

**Comment by mbushkov** [comment]
We're very close to releasing 3.4.0.0 - the clients are working, but we haven't done full end-to-end testing yet. It's a rather big switch, since the new version is Python 3 only, so some bugs are to be expected :/
We'll look into the hunts issue and will fix it asap in HEAD.

**Comment by huskyjag** [comment]
Thank you very much and sorry for the troubles caused. I somehow assumed that it was released when I saw it in the repo. We can easily roll back to an older release anytime.

Let me know if I can provide any further information.

**Comment by mbushkov** [comment]
I think that this bug was actually fixed here: https://github.com/google/grr/commit/1869d875aea1ebc3ec419cf996d3bd9b76b0a792 (see "MySQL bug fix for foreman rules." in the description): 

@huskyjag - it's likely that rebuilding the server from the latest commit will fix the issue for you. Can you please check if it's so?

**Comment by huskyjag** [comment]
Can confirm :-) We rebuilded based on the latest commit and it works.

Thanks for the great support! 👍
