### ISSUE TITLE
vadinfo:  Unknown format code 'x' for object of type 'str'

### ISSUE THREAD

**Issue by keithtyler** [google/grr#77]
When running vadinfo in the web gui, it always returns:

```python
Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_2-py2.7.egg/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_2-py2.7.egg/grr/gui/views.py", line 159, in RenderGenericRenderer
    result = method(request, result) or result
  File "/usr/local/lib/python2.7/dist-packages/grr-0.3.0_2-py2.7.egg/grr/gui/plugins/rekall_viewer.py", line 240, in Layout
    self.free_text.append(format_string.format(*args))
ValueError: Unknown format code 'x' for object of type 'str'
```

The results are there and can be viewed with rekall. Let me know if any more info is needed.

**Comment by destijl** [comment]
So with current server and 3.0.0.5 client this works and renders, if you look in the browse filesystem view, find the right collection, and click results.  Opening a separate bug to make this more usable.
