### ISSUE TITLE
IE history parser issue

### ISSUE THREAD

**Issue by mbushkov** [google/grr#778]
GRR 3.4.0.1 on Ubuntu server 18.04

Traceback (most recent call last): File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/flow_base.py", line 633, in RunStateMethod method(responses) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/flows/general/collectors.py", line 269, in ProcessFileFinderResults messages=[r.stat_entry for r in responses]) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/flow_base.py", line 241, in CallStateInline getattr(self, next_state)(responses) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/flows/general/collectors.py", line 628, in ProcessCollected self._ParseResponses(list(responses), artifact_name, source) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/flows/general/collectors.py", line 733, in _ParseResponses self) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_server/artifact.py", line 450, in ApplyParsersToResponses parser.ParseFile(knowledge_base, response.pathspec, filedesc)) File "/usr/share/grr-server/lib/python3.6/site-packages/grr_response_core/lib/parsers/ie_history.py", line 47, in ParseFile source_path=pathspec.CollapsePath()) UnboundLocalError: local variable 'pathspec' referenced before assignment

**Comment by panhania** [comment]
This has been fixed and is available since 02d3b45707055444015d76ee300bd57b803d9879.
