### ISSUE TITLE
thrdscan: TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by keithtyler** [google/grr#78]
When you run 'thrdscan' from the web ui the client returns:

``` python
Enumerating VADs in %s (%s)",["OUTLOOK.EXE",2408],{}],["p","Merging export table: %s",["??0OdfStgParams@@QAE@XZ"],{}],["e","
Traceback (most recent call last):
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.session", line 448, in _RunPlugin
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.plugins.windows.modscan", line 179, in render
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.kb", line 481, in format_address
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.kb", line 562, in get_nearest_constant_by_address
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.kb", line 333, in LoadProfileForDll
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.session", line 590, in report_progress
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.session", line 229, in Broadcast
  File "c:\grr_build\autobuild\20140911_1115_qq0s9d\build\grr\out00-PYZ.pyz\rekall.ui.json_renderer", line 590, in RenderProgress
TypeError: 'tuple' object does not support item assignment
```

So far I have tested this on two Windows 7 x64 machines.

**Comment by destijl** [comment]
This particular problem seems to be fixed with new client and server, but instead it hit the memory limit and crashed.  @scudette

**Comment by grrrrrrrrr** [comment]
Obsolete.
