### ISSUE TITLE
Unable to add custom email

### ISSUE THREAD

**Issue by knsankar** [google/grr#812]
Hello,

I am trying to set custom email to users. I followed the email config in documentation. 

I added this line `Email.enable_custom_email_address: true` in server config. restarted the services.

when I try to run `grr_api_shell_raw_access  --exec_code "grrapi.root.GrrUser('admin').Get().Modify(email='myemail@mydomain.com')"` I get the following error.

Traceback (most recent call last):
  File "/opt/grr/GRR_ENV/bin/grr_api_shell_raw_access", line 8, in <module>
    sys.exit(ApiShellRawAccess())
  File "/opt/grr/GRR_ENV/lib/python3.6/site-packages/grr_response_server/distro_entry.py", line 19, in ApiShellRawAccess
    app.run(api_shell_raw_access.main)
  File "/opt/grr/GRR_ENV/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/grr/GRR_ENV/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/grr/GRR_ENV/lib/python3.6/site-packages/grr_response_server/bin/api_shell_raw_access.py", line 89, in main
    exec (flags.FLAGS.exec_code, dict(grrapi=grrapi))
  File "<string>", line 1, in <module>
TypeError: Modify() got an unexpected keyword argument 'email'

server version: GRR server 3.4.0post1
OS version: CentOS Linux 7

**Comment by mol123** [comment]
Hi,

support for custom email addresses has been introduced in [GRR version 3.4.2.0 Released July 06 2020](https://grr-doc.readthedocs.io/en/latest/release-notes.html#july-06-2020). You seem to be running 3.4.0.1.

(We should probably mention this in the docs.)
