### ISSUE TITLE
macOS 11.0 support, Library Foundation not found

### ISSUE THREAD

**Issue by mikemackintosh** [google/grr#825]
**Environment**
Installed GRR from DEB, version `3.4.0.1` on macOS Big Sur developer beta 4.
```
sw_vers
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5343i
```

**Describe the issue**
GRR fails to launch as a result of the missing Foundation (CTypes) library.

**Error logs**
``` bash
I0814 12:26:37.996510 4527623680 client_logging.py:116] Writing log file to /var/log/GRRlog.txt
INFO:2020-08-14 12:26:37,996 client_logging:116] Writing log file to /var/log/GRRlog.txt
Traceback (most recent call last):
  File "site-packages/grr_response_client/client.py", line 102, in <module>
  File "site-packages/absl/app.py", line 299, in run
  File "site-packages/absl/app.py", line 250, in _run_main
  File "site-packages/grr_response_client/client.py", line 92, in main
  File "site-packages/grr_response_client/comms.py", line 977, in __init__
  File "site-packages/grr_response_client/comms.py", line 142, in __init__
  File "site-packages/grr_response_client/comms.py", line 175, in _GetProxies
  File "site-packages/grr_response_client/client_utils_osx.py", line 36, in FindProxies
  File "site-packages/grr_response_client/osx/objc.py", line 202, in __init__
  File "site-packages/grr_response_client/osx/objc.py", line 133, in __init__
  File "site-packages/grr_response_client/osx/objc.py", line 95, in LoadLibrary
  File "site-packages/grr_response_client/osx/objc.py", line 73, in SetCTypesForLibrary
grr_response_client.osx.objc.ErrorLibNotFound: Library Foundation not found
```

**Additional context**
Manual installation of Xcode 12 beta Command Line Developer Tools resolved many similar issues for Ruby-based projects, but not Python.

**Comment by max-vogler** [comment]
Thanks for your bug report! This is a [regression from Big Sur](https://www.reddit.com/r/MacOSBeta/comments/hfknpa/is_corefoundation_missing_for_everyone_on_big_sur/). I'm on it, will update this issue once a workaround is done.

**Comment by max-vogler** [comment]
This has been fixed in [9a96b96b](https://github.com/google/grr/commit/9a96b96bec76fd06e4f43e3a46cb7450c06e4b88#diff-d4292f874d9df6c158aafedcc3544831) and is part of our next release.

**Comment by dparker18** [comment]
I am seeing this exact error on an Apple Silicon machine but the same installer works on Intel. Both machines are Big Sur 11.2.3. No difference after installing Xcode.

Is M1 support a known issue? Any known workarounds? I'm happy to help.

**Comment by dparker18** [comment]
Interesting:
```
bash-3.2# python2 -c 'import ctypes.util; print(ctypes.util.find_library("Foundation"))'
/System/Library/Frameworks/Foundation.framework/Foundation

bash-3.2# python3 -c 'import ctypes.util; print(ctypes.util.find_library("Foundation"))'
None
```

**Comment by max-vogler** [comment]
@dparker18, are you encountering the error when installing GRR server and client from HEAD?

Our [objc.py](https://github.com/google/grr/blob/master/grr/client/grr_response_client/osx/objc.py#L51) contains some fixes for this. Even with`ctypes.util.find_library("Foundation")` returning `None`, we try to load the library directly:

```py
ctypes.cdll.LoadLibrary('/System/Library/Frameworks/Foundation.framework/Foundation')
```
