### ISSUE TITLE
wmi_parser errors

### ISSUE THREAD

**Issue by pidydx** [google/grr#87]
We get a lot of errors associated with the wmi_parser.  The clients are all 3.0.0.3 and the server is pretty recent.

ERROR:2015-01-02 00:56:59,498 flow_runner:873] Error in flow aff4:/hunts/W:F5AF45EF/C.0e550087c9a8a545/W:42170A93/W:635150B6 (aff4:/C.0e550087c9a8a545). Trace: Traceback (most recent call last):
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_2-py2.7.egg/grr/lib/flow_runner.py", line 528, in RunStateMethod
    responses=responses)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_2-py2.7.egg/grr/lib/flow.py", line 310, in Decorated
    res = f(*args[:f.func_code.co_argcount])
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_2-py2.7.egg/grr/lib/flows/general/collectors.py", line 479, in ProcessCollected
    artifact_name, collector)
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_2-py2.7.egg/grr/lib/flows/general/collectors.py", line 650, in _ParseResponses
    for result in result_iterator:
  File "/opt/grr/lib64/python2.7/site-packages/grr-0.3.0_2-py2.7.egg/grr/parsers/wmi_parser.py", line 103, in Parse
    size = int(result.get("Size"))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by grrrrrrrrr** [comment]
This should now be fixed.
