### ISSUE TITLE
Error accessing UI dashboard after deleting a client

### ISSUE THREAD

**Issue by knsankar** [google/grr#903]
I deleted a client using the comment mentioned in the docs.

grr_console  --code_to_execute 'data_store.REL_DB.DeleteClient(u"C.edeae1a8cd8c4f8f")'

I am getting following error when I access the dashboard after deleting a client.

Actually, the client was in "Recently accessed", I think the UI is trying to access the deleted client, hence the error.
Is there a cleaner way to do it?

Traceback (most recent call last):
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 758, in ReadClientFullInfo
return result[client_id]
KeyError: 'C.edeae1a8cd8c4f8f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 512, in HandleRequest
result = self.CallApiHandler(handler, args, context=context)
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/http_api.py", line 310, in CallApiHandler
result = handler.Handle(args, context=context)
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 955, in Handle
items = list(itertools.islice(approvals, args.offset, end))
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 658, in _FilterRelationalApprovalRequests
client_approval = approval_create_fn(ar)
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 948, in
approvals, lambda ar: ApiClientApproval().InitFromDatabaseObject(ar),
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/gui/api_plugins/user.py", line 405, in InitFromDatabaseObject
db_obj.subject_id)
File "/srv/grr/lib64/python3.6/site-packages/grr_response_server/databases/db.py", line 760, in ReadClientFullInfo
raise UnknownClientError(client_id)
grr_response_server.databases.db.UnknownClientError: Client with id 'C.edeae1a8cd8c4f8f' does not exist

**Comment by mbushkov** [comment]
The issue here is that you had an approval request that was referencing the deleted client. Latest approval requests are displayed on GRR AdminUI's home page. Deleting the clients directly from the database is a kind of a hack that normally works. Unfortunately here you've hit the issue that wasn't encountered before.

A simple workaround might be to not hit the home page. I.e. you can say `http://<your grr address>/#/hunts` and then use the menu on the left and the search as you normally would. If you request a few more approvals, the broken one should be pushed from the list of the latest approvals list and eventually the home page will work again.

A general comment: we'll look into properly supporting clients deletion. The current approach of using grr_console is hacky and is prone to issues like the one you have.

**Comment by panhania** [comment]
> The current approach of using grr_console is hacky and is prone to issues like the one you have.

While having a proper support for it in the UI would certainly be nice, I would also expect `data_store.REL_DB.DeleteClient` to correctly handle this situation. I think we just miss some foreign key constraint that would make us acknowledge the issue before.

**Comment by mbushkov** [comment]
@panhania - the client id is referenced inside a serialized approval proto, this is why we don't catch it via the foreign key constraints.

**Comment by max-vogler** [comment]
The client id is in the column `subject_id varchar(128)`, which can contain IDs of different entity types (hunt, client, cronjob). That's why there is no foreign key constraint.
