### ISSUE TITLE
GRR Client Crashes "Serialized message too large"

### ISSUE THREAD

**Issue by bprykhodchenko** [google/grr#978]
**Environment**
- The GRR is installed on a VM running on ESXi on-prem. The VM runs Ubuntu 18.04 and GRR was installed from DEB (using the official documentation)
- GRR Version is 3.4.6.0
- Ubuntu 18.04
- Windows 10

**Describe the issue**
When I do the Memory Dump of All processes except GRR it works fine for some time, but at some point in time I get this message:

CRITICAL:2022-05-30 11:50:07,252 fleetspeak_client:117] Fatal error occurred:
Traceback (most recent call last):
  File "site-packages\grr_response_client\fleetspeak_client.py", line 111, in _RunInLoop
  File "site-packages\grr_response_client\fleetspeak_client.py", line 209, in _SendOp
  File "site-packages\grr_response_client\fleetspeak_client.py", line 176, in _SendMessages
  File "site-packages\fleetspeak\client_connector\connector.py", line 144, in Send
  File "site-packages\fleetspeak\client_connector\connector.py", line 154, in _SendImpl
ValueError: Serialized message too large, size must be at most 2097152, got 2323650

So it doesn't like the message size. Now, the question, where this limit can be increased?

**Comment by ITPro17** [comment]
Yes, I know the solution.
1. You need to downgrade the kernel of your OS to 16
2. Remove the database you have. Instead, install the Hadoop cluster.
3. Connect GRR to Hadoop

It should fix the issue.

**Comment by max-vogler** [comment]
Thanks for your report. This looks like a legit issue on the GRR client side, we'll look into it. Increasing this limit on the client side likely creates more problems on the server side, so changing the chunking logic or similar is probably the way forward.

**Comment by bprykhodchenko** [comment]
> Thanks for your report. This looks like a legit issue on the GRR client side, we'll look into it. Increasing this limit on the client side likely creates more problems on the server side, so changing the chunking logic or similar is probably the way forward.

So I have tried to decrease the Chunk size to 2000000, which is less then the agent able to receive and the same issue occured:

CRITICAL:2022-06-01 10:20:24,761 fleetspeak_client:117] Fatal error occurred:
Traceback (most recent call last):
  File "site-packages\grr_response_client\fleetspeak_client.py", line 111, in _RunInLoop
  File "site-packages\grr_response_client\fleetspeak_client.py", line 209, in _SendOp
  File "site-packages\grr_response_client\fleetspeak_client.py", line 176, in _SendMessages
  File "site-packages\fleetspeak\client_connector\connector.py", line 144, in Send
  File "site-packages\fleetspeak\client_connector\connector.py", line 154, in _SendImpl
ValueError: Serialized message too large, size must be at most 2097152, got 2579672

So it is definitely something to be fixed in GRR.

**Comment by mbushkov** [comment]
I looked at the YaraProcessDump client action. It dumps the memory on disk and the sends back a data structure with information about all the processes:
https://github.com/google/grr/blob/master/grr/client/grr_response_client/client_actions/memory.py#L767

What this means: if the `result` proto is larger than 2Mb in the serialized form, the client action will fail. If the machine has a lot of memory and a lot of processes, then growing over 2Mb is likely possible. We need to look into either:
* Chunking response, or
* Increasing the limit from 2Mb to a higher value. I have to check what's the motivation for the 2Mb limit is.

**Comment by bprykhodchenko** [comment]
Hello,
as for your question - I just run the YARA Memory Dump from UI, I do not use CLI to include specific command line arguments.

As for the solution,
1. I was changing the chunk size to smaller then the client can "eat" (in flow parameters), but I was running into the same issue.
2. Should I wait for a fixed version, OR
3. Should I download the source code, change the MAX_SIZE in connect.py file to, say, 4 MB, and install the server from the source code?
